using Lokad.Lython.Runtime;

namespace Lokad.Lython.Frontend;

internal static partial class StaticContracts
{
    private static class DataCallableContractCatalog
    {
        public static readonly StaticCallableContract[] Contracts =
        [
        new(AbstractValueKind.Dict, "get", 1, 2, "LA3126", "dict.get(key[, default]) expects one key and an optional default.", parameterNames: ["key", "default"]),
        new(AbstractValueKind.Dict, "keys", 0, 0, "LA3127", "dict.keys() expects no arguments."),
        new(AbstractValueKind.Dict, "values", 0, 0, "LA3128", "dict.values() expects no arguments."),
        new(AbstractValueKind.Dict, "items", 0, 0, "LA3129", "dict.items() expects no arguments."),
        new(AbstractValueKind.Dict, "update", 1, 1, "LA3130", "dict.update(mapping) expects one dictionary argument.", StaticMutationKind.MutatesReceiver, ["mapping"]),
        new(AbstractValueKind.Dict, "pop", 1, 1, "LA3131", "dict.pop(key) expects one key.", StaticMutationKind.MutatesReceiver, ["key"]),
        new(AbstractValueKind.Dict, "copy", 0, 0, "LA3132", "dict.copy() expects no arguments."),
        new(AbstractValueKind.Dict, "clear", 0, 0, "LA3133", "dict.clear() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.Dict, "setdefault", 1, 2, "LA3134", "dict.setdefault(key[, default]) expects one key and an optional default.", StaticMutationKind.MutatesReceiver, ["key", "default"]),
        new(AbstractValueKind.Set, "add", 1, 1, "LA3135", "set.add(value) expects one positional argument.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.Set, "discard", 1, 1, "LA3136", "set.discard(value) expects one positional argument.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.Set, "remove", 1, 1, "LA3137", "set.remove(value) expects one positional argument.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.Set, "copy", 0, 0, "LA3138", "set.copy() expects no arguments."),
        new(AbstractValueKind.Set, "clear", 0, 0, "LA3139", "set.clear() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.Set, "pop", 0, 0, "LA3139", "set.pop() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.Set, "union", 0, ArgumentCountLimit.Unbounded, "LA3139", "set.union(*others) expects positional iterable operands."),
        new(AbstractValueKind.Set, "intersection", 0, ArgumentCountLimit.Unbounded, "LA3139", "set.intersection(*others) expects positional iterable operands."),
        new(AbstractValueKind.Set, "difference", 0, ArgumentCountLimit.Unbounded, "LA3139", "set.difference(*others) expects positional iterable operands."),
        new(AbstractValueKind.Set, "symmetric_difference", 1, 1, "LA3139", "set.symmetric_difference(other) expects one positional iterable operand."),
        new(AbstractValueKind.Set, "isdisjoint", 1, 1, "LA3139", "set.isdisjoint(other) expects one positional iterable operand."),
        new(AbstractValueKind.Set, "issubset", 1, 1, "LA3139", "set.issubset(other) expects one positional iterable operand."),
        new(AbstractValueKind.Set, "issuperset", 1, 1, "LA3139", "set.issuperset(other) expects one positional iterable operand."),
        new(AbstractValueKind.Set, "update", 0, ArgumentCountLimit.Unbounded, "LA3139", "set.update(*others) expects positional iterable operands.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.Set, "intersection_update", 0, ArgumentCountLimit.Unbounded, "LA3139", "set.intersection_update(*others) expects positional iterable operands.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.Set, "difference_update", 0, ArgumentCountLimit.Unbounded, "LA3139", "set.difference_update(*others) expects positional iterable operands.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.Set, "symmetric_difference_update", 1, 1, "LA3139", "set.symmetric_difference_update(other) expects one positional iterable operand.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.SetType, "add", 1, 1, "LA3135", "set.add(value) expects one positional argument.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.SetType, "discard", 1, 1, "LA3136", "set.discard(value) expects one positional argument.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.SetType, "remove", 1, 1, "LA3137", "set.remove(value) expects one positional argument.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.SetType, "copy", 0, 0, "LA3138", "set.copy() expects no arguments."),
        new(AbstractValueKind.SetType, "clear", 0, 0, "LA3139", "set.clear() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.SetType, "pop", 0, 0, "LA3139", "set.pop() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.SetType, "union", 0, ArgumentCountLimit.Unbounded, "LA3139", "set.union(*others) expects positional iterable operands."),
        new(AbstractValueKind.SetType, "intersection", 0, ArgumentCountLimit.Unbounded, "LA3139", "set.intersection(*others) expects positional iterable operands."),
        new(AbstractValueKind.SetType, "difference", 0, ArgumentCountLimit.Unbounded, "LA3139", "set.difference(*others) expects positional iterable operands."),
        new(AbstractValueKind.SetType, "symmetric_difference", 1, 1, "LA3139", "set.symmetric_difference(other) expects one positional iterable operand."),
        new(AbstractValueKind.SetType, "isdisjoint", 1, 1, "LA3139", "set.isdisjoint(other) expects one positional iterable operand."),
        new(AbstractValueKind.SetType, "issubset", 1, 1, "LA3139", "set.issubset(other) expects one positional iterable operand."),
        new(AbstractValueKind.SetType, "issuperset", 1, 1, "LA3139", "set.issuperset(other) expects one positional iterable operand."),
        new(AbstractValueKind.SetType, "update", 0, ArgumentCountLimit.Unbounded, "LA3139", "set.update(*others) expects positional iterable operands.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.SetType, "intersection_update", 0, ArgumentCountLimit.Unbounded, "LA3139", "set.intersection_update(*others) expects positional iterable operands.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.SetType, "difference_update", 0, ArgumentCountLimit.Unbounded, "LA3139", "set.difference_update(*others) expects positional iterable operands.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.SetType, "symmetric_difference_update", 1, 1, "LA3139", "set.symmetric_difference_update(other) expects one positional iterable operand.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.RegexPattern, "search", 1, 3, "LA3152", "pattern.search(string[, pos[, endpos]]) expects one to three arguments.", parameterNames: ["string", "pos", "endpos"]),
        new(AbstractValueKind.RegexPattern, "match", 1, 3, "LA3152", "pattern.match(string[, pos[, endpos]]) expects one to three arguments.", parameterNames: ["string", "pos", "endpos"]),
        new(AbstractValueKind.RegexPattern, "fullmatch", 1, 3, "LA3152", "pattern.fullmatch(string[, pos[, endpos]]) expects one to three arguments.", parameterNames: ["string", "pos", "endpos"]),
        new(AbstractValueKind.RegexPattern, "findall", 1, 3, "LA3152", "pattern.findall(string[, pos[, endpos]]) expects one to three arguments.", parameterNames: ["string", "pos", "endpos"]),
        new(AbstractValueKind.RegexPattern, "finditer", 1, 3, "LA3152", "pattern.finditer(string[, pos[, endpos]]) expects one to three arguments.", parameterNames: ["string", "pos", "endpos"]),
        new(AbstractValueKind.RegexPattern, "sub", 2, 5, "LA3152", "pattern.sub(repl, string[, count[, pos[, endpos]]]) expects two to five arguments.", parameterNames: ["repl", "string", "count", "pos", "endpos"]),
        new(AbstractValueKind.RegexPattern, "subn", 2, 5, "LA3152", "pattern.subn(repl, string[, count[, pos[, endpos]]]) expects two to five arguments.", parameterNames: ["repl", "string", "count", "pos", "endpos"]),
        new(AbstractValueKind.RegexPattern, "split", 1, 4, "LA3152", "pattern.split(string[, maxsplit[, pos[, endpos]]]) expects one to four arguments.", parameterNames: ["string", "maxsplit", "pos", "endpos"]),
        new(AbstractValueKind.RegexMatch, "group", 0, ArgumentCountLimit.Unbounded, "LA3152", "match.group([index...]) expects zero or more positional group identifiers."),
        new(AbstractValueKind.RegexMatch, "groups", 0, 1, "LA3152", "match.groups(default=None) expects zero or one argument.", parameterNames: ["default"]),
        new(AbstractValueKind.RegexMatch, "groupdict", 0, 1, "LA3152", "match.groupdict(default=None) expects zero or one argument.", parameterNames: ["default"]),
        new(AbstractValueKind.RegexMatch, "expand", 1, 1, "LA3152", "match.expand(template) expects one string argument.", parameterNames: ["template"]),
        new(AbstractValueKind.RegexMatch, "start", 0, 1, "LA3152", "match.start(group=0) expects zero or one group identifier.", parameterNames: ["group"]),
        new(AbstractValueKind.RegexMatch, "end", 0, 1, "LA3152", "match.end(group=0) expects zero or one group identifier.", parameterNames: ["group"]),
        new(AbstractValueKind.RegexMatch, "span", 0, 1, "LA3152", "match.span(group=0) expects zero or one group identifier.", parameterNames: ["group"]),
        new(AbstractValueKind.ArgparseParser, "add_mutually_exclusive_group", 0, 1, "LA3153", "argparse.ArgumentParser.add_mutually_exclusive_group([required]) expects zero or one argument.", parameterNames: ["required"]),
        new(AbstractValueKind.ArgparseParser, "parse_args", 0, 2, "LA3154", "argparse.ArgumentParser.parse_args([args][, namespace]) expects zero to two arguments.", parameterNames: ["args", "namespace"]),
        new(AbstractValueKind.ArgparseParser, "parse_known_args", 0, 2, "LA3154", "argparse.ArgumentParser.parse_known_args([args][, namespace]) expects zero to two arguments.", parameterNames: ["args", "namespace"]),
        new(AbstractValueKind.ArgparseParser, "format_usage", 0, 0, "LA3154", "argparse.ArgumentParser.format_usage() expects no arguments."),
        new(AbstractValueKind.ArgparseParser, "format_help", 0, 0, "LA3154", "argparse.ArgumentParser.format_help() expects no arguments."),
        new(AbstractValueKind.ArgparseParser, "print_usage", 0, 1, "LA3154", "argparse.ArgumentParser.print_usage([file]) expects zero or one argument.", parameterNames: ["file"]),
        new(AbstractValueKind.ArgparseParser, "print_help", 0, 1, "LA3154", "argparse.ArgumentParser.print_help([file]) expects zero or one argument.", parameterNames: ["file"]),
        new(AbstractValueKind.ArgparseParser, "error", 1, 1, "LA3154", "argparse.ArgumentParser.error(message) expects one argument.", parameterNames: ["message"]),
        new(AbstractValueKind.ArgparseParser, "exit", 0, 2, "LA3154", "argparse.ArgumentParser.exit([status][, message]) expects zero to two arguments.", parameterNames: ["status", "message"]),
        new(AbstractValueKind.ArgparseParser, "get_default", 1, 1, "LA3154", "argparse.ArgumentParser.get_default(dest) expects one argument.", parameterNames: ["dest"]),
        new(AbstractValueKind.ArgparseParser, "add_subparsers", 0, ArgumentCountLimit.Unbounded, "LA3154", "argparse.ArgumentParser.add_subparsers(...) is not supported by Lython."),
        new(AbstractValueKind.CsvWriter, "writerow", 1, 1, "LA3155", "csv.writerow(row) expects one argument.", parameterNames: ["row"]),
        new(AbstractValueKind.CsvWriter, "writerows", 1, 1, "LA3155", "csv.writerows(rows) expects one argument.", parameterNames: ["rows"]),
        new(AbstractValueKind.CsvWriter, "getvalue", 0, 0, "LA3155", "csv.getvalue() expects no arguments."),
        new(AbstractValueKind.CsvDictWriter, "writeheader", 0, 0, "LA3155", "csv.DictWriter.writeheader() expects no arguments."),
        new(AbstractValueKind.CsvDictWriter, "writerow", 1, 1, "LA3155", "csv.DictWriter.writerow(rowdict) expects one argument.", parameterNames: ["rowdict"]),
        new(AbstractValueKind.CsvDictWriter, "writerows", 1, 1, "LA3155", "csv.DictWriter.writerows(rowdicts) expects one argument.", parameterNames: ["rowdicts"]),
        new(AbstractValueKind.Decimal, "quantize", 1, 3, "LA3156", "Decimal.quantize(exp[, rounding][, context]) expects one to three arguments.", parameterNames: ["exp", "rounding", "context"]),
        new(AbstractValueKind.Decimal, "normalize", 0, 1, "LA3156", "Decimal.normalize([context]) expects zero or one argument.", parameterNames: ["context"]),
        new(AbstractValueKind.Decimal, "sqrt", 0, 1, "LA3156", "Decimal.sqrt([context]) expects zero or one argument.", parameterNames: ["context"]),
        new(AbstractValueKind.Decimal, "exp", 0, 1, "LA3156", "Decimal.exp([context]) expects zero or one argument.", parameterNames: ["context"]),
        new(AbstractValueKind.Decimal, "ln", 0, 1, "LA3156", "Decimal.ln([context]) expects zero or one argument.", parameterNames: ["context"]),
        new(AbstractValueKind.Decimal, "log10", 0, 1, "LA3156", "Decimal.log10([context]) expects zero or one argument.", parameterNames: ["context"]),
        new(AbstractValueKind.Decimal, "copy_abs", 0, 1, "LA3156", "Decimal.copy_abs([context]) expects zero or one argument.", parameterNames: ["context"]),
        new(AbstractValueKind.Decimal, "copy_negate", 0, 1, "LA3156", "Decimal.copy_negate([context]) expects zero or one argument.", parameterNames: ["context"]),
        new(AbstractValueKind.Decimal, "copy_sign", 1, 1, "LA3156", "Decimal.copy_sign(other) expects one argument.", parameterNames: ["other"]),
        new(AbstractValueKind.Decimal, "to_integral_value", 0, 2, "LA3156", "Decimal.to_integral_value([rounding][, context]) expects zero to two arguments.", parameterNames: ["rounding", "context"]),
        new(AbstractValueKind.Decimal, "to_integral_exact", 0, 2, "LA3156", "Decimal.to_integral_exact([rounding][, context]) expects zero to two arguments.", parameterNames: ["rounding", "context"]),
        new(AbstractValueKind.Decimal, "to_integral", 0, 2, "LA3156", "Decimal.to_integral([rounding][, context]) expects zero to two arguments.", parameterNames: ["rounding", "context"]),
        new(AbstractValueKind.Decimal, "as_tuple", 0, 0, "LA3156", "Decimal.as_tuple() expects no arguments."),
        new(AbstractValueKind.Decimal, "adjusted", 0, 0, "LA3156", "Decimal.adjusted() expects no arguments."),
        new(AbstractValueKind.Decimal, "compare", 1, 2, "LA3156", "Decimal.compare(other[, context]) expects one or two arguments.", parameterNames: ["other", "context"]),
        new(AbstractValueKind.Decimal, "compare_total", 1, 1, "LA3156", "Decimal.compare_total(other) expects one argument.", parameterNames: ["other"]),
        new(AbstractValueKind.Decimal, "is_nan", 0, 0, "LA3156", "Decimal.is_nan() expects no arguments."),
        new(AbstractValueKind.Decimal, "is_infinite", 0, 0, "LA3156", "Decimal.is_infinite() expects no arguments."),
        new(AbstractValueKind.Decimal, "is_finite", 0, 0, "LA3156", "Decimal.is_finite() expects no arguments."),
        new(AbstractValueKind.Decimal, "is_zero", 0, 0, "LA3156", "Decimal.is_zero() expects no arguments."),
        new(AbstractValueKind.Decimal, "is_signed", 0, 0, "LA3156", "Decimal.is_signed() expects no arguments."),
        new(AbstractValueKind.Decimal, "to_eng_string", 0, 0, "LA3156", "Decimal.to_eng_string() expects no arguments."),
        new(AbstractValueKind.Decimal, "scaleb", 1, 2, "LA3156", "Decimal.scaleb(other[, context]) expects one or two arguments.", parameterNames: ["other", "context"]),
        new(AbstractValueKind.Decimal, "shift", 1, 1, "LA3156", "Decimal.shift(other) expects one argument.", parameterNames: ["other"]),
        new(AbstractValueKind.Decimal, "rotate", 1, 1, "LA3156", "Decimal.rotate(other) expects one argument.", parameterNames: ["other"]),
        new(AbstractValueKind.Decimal, "same_quantum", 1, 1, "LA3156", "Decimal.same_quantum(other) expects one argument.", parameterNames: ["other"]),
        new(AbstractValueKind.Decimal, "remainder_near", 1, 2, "LA3156", "Decimal.remainder_near(other[, context]) expects one or two arguments.", parameterNames: ["other", "context"]),
        new(AbstractValueKind.Decimal, "min", 1, 2, "LA3156", "Decimal.min(other[, context]) expects one or two arguments.", parameterNames: ["other", "context"]),
        new(AbstractValueKind.Decimal, "max", 1, 2, "LA3156", "Decimal.max(other[, context]) expects one or two arguments.", parameterNames: ["other", "context"]),
        new(AbstractValueKind.Decimal, "min_mag", 1, 2, "LA3156", "Decimal.min_mag(other[, context]) expects one or two arguments.", parameterNames: ["other", "context"]),
        new(AbstractValueKind.Decimal, "max_mag", 1, 2, "LA3156", "Decimal.max_mag(other[, context]) expects one or two arguments.", parameterNames: ["other", "context"]),
        new(AbstractValueKind.DecimalContext, "copy", 0, 0, "LA3156", "Context.copy() expects no arguments."),
        new(AbstractValueKind.DecimalContext, "clear_flags", 0, 0, "LA3156", "Context.clear_flags() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.DecimalContext, "create_decimal", 1, 1, "LA3156", "Context.create_decimal(value) expects one argument.", parameterNames: ["value"]),
        new(AbstractValueKind.DecimalContext, "create_decimal_from_float", 1, 1, "LA3156", "Context.create_decimal_from_float(f) expects one argument.", parameterNames: ["f"]),
        ];
    }
}
