using Lokad.Lython.Runtime;

namespace Lokad.Lython.Frontend;

internal static partial class StaticContracts
{
    private static class CoreCallableContractCatalog
    {
        public static readonly StaticCallableContract[] Contracts =
        [
        new(AbstractValueKind.Path, "__fspath__", 0, 0, "LA3114", "Path.__fspath__() expects no arguments."),
        new(AbstractValueKind.Path, "is_absolute", 0, 0, "LA3114", "Path.is_absolute() expects no arguments."),
        new(AbstractValueKind.Path, "is_mount", 0, 0, "LA3114", "Path.is_mount() expects no arguments."),
        new(AbstractValueKind.Path, "is_reserved", 0, 0, "LA3114", "Path.is_reserved() expects no arguments."),
        new(AbstractValueKind.Path, "as_posix", 0, 0, "LA3114", "Path.as_posix() expects no arguments."),
        new(AbstractValueKind.Path, "resolve", 0, 0, "LA3114", "Path.resolve() expects no arguments."),
        new(AbstractValueKind.Path, "expanduser", 0, 0, "LA3114", "Path.expanduser() expects no arguments."),
        new(AbstractValueKind.Path, "exists", 0, 0, "LA3114", "Path.exists() expects no arguments."),
        new(AbstractValueKind.Path, "is_file", 0, 0, "LA3114", "Path.is_file() expects no arguments."),
        new(AbstractValueKind.Path, "is_dir", 0, 0, "LA3114", "Path.is_dir() expects no arguments."),
        new(AbstractValueKind.Path, "is_symlink", 0, 0, "LA3114", "Path.is_symlink() expects no arguments."),
        new(AbstractValueKind.Path, "stat", 0, 0, "LA3114", "Path.stat() expects no arguments."),
        new(AbstractValueKind.Path, "lstat", 0, 0, "LA3114", "Path.lstat() expects no arguments."),
        new(AbstractValueKind.Path, "iterdir", 0, 0, "LA3114", "Path.iterdir() expects no arguments."),
        new(AbstractValueKind.Path, "absolute", 0, 0, "LA3114", "Path.absolute() expects no arguments."),
        new(AbstractValueKind.Path, "unlink", 0, 1, "LA3114", "Path.unlink([missing_ok]) expects zero or one argument.", parameterNames: ["missing_ok"]),
        new(AbstractValueKind.Path, "rmdir", 0, 0, "LA3114", "Path.rmdir() expects no arguments."),
        new(AbstractValueKind.Path, "touch", 0, 2, "LA3114", "Path.touch([mode][, exist_ok]) expects zero to two arguments.", parameterNames: ["mode", "exist_ok"]),
        new(AbstractValueKind.Path, "mkdir", 0, 3, "LA3114", "Path.mkdir([mode][, parents][, exist_ok]) expects zero to three arguments.", parameterNames: ["mode", "parents", "exist_ok"]),
        new(AbstractValueKind.Path, "read_text", 0, 3, "LA3114", "Path.read_text([encoding][, errors][, newline]) expects zero to three arguments.", parameterNames: ["encoding", "errors", "newline"]),
        new(AbstractValueKind.Path, "open", 0, 5, "LA3114", "Path.open([mode][, buffering][, encoding][, errors][, newline]) expects zero to five arguments.", parameterNames: ["mode", "buffering", "encoding", "errors", "newline"]),
        new(AbstractValueKind.Path, "write_text", 1, 4, "LA3114", "Path.write_text(text[, encoding][, errors][, newline]) expects one to four arguments.", parameterNames: ["text", "encoding", "errors", "newline"]),
        new(AbstractValueKind.Path, "match", 1, 1, "LA3114", "Path.match(pattern) expects one argument.", parameterNames: ["pattern"]),
        new(AbstractValueKind.Path, "relative_to", 1, 1, "LA3114", "Path.relative_to(other) expects one argument.", parameterNames: ["other"]),
        new(AbstractValueKind.Path, "with_suffix", 1, 1, "LA3114", "Path.with_suffix(suffix) expects one argument.", parameterNames: ["suffix"]),
        new(AbstractValueKind.Path, "with_name", 1, 1, "LA3114", "Path.with_name(name) expects one argument.", parameterNames: ["name"]),
        new(AbstractValueKind.Path, "with_stem", 1, 1, "LA3114", "Path.with_stem(stem) expects one argument.", parameterNames: ["stem"]),
        new(AbstractValueKind.Path, "is_relative_to", 1, 1, "LA3114", "Path.is_relative_to(other) expects one argument.", parameterNames: ["other"]),
        new(AbstractValueKind.Path, "samefile", 1, 1, "LA3114", "Path.samefile(other_path) expects one argument.", parameterNames: ["other_path"]),
        new(AbstractValueKind.Path, "rename", 1, 1, "LA3114", "Path.rename(target) expects one argument.", parameterNames: ["target"]),
        new(AbstractValueKind.Path, "replace", 1, 1, "LA3114", "Path.replace(target) expects one argument.", parameterNames: ["target"]),
        new(AbstractValueKind.Path, "glob", 1, 3, "LA3114", "Path.glob(pattern[, case_sensitive][, recurse_symlinks]) expects one to three arguments.", parameterNames: ["pattern", "case_sensitive", "recurse_symlinks"]),
        new(AbstractValueKind.Path, "rglob", 1, 3, "LA3114", "Path.rglob(pattern[, case_sensitive][, recurse_symlinks]) expects one to three arguments.", parameterNames: ["pattern", "case_sensitive", "recurse_symlinks"]),
        new(AbstractValueKind.Path, "joinpath", 1, ArgumentCountLimit.Unbounded, "LA3114", "Path.joinpath(*other) expects at least one argument."),
        new(AbstractValueKind.Path, "read_bytes", 0, 0, "LA3114", "Path.read_bytes() expects no arguments."),
        new(AbstractValueKind.Path, "write_bytes", 1, 1, "LA3114", "Path.write_bytes(data) expects one argument.", parameterNames: ["data"]),
        new(AbstractValueKind.Path, "readlink", 0, 0, "LA3114", "Path.readlink() expects no arguments."),
        new(AbstractValueKind.Path, "symlink_to", 1, 2, "LA3114", "Path.symlink_to(target[, target_is_directory]) expects one or two arguments.", parameterNames: ["target", "target_is_directory"]),
        new(AbstractValueKind.Path, "hardlink_to", 1, 1, "LA3114", "Path.hardlink_to(target) expects one argument.", parameterNames: ["target"]),
        new(AbstractValueKind.Path, "chmod", 1, 1, "LA3114", "Path.chmod(mode) expects one argument.", parameterNames: ["mode"]),
        new(AbstractValueKind.Path, "owner", 0, 0, "LA3114", "Path.owner() expects no arguments."),
        new(AbstractValueKind.Path, "group", 0, 0, "LA3114", "Path.group() expects no arguments."),
        new(AbstractValueKind.TextFileHandle, "close", 0, 0, "LA3108", "file.close() expects no arguments."),
        new(AbstractValueKind.TextFileHandle, "readable", 0, 0, "LA3108", "file.readable() expects no arguments."),
        new(AbstractValueKind.TextFileHandle, "writable", 0, 0, "LA3108", "file.writable() expects no arguments."),
        new(AbstractValueKind.TextFileHandle, "seekable", 0, 0, "LA3108", "file.seekable() expects no arguments."),
        new(AbstractValueKind.TextFileHandle, "tell", 0, 0, "LA3108", "file.tell() expects no arguments."),
        new(AbstractValueKind.TextFileHandle, "seek", 1, 2, "LA3108", "file.seek(offset[, whence]) expects one or two arguments.", parameterNames: ["offset", "whence"]),
        new(AbstractValueKind.TextFileHandle, "read", 0, 1, "LA3108", "file.read([size]) expects zero or one argument.", parameterNames: ["size"]),
        new(AbstractValueKind.TextFileHandle, "readline", 0, 1, "LA3108", "file.readline([size]) expects zero or one argument.", parameterNames: ["size"]),
        new(AbstractValueKind.TextFileHandle, "readlines", 0, 1, "LA3108", "file.readlines([hint]) expects zero or one argument.", parameterNames: ["hint"]),
        new(AbstractValueKind.TextFileHandle, "write", 1, 1, "LA3111", "file.write(text) expects one string argument.", parameterNames: ["text"]),
        new(AbstractValueKind.TextFileHandle, "writelines", 1, 1, "LA3112", "file.writelines(lines) expects one iterable of strings argument.", parameterNames: ["lines"]),
        new(AbstractValueKind.TextFileHandle, "flush", 0, 0, "LA3108", "file.flush() expects no arguments."),
        new(AbstractValueKind.CollectionsDefaultDict, "get", 1, 2, "LA3114", "defaultdict.get(key[, default]) expects one or two arguments.", parameterNames: ["key", "default"]),
        new(AbstractValueKind.CollectionsDefaultDict, "keys", 0, 0, "LA3114", "defaultdict.keys() expects no arguments."),
        new(AbstractValueKind.CollectionsDefaultDict, "values", 0, 0, "LA3114", "defaultdict.values() expects no arguments."),
        new(AbstractValueKind.CollectionsDefaultDict, "items", 0, 0, "LA3114", "defaultdict.items() expects no arguments."),
        new(AbstractValueKind.CollectionsDefaultDict, "setdefault", 1, 2, "LA3114", "defaultdict.setdefault(key[, default]) expects one or two arguments.", parameterNames: ["key", "default"]),
        new(AbstractValueKind.CollectionsDefaultDict, "copy", 0, 0, "LA3114", "defaultdict.copy() expects no arguments."),
        new(AbstractValueKind.CollectionsDefaultDict, "clear", 0, 0, "LA3114", "defaultdict.clear() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.CollectionsDefaultDict, "update", 1, 1, "LA3114", "defaultdict.update(mapping) expects one dictionary argument.", StaticMutationKind.MutatesReceiver, ["mapping"]),
        new(AbstractValueKind.CollectionsDefaultDict, "pop", 1, 2, "LA3114", "defaultdict.pop(key[, default]) expects one key and an optional default.", StaticMutationKind.MutatesReceiver, ["key", "default"]),
        new(AbstractValueKind.CollectionsDefaultDict, "popitem", 0, 0, "LA3114", "defaultdict.popitem() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.CollectionsCounter, "get", 1, 2, "LA3114", "Counter.get(key[, default]) expects one or two arguments.", parameterNames: ["key", "default"]),
        new(AbstractValueKind.CollectionsCounter, "update", 0, ArgumentCountLimit.Unbounded, "LA3114", "Counter.update([iterable], **kwargs) expects supported arguments.", StaticMutationKind.MutatesReceiver, ["iterable"], allowsExtraKeywords: true),
        new(AbstractValueKind.CollectionsCounter, "subtract", 0, ArgumentCountLimit.Unbounded, "LA3114", "Counter.subtract([iterable], **kwargs) expects supported arguments.", StaticMutationKind.MutatesReceiver, ["iterable"], allowsExtraKeywords: true),
        new(AbstractValueKind.CollectionsCounter, "total", 0, 0, "LA3114", "Counter.total() expects no arguments."),
        new(AbstractValueKind.CollectionsCounter, "most_common", 0, 1, "LA3114", "Counter.most_common([n]) expects zero or one argument.", parameterNames: ["n"]),
        new(AbstractValueKind.CollectionsCounter, "elements", 0, 0, "LA3114", "Counter.elements() expects no arguments."),
        new(AbstractValueKind.CollectionsCounter, "copy", 0, 0, "LA3114", "Counter.copy() expects no arguments."),
        new(AbstractValueKind.CollectionsCounter, "clear", 0, 0, "LA3114", "Counter.clear() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.CollectionsCounter, "keys", 0, 0, "LA3114", "Counter.keys() expects no arguments."),
        new(AbstractValueKind.CollectionsCounter, "values", 0, 0, "LA3114", "Counter.values() expects no arguments."),
        new(AbstractValueKind.CollectionsCounter, "items", 0, 0, "LA3114", "Counter.items() expects no arguments."),
        new(AbstractValueKind.CollectionsDeque, "append", 1, 1, "LA3114", "deque.append(value) expects one argument.", StaticMutationKind.MutatesReceiver, ["value"]),
        new(AbstractValueKind.CollectionsDeque, "appendleft", 1, 1, "LA3114", "deque.appendleft(value) expects one argument.", StaticMutationKind.MutatesReceiver, ["value"]),
        new(AbstractValueKind.CollectionsDeque, "pop", 0, 0, "LA3114", "deque.pop() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.CollectionsDeque, "popleft", 0, 0, "LA3114", "deque.popleft() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.CollectionsDeque, "extend", 1, 1, "LA3114", "deque.extend(iterable) expects one argument.", StaticMutationKind.MutatesReceiver, ["iterable"]),
        new(AbstractValueKind.CollectionsDeque, "extendleft", 1, 1, "LA3114", "deque.extendleft(iterable) expects one argument.", StaticMutationKind.MutatesReceiver, ["iterable"]),
        new(AbstractValueKind.CollectionsDeque, "clear", 0, 0, "LA3114", "deque.clear() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.CollectionsDeque, "copy", 0, 0, "LA3114", "deque.copy() expects no arguments."),
        new(AbstractValueKind.CollectionsDeque, "count", 1, 1, "LA3114", "deque.count(value) expects one argument.", parameterNames: ["value"]),
        new(AbstractValueKind.CollectionsDeque, "index", 1, 3, "LA3114", "deque.index(value[, start[, stop]]) expects one to three arguments.", parameterNames: ["value", "start", "stop"]),
        new(AbstractValueKind.CollectionsDeque, "insert", 2, 2, "LA3114", "deque.insert(index, value) expects two arguments.", StaticMutationKind.MutatesReceiver, ["index", "value"]),
        new(AbstractValueKind.CollectionsDeque, "remove", 1, 1, "LA3114", "deque.remove(value) expects one argument.", StaticMutationKind.MutatesReceiver, ["value"]),
        new(AbstractValueKind.CollectionsDeque, "reverse", 0, 0, "LA3114", "deque.reverse() expects no arguments.", StaticMutationKind.MutatesReceiver),
        new(AbstractValueKind.CollectionsDeque, "rotate", 0, 1, "LA3114", "deque.rotate([n]) expects zero or one argument.", StaticMutationKind.MutatesReceiver, ["n"]),
        new(AbstractValueKind.CollectionsChainMap, "get", 1, 2, "LA3114", "ChainMap.get(key[, default]) expects one or two arguments.", parameterNames: ["key", "default"]),
        new(AbstractValueKind.CollectionsChainMap, "keys", 0, 0, "LA3114", "ChainMap.keys() expects no arguments."),
        new(AbstractValueKind.CollectionsChainMap, "values", 0, 0, "LA3114", "ChainMap.values() expects no arguments."),
        new(AbstractValueKind.CollectionsChainMap, "items", 0, 0, "LA3114", "ChainMap.items() expects no arguments."),
        new(AbstractValueKind.CollectionsChainMap, "new_child", 0, 1, "LA3114", "ChainMap.new_child([m]) expects zero or one argument.", parameterNames: ["m"]),
        new(AbstractValueKind.CollectionsChainMap, "copy", 0, 0, "LA3114", "ChainMap.copy() expects no arguments."),
        ];
    }
}
