using Lokad.Lython.Runtime;

namespace Lokad.Lython.Frontend;

internal static partial class StaticContracts
{
    private static readonly StaticMemberValueContract[] MemberValueContracts =
    [
        new(AbstractValueKind.Path, "name", StaticReturnShape.String),
        new(AbstractValueKind.Path, "suffix", StaticReturnShape.String),
        new(AbstractValueKind.Path, "suffixes", StaticReturnShape.ListOfString),
        new(AbstractValueKind.Path, "stem", StaticReturnShape.String),
        new(AbstractValueKind.Path, "parent", StaticReturnShape.Path),
        new(AbstractValueKind.Path, "drive", StaticReturnShape.String),
        new(AbstractValueKind.Path, "root", StaticReturnShape.String),
        new(AbstractValueKind.Path, "anchor", StaticReturnShape.String),
        new(AbstractValueKind.TextFileHandle, "closed", StaticReturnShape.Boolean),
        new(AbstractValueKind.CollectionsDefaultDict, "default_factory", StaticReturnShape.Unknown),
        new(AbstractValueKind.CollectionsDeque, "maxlen", StaticReturnShape.Unknown),
        new(AbstractValueKind.CollectionsChainMap, "maps", StaticReturnShape.ListOfUnknown),
        new(AbstractValueKind.CollectionsChainMap, "parents", StaticReturnShape.CollectionsChainMap),
        new(AbstractValueKind.DecimalContext, "prec", StaticReturnShape.Integer),
        new(AbstractValueKind.DecimalContext, "rounding", StaticReturnShape.String),
        new(AbstractValueKind.DecimalContext, "Emin", StaticReturnShape.Integer),
        new(AbstractValueKind.DecimalContext, "Emax", StaticReturnShape.Integer),
        new(AbstractValueKind.DecimalContext, "capitals", StaticReturnShape.Integer),
        new(AbstractValueKind.DecimalContext, "clamp", StaticReturnShape.Integer),
        new(AbstractValueKind.DecimalContext, "flags", StaticReturnShape.Dict),
        new(AbstractValueKind.DecimalContext, "traps", StaticReturnShape.Dict),
        new(AbstractValueKind.DecimalTuple, "sign", StaticReturnShape.Integer),
        new(AbstractValueKind.DecimalTuple, "digits", StaticReturnShape.Unknown),
        new(AbstractValueKind.DecimalTuple, "exponent", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeTimedelta, "days", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeTimedelta, "seconds", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeTimedelta, "microseconds", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeDate, "year", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeDate, "month", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeDate, "day", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeTime, "hour", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeTime, "minute", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeTime, "second", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeTime, "microsecond", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeTime, "tzinfo", StaticReturnShape.Unknown),
        new(AbstractValueKind.DateTimeTime, "fold", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeDateTime, "year", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeDateTime, "month", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeDateTime, "day", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeDateTime, "hour", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeDateTime, "minute", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeDateTime, "second", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeDateTime, "microsecond", StaticReturnShape.Integer),
        new(AbstractValueKind.DateTimeDateTime, "tzinfo", StaticReturnShape.Unknown),
        new(AbstractValueKind.DateTimeDateTime, "fold", StaticReturnShape.Integer),
        new(AbstractValueKind.StatisticsLinearRegression, "slope", StaticReturnShape.Float),
        new(AbstractValueKind.StatisticsLinearRegression, "intercept", StaticReturnShape.Float),
        new(AbstractValueKind.StatisticsLinearRegression, "_fields", StaticReturnShape.ListOfString),
        new(AbstractValueKind.StatisticsNormalDist, "mean", StaticReturnShape.Float),
        new(AbstractValueKind.StatisticsNormalDist, "median", StaticReturnShape.Float),
        new(AbstractValueKind.StatisticsNormalDist, "mode", StaticReturnShape.Float),
        new(AbstractValueKind.StatisticsNormalDist, "stdev", StaticReturnShape.Float),
        new(AbstractValueKind.StatisticsNormalDist, "variance", StaticReturnShape.Float),
        new(AbstractValueKind.SubprocessCompletedProcess, "args", StaticReturnShape.ListOfString),
        new(AbstractValueKind.SubprocessCompletedProcess, "returncode", StaticReturnShape.Integer),
        new(AbstractValueKind.SubprocessCompletedProcess, "stdout", StaticReturnShape.String),
        new(AbstractValueKind.SubprocessCompletedProcess, "stderr", StaticReturnShape.String),
        new(AbstractValueKind.DifflibDiffer, "linejunk", StaticReturnShape.Unknown),
        new(AbstractValueKind.DifflibDiffer, "charjunk", StaticReturnShape.Unknown),
        new(AbstractValueKind.DifflibMatch, "a", StaticReturnShape.Integer),
        new(AbstractValueKind.DifflibMatch, "b", StaticReturnShape.Integer),
        new(AbstractValueKind.DifflibMatch, "size", StaticReturnShape.Integer),
        new(AbstractValueKind.DifflibSequenceMatcher, "a", StaticReturnShape.Unknown),
        new(AbstractValueKind.DifflibSequenceMatcher, "b", StaticReturnShape.Unknown),
        new(AbstractValueKind.DifflibSequenceMatcher, "b2j", StaticReturnShape.Unknown),
        new(AbstractValueKind.DifflibSequenceMatcher, "bjunk", StaticReturnShape.Unknown),
        new(AbstractValueKind.DifflibSequenceMatcher, "bpopular", StaticReturnShape.Unknown),
        new(AbstractValueKind.PkgutilModuleInfo, "module_finder", StaticReturnShape.Unknown),
        new(AbstractValueKind.PkgutilModuleInfo, "name", StaticReturnShape.String),
        new(AbstractValueKind.PkgutilModuleInfo, "ispkg", StaticReturnShape.Boolean),
        new(AbstractValueKind.PkgutilModuleInfo, "_fields", StaticReturnShape.ListOfString),
        new(AbstractValueKind.PkgutilLoader, "name", StaticReturnShape.String),
        new(AbstractValueKind.PkgutilLoader, "fullname", StaticReturnShape.String),
        new(AbstractValueKind.PkgutilLoader, "ispkg", StaticReturnShape.Boolean),
        new(AbstractValueKind.DataclassField, "name", StaticReturnShape.String),
        new(AbstractValueKind.DataclassField, "type", StaticReturnShape.Unknown),
        new(AbstractValueKind.DataclassField, "default", StaticReturnShape.Unknown),
        new(AbstractValueKind.DataclassField, "default_factory", StaticReturnShape.Unknown),
        new(AbstractValueKind.DataclassField, "init", StaticReturnShape.Boolean),
        new(AbstractValueKind.DataclassField, "repr", StaticReturnShape.Boolean),
        new(AbstractValueKind.DataclassField, "hash", StaticReturnShape.Unknown),
        new(AbstractValueKind.DataclassField, "compare", StaticReturnShape.Boolean),
        new(AbstractValueKind.DataclassField, "metadata", StaticReturnShape.Unknown),
        new(AbstractValueKind.DataclassField, "kw_only", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlWorkbook, "active", StaticReturnShape.OpenPyxlWorksheet),
        new(AbstractValueKind.OpenPyxlWorkbook, "worksheets", StaticReturnShape.ListOfUnknown),
        new(AbstractValueKind.OpenPyxlWorkbook, "sheetnames", StaticReturnShape.ListOfString),
        new(AbstractValueKind.OpenPyxlWorkbook, "read_only", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlWorkbook, "write_only", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlWorkbook, "iso_dates", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlWorkbook, "template", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlWorkbook, "mime_type", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbook, "epoch", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbook, "excel_base_date", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbook, "named_styles", StaticReturnShape.ListOfOpenPyxlNamedStyle),
        new(AbstractValueKind.OpenPyxlWorkbook, "style_names", StaticReturnShape.ListOfString),
        new(AbstractValueKind.OpenPyxlWorkbook, "security", StaticReturnShape.OpenPyxlWorkbookProtection),
        new(AbstractValueKind.OpenPyxlWorksheet, "title", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorksheet, "min_row", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlWorksheet, "max_row", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlWorksheet, "min_column", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlWorksheet, "max_column", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlWorksheet, "dimensions", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorksheet, "show_gridlines", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlWorksheet, "sheet_view", StaticReturnShape.OpenPyxlSheetView),
        new(AbstractValueKind.OpenPyxlWorksheet, "page_margins", StaticReturnShape.OpenPyxlPageMargins),
        new(AbstractValueKind.OpenPyxlWorksheet, "page_setup", StaticReturnShape.OpenPyxlPageSetup),
        new(AbstractValueKind.OpenPyxlWorksheet, "protection", StaticReturnShape.OpenPyxlSheetProtection),
        new(AbstractValueKind.OpenPyxlWorksheet, "auto_filter", StaticReturnShape.OpenPyxlAutoFilter),
        new(AbstractValueKind.OpenPyxlWorksheet, "tables", StaticReturnShape.OpenPyxlTableCollection),
        new(AbstractValueKind.OpenPyxlWorksheet, "data_validations", StaticReturnShape.OpenPyxlDataValidationList),
        new(AbstractValueKind.OpenPyxlWorksheet, "conditional_formatting", StaticReturnShape.OpenPyxlConditionalFormattingCollection),
        new(AbstractValueKind.OpenPyxlWorksheet, "_charts", StaticReturnShape.ListOfUnknown),
        new(AbstractValueKind.OpenPyxlWorksheet, "_images", StaticReturnShape.ListOfUnknown),
        new(AbstractValueKind.OpenPyxlWorksheet, "_drawings", StaticReturnShape.ListOfUnknown),
        new(AbstractValueKind.OpenPyxlWorksheet, "drawings", StaticReturnShape.ListOfUnknown),
        new(AbstractValueKind.OpenPyxlWorksheet, "_drawing", StaticReturnShape.OpenPyxlDrawing),
        new(AbstractValueKind.OpenPyxlWorksheet, "merged_cells", StaticReturnShape.OpenPyxlMergedCellSet),
        new(AbstractValueKind.OpenPyxlWorksheet, "merged_cell_ranges", StaticReturnShape.ListOfString),
        new(AbstractValueKind.OpenPyxlCell, "row", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlCell, "column", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlCell, "col_idx", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlCell, "column_letter", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlCell, "coordinate", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlCell, "parent", StaticReturnShape.OpenPyxlWorksheet),
        new(AbstractValueKind.OpenPyxlCell, "is_date", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlCell, "base_date", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlCell, "number_format", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlCell, "font", StaticReturnShape.OpenPyxlFont),
        new(AbstractValueKind.OpenPyxlCell, "fill", StaticReturnShape.OpenPyxlPatternFill),
        new(AbstractValueKind.OpenPyxlCell, "border", StaticReturnShape.OpenPyxlBorder),
        new(AbstractValueKind.OpenPyxlCell, "alignment", StaticReturnShape.OpenPyxlAlignment),
        new(AbstractValueKind.OpenPyxlCell, "protection", StaticReturnShape.OpenPyxlProtection),
        new(AbstractValueKind.OpenPyxlCell, "style", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlCell, "style_id", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlCell, "data_type", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlHyperlink, "ref", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlHyperlink, "target", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlHyperlink, "display", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlComment, "text", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlComment, "author", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlComment, "width", StaticReturnShape.Float),
        new(AbstractValueKind.OpenPyxlComment, "height", StaticReturnShape.Float),
        new(AbstractValueKind.OpenPyxlFont, "name", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlFont, "sz", StaticReturnShape.Float),
        new(AbstractValueKind.OpenPyxlFont, "bold", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlFont, "italic", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlFont, "color", StaticReturnShape.OpenPyxlColor),
        new(AbstractValueKind.OpenPyxlFont, "underline", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlFont, "b", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlFont, "i", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlPatternFill, "fill_type", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlPatternFill, "start_color", StaticReturnShape.OpenPyxlColor),
        new(AbstractValueKind.OpenPyxlPatternFill, "end_color", StaticReturnShape.OpenPyxlColor),
        new(AbstractValueKind.OpenPyxlPatternFill, "fgColor", StaticReturnShape.OpenPyxlColor),
        new(AbstractValueKind.OpenPyxlPatternFill, "bgColor", StaticReturnShape.OpenPyxlColor),
        new(AbstractValueKind.OpenPyxlPatternFill, "patternType", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlBorder, "left", StaticReturnShape.OpenPyxlSide),
        new(AbstractValueKind.OpenPyxlBorder, "right", StaticReturnShape.OpenPyxlSide),
        new(AbstractValueKind.OpenPyxlBorder, "top", StaticReturnShape.OpenPyxlSide),
        new(AbstractValueKind.OpenPyxlBorder, "bottom", StaticReturnShape.OpenPyxlSide),
        new(AbstractValueKind.OpenPyxlSide, "style", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlSide, "color", StaticReturnShape.OpenPyxlColor),
        new(AbstractValueKind.OpenPyxlSide, "border_style", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlColor, "type", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlColor, "rgb", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlColor, "indexed", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlColor, "theme", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlColor, "tint", StaticReturnShape.Float),
        new(AbstractValueKind.OpenPyxlColor, "auto", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlColor, "index", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlColor, "value", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlAlignment, "horizontal", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlAlignment, "vertical", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlAlignment, "wrap_text", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlAlignment, "text_rotation", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlProtection, "locked", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlProtection, "hidden", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlNamedStyle, "name", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlNamedStyle, "number_format", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlNamedStyle, "font", StaticReturnShape.OpenPyxlFont),
        new(AbstractValueKind.OpenPyxlNamedStyle, "fill", StaticReturnShape.OpenPyxlPatternFill),
        new(AbstractValueKind.OpenPyxlNamedStyle, "border", StaticReturnShape.OpenPyxlBorder),
        new(AbstractValueKind.OpenPyxlNamedStyle, "alignment", StaticReturnShape.OpenPyxlAlignment),
        new(AbstractValueKind.OpenPyxlNamedStyle, "protection", StaticReturnShape.OpenPyxlProtection),
        new(AbstractValueKind.OpenPyxlTable, "displayName", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlTable, "name", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlTable, "ref", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlTable, "tableStyleInfo", StaticReturnShape.OpenPyxlTableStyleInfo),
        new(AbstractValueKind.OpenPyxlTableStyleInfo, "name", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlTableStyleInfo, "showFirstColumn", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlTableStyleInfo, "showLastColumn", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlTableStyleInfo, "showRowStripes", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlTableStyleInfo, "showColumnStripes", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlDataValidation, "type", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDataValidation, "formula1", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDataValidation, "formula2", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDataValidation, "allow_blank", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlDataValidation, "allowBlank", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlDataValidation, "showErrorMessage", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlDataValidation, "showInputMessage", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlDataValidation, "operator", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDataValidation, "errorTitle", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDataValidation, "error", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDataValidation, "promptTitle", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDataValidation, "prompt", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDataValidation, "sqref", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDataValidation, "ranges", StaticReturnShape.ListOfString),
        new(AbstractValueKind.OpenPyxlDataValidationList, "dataValidation", StaticReturnShape.ListOfUnknown),
        new(AbstractValueKind.OpenPyxlDataValidationList, "count", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlConditionalFormattingRule, "type", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlConditionalFormattingRule, "operator", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlConditionalFormattingRule, "priority", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlConditionalFormattingRule, "formula", StaticReturnShape.ListOfString),
        new(AbstractValueKind.OpenPyxlConditionalFormattingCollection, "ranges", StaticReturnShape.ListOfString),
        new(AbstractValueKind.OpenPyxlAutoFilter, "ref", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlSheetProtection, "sheet", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlSheetProtection, "objects", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlSheetProtection, "scenarios", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlSheetProtection, "password", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlSheetProtection, "algorithmName", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlSheetProtection, "hashValue", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlSheetProtection, "saltValue", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlSheetProtection, "spinCount", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "lockStructure", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "lockWindows", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "lockRevision", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "workbookPassword", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "workbookPasswordCharacterSet", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "revisionsPassword", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "revisionsPasswordCharacterSet", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "workbookAlgorithmName", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "workbookHashValue", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "workbookSaltValue", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "workbookSpinCount", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "revisionsAlgorithmName", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "revisionsHashValue", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "revisionsSaltValue", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlWorkbookProtection, "revisionsSpinCount", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlDrawing, "path", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDrawing, "_path", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDrawing, "package_path", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDrawing, "relationship_id", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlDrawing, "charts", StaticReturnShape.ListOfUnknown),
        new(AbstractValueKind.OpenPyxlDrawing, "_charts", StaticReturnShape.ListOfUnknown),
        new(AbstractValueKind.OpenPyxlDrawing, "images", StaticReturnShape.ListOfUnknown),
        new(AbstractValueKind.OpenPyxlDrawing, "_images", StaticReturnShape.ListOfUnknown),
        new(AbstractValueKind.OpenPyxlChart, "type", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlChart, "path", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlChart, "_path", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlChart, "package_path", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlChart, "relationship_id", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlChart, "drawing_path", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlChart, "anchor", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlChart, "width", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlChart, "height", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlChart, "title", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlChart, "style", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlChart, "x_axis", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlChart, "y_axis", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlChart, "series", StaticReturnShape.ListOfUnknown),
        new(AbstractValueKind.OpenPyxlChart, "categories", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlImage, "path", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlImage, "_path", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlImage, "package_path", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlImage, "relationship_id", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlImage, "drawing_path", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlImage, "ref", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlImage, "format", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlImage, "anchor", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlImage, "width", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlImage, "height", StaticReturnShape.Unknown),
        new(AbstractValueKind.OpenPyxlSheetView, "showGridLines", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlSheetView, "show_gridlines", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlSheetView, "tabSelected", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlSheetView, "workbookViewId", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlSelection, "activeCell", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlSelection, "sqref", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlPageMargins, "left", StaticReturnShape.Float),
        new(AbstractValueKind.OpenPyxlPageMargins, "right", StaticReturnShape.Float),
        new(AbstractValueKind.OpenPyxlPageMargins, "top", StaticReturnShape.Float),
        new(AbstractValueKind.OpenPyxlPageMargins, "bottom", StaticReturnShape.Float),
        new(AbstractValueKind.OpenPyxlPageMargins, "header", StaticReturnShape.Float),
        new(AbstractValueKind.OpenPyxlPageMargins, "footer", StaticReturnShape.Float),
        new(AbstractValueKind.OpenPyxlPageSetup, "orientation", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlPageSetup, "paperSize", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlPageSetup, "paper_size", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlPageSetup, "fitToWidth", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlPageSetup, "fit_to_width", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlPageSetup, "fitToHeight", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlPageSetup, "fit_to_height", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlPageSetup, "scale", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlColumnDimension, "index", StaticReturnShape.String),
        new(AbstractValueKind.OpenPyxlColumnDimension, "width", StaticReturnShape.Float),
        new(AbstractValueKind.OpenPyxlColumnDimension, "hidden", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlRowDimension, "index", StaticReturnShape.Integer),
        new(AbstractValueKind.OpenPyxlRowDimension, "height", StaticReturnShape.Float),
        new(AbstractValueKind.OpenPyxlRowDimension, "hidden", StaticReturnShape.Boolean),
        new(AbstractValueKind.OpenPyxlMergedCellSet, "ranges", StaticReturnShape.ListOfString),
    ];

    public static bool TryGetMemberValue(AbstractValue receiver, string memberName, LythonSourceSpan span, out AbstractValue value)
    {
        if (receiver.Kind == AbstractValueKind.ArgparseNamespace)
        {
            var summary = (AbstractArgparseNamespaceSummary)receiver.Value;
            if (summary.Members.TryGetValue(memberName, out value))
            {
                value = value.WithSpan(span);
                return true;
            }
        }

        if (receiver.Kind == AbstractValueKind.DataclassField &&
            string.Equals(memberName, "name", StringComparison.Ordinal))
        {
            var field = (AbstractDataclassFieldSummary)receiver.Value;
            value = AbstractValue.String(field.Name, span);
            return true;
        }

        if (receiver.Kind == AbstractValueKind.KnownCallable &&
            TryGetKnownCallableMemberValue((string)receiver.Value, memberName, span, out value))
        {
            return true;
        }

        foreach (var contract in MemberValueContracts)
        {
            if (contract.ReceiverKind == receiver.Kind &&
                contract.MemberName == memberName)
            {
                value = CreateReturnValue(contract.ValueShape, span);
                return true;
            }
        }

        value = default;
        return false;
    }

    private static bool TryGetKnownCallableMemberValue(string targetName, string memberName, LythonSourceSpan span, out AbstractValue value)
    {
        value = targetName switch
        {
            "datetime.date" => memberName switch
            {
                "min" or "max" => AbstractValue.DateTimeDate(span),
                "resolution" => AbstractValue.DateTimeTimedelta(span),
                "today" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateToday.Name, span),
                "fromtimestamp" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateFromTimestamp.Name, span),
                "fromordinal" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateFromOrdinal.Name, span),
                "fromisoformat" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateFromIsoFormat.Name, span),
                "fromisocalendar" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateFromIsoCalendar.Name, span),
                _ => default
            },
            "datetime.time" => memberName switch
            {
                "min" or "max" => AbstractValue.DateTimeTime(span),
                "resolution" => AbstractValue.DateTimeTimedelta(span),
                "fromisoformat" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeTimeFromIsoFormat.Name, span),
                _ => default
            },
            "datetime.datetime" => memberName switch
            {
                "min" or "max" => AbstractValue.DateTimeDateTime(span),
                "resolution" => AbstractValue.DateTimeTimedelta(span),
                "today" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateTimeToday.Name, span),
                "now" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateTimeNow.Name, span),
                "utcnow" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateTimeUtcNow.Name, span),
                "fromtimestamp" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateTimeFromTimestamp.Name, span),
                "utcfromtimestamp" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateTimeUtcFromTimestamp.Name, span),
                "fromordinal" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateTimeFromOrdinal.Name, span),
                "combine" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateTimeCombine.Name, span),
                "fromisoformat" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateTimeFromIsoFormat.Name, span),
                "fromisocalendar" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateTimeFromIsoCalendar.Name, span),
                "strptime" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.DateTimeDateTimeStrptime.Name, span),
                _ => default
            },
            "datetime.timezone" => memberName switch
            {
                "utc" => AbstractValue.DateTimeTimezone(span),
                _ => default
            },
            "datetime.timedelta" => memberName switch
            {
                "min" or "max" or "resolution" => AbstractValue.DateTimeTimedelta(span),
                _ => default
            },
            "statistics.NormalDist" => memberName switch
            {
                "from_samples" => AbstractValue.KnownCallable(LythonKnownCallableSignatures.StatisticsNormalDistFromSamples.Name, span),
                _ => default
            },
            _ => default
        };

        return value.Kind != default;
    }
}
