using Lokad.Lython.Runtime;

namespace Lokad.Lython.Frontend;

internal static partial class StaticContracts
{
    private static readonly StaticKnownCallContract[] KnownCallContracts =
    [
        new(LythonKnownCallableSignatures.SysExit, "LA3151", "sys.exit([code]) expects zero or one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.SysGetDefaultEncoding, "LA3151", "sys.getdefaultencoding() expects no arguments.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.SysExcInfo, "LA3151", "sys.exc_info() expects no arguments."),
        new(LythonKnownCallableSignatures.SysGetSizeOf, "LA3151", "sys.getsizeof(object[, default]) expects one or two arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.SysSetTrace, "LA3151", "sys.settrace(function) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.SysSetProfile, "LA3151", "sys.setprofile(function) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.SysSetRecursionLimit, "LA3151", "sys.setrecursionlimit(limit) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.SysAddAuditHook, "LA3151", "sys.addaudithook(hook) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.SysAudit, "LA3151", "sys.audit(event[, args]) expects one or two arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.PathlibPath, "LA3151", "pathlib.Path([path][, ...]) expects string or Path path arguments.", StaticReturnShape.Path),
        new(LythonKnownCallableSignatures.PathlibPurePath, "LA3151", "pathlib.PurePath([path][, ...]) expects string or Path path arguments.", StaticReturnShape.Path),
        new(LythonKnownCallableSignatures.PathlibPurePosixPath, "LA3151", "pathlib.PurePosixPath([path][, ...]) expects string or Path path arguments.", StaticReturnShape.Path),
        new(LythonKnownCallableSignatures.PathlibPosixPath, "LA3151", "pathlib.PosixPath([path][, ...]) expects string or Path path arguments.", StaticReturnShape.Path),
        new(LythonKnownCallableSignatures.PathlibPureWindowsPath, "LA3151", "pathlib.PureWindowsPath(...) is not supported by Lython's normalized POSIX-like path model."),
        new(LythonKnownCallableSignatures.PathlibWindowsPath, "LA3151", "pathlib.WindowsPath(...) is not supported by Lython's normalized POSIX-like path model."),
        new(LythonKnownCallableSignatures.JsonLoads, "LA3151", "json.loads(s) expects one argument."),
        new(LythonKnownCallableSignatures.JsonDumps, "LA3151", "json.dumps(obj) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.CsvReader, "LA3151", "csv.reader(csvfile[, dialect][, ...]) expects one argument and supported CSV options.", StaticReturnShape.CsvReader),
        new(LythonKnownCallableSignatures.CsvWriter, "LA3151", "csv.writer([fileobj][, dialect][, ...]) expects a text file handle or no file object.", StaticReturnShape.CsvWriter),
        new(LythonKnownCallableSignatures.CsvDictReader, "LA3151", "csv.DictReader(f[, fieldnames][, restkey][, restval][, ...]) expects supported CSV options.", StaticReturnShape.CsvDictReader),
        new(LythonKnownCallableSignatures.CsvDictWriter, "LA3151", "csv.DictWriter(f, fieldnames, ...) expects a text file handle and field names.", StaticReturnShape.CsvDictWriter),
        new(LythonKnownCallableSignatures.CollectionsDefaultDict, "LA3151", "collections.defaultdict([default_factory][, iterable], **kwargs) expects supported arguments.", StaticReturnShape.CollectionsDefaultDict),
        new(LythonKnownCallableSignatures.CollectionsCounter, "LA3151", "collections.Counter([iterable], **kwargs) expects supported arguments.", StaticReturnShape.CollectionsCounter),
        new(LythonKnownCallableSignatures.CollectionsDeque, "LA3151", "collections.deque([iterable][, maxlen]) expects supported arguments.", StaticReturnShape.CollectionsDeque),
        new(LythonKnownCallableSignatures.CollectionsNamedTuple, "LA3151", "collections.namedtuple(typename, field_names[, rename][, defaults][, module]) expects supported arguments."),
        new(LythonKnownCallableSignatures.CollectionsOrderedDict, "LA3151", "collections.OrderedDict([mapping], **kwargs) expects supported arguments.", StaticReturnShape.Dict),
        new(LythonKnownCallableSignatures.CollectionsChainMap, "LA3151", "collections.ChainMap(*maps) expects positional mapping arguments.", StaticReturnShape.CollectionsChainMap),
        new(LythonKnownCallableSignatures.CollectionsUserDict, "LA3151", "collections.UserDict is explicitly unsupported by Lython."),
        new(LythonKnownCallableSignatures.CollectionsUserList, "LA3151", "collections.UserList is explicitly unsupported by Lython."),
        new(LythonKnownCallableSignatures.CollectionsUserString, "LA3151", "collections.UserString is explicitly unsupported by Lython."),
        new(LythonKnownCallableSignatures.OpenPyxlWorkbook, "LA3151", "openpyxl.Workbook([write_only][, iso_dates]) expects zero to two arguments.", StaticReturnShape.OpenPyxlWorkbook),
        new(LythonKnownCallableSignatures.OpenPyxlLoadWorkbook, "LA3151", "openpyxl.load_workbook(filename[, read_only][, keep_vba][, data_only][, keep_links][, rich_text]) expects one to six arguments.", StaticReturnShape.OpenPyxlWorkbook),
        new(LythonKnownCallableSignatures.OpenPyxlGetColumnLetter, "LA3151", "openpyxl.utils.get_column_letter(col_idx) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OpenPyxlColumnIndexFromString, "LA3151", "openpyxl.utils.column_index_from_string(col) expects one argument.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.OpenPyxlCoordinateFromString, "LA3151", "openpyxl.utils.coordinate_from_string(coord_string) expects one argument."),
        new(LythonKnownCallableSignatures.OpenPyxlCoordinateToTuple, "LA3151", "openpyxl.utils.coordinate_to_tuple(coordinate) expects one argument."),
        new(LythonKnownCallableSignatures.OpenPyxlRangeBoundaries, "LA3151", "openpyxl.utils.range_boundaries(range_string) expects one argument."),
        new(LythonKnownCallableSignatures.OpenPyxlGetColumnInterval, "LA3151", "openpyxl.utils.get_column_interval(start, end) expects two arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.OpenPyxlAbsoluteCoordinate, "LA3151", "openpyxl.utils.absolute_coordinate(coord_string) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OpenPyxlQuoteSheetName, "LA3151", "openpyxl.utils.quote_sheetname(sheetname) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OpenPyxlRowsFromRange, "LA3151", "openpyxl.utils.rows_from_range(range_string) expects one argument.", StaticReturnShape.ListOfUnknown),
        new(LythonKnownCallableSignatures.OpenPyxlColsFromRange, "LA3151", "openpyxl.utils.cols_from_range(range_string) expects one argument.", StaticReturnShape.ListOfUnknown),
        new(LythonKnownCallableSignatures.OpenPyxlComment, "LA3151", "openpyxl.comments.Comment(text, author) expects two arguments.", StaticReturnShape.OpenPyxlComment),
        new(LythonKnownCallableSignatures.OpenPyxlFont, "LA3151", "openpyxl.styles.Font(...) received unsupported arguments.", StaticReturnShape.OpenPyxlFont),
        new(LythonKnownCallableSignatures.OpenPyxlPatternFill, "LA3151", "openpyxl.styles.PatternFill(...) received unsupported arguments.", StaticReturnShape.OpenPyxlPatternFill),
        new(LythonKnownCallableSignatures.OpenPyxlBorder, "LA3151", "openpyxl.styles.Border(...) received unsupported arguments.", StaticReturnShape.OpenPyxlBorder),
        new(LythonKnownCallableSignatures.OpenPyxlSide, "LA3151", "openpyxl.styles.Side(...) received unsupported arguments.", StaticReturnShape.OpenPyxlSide),
        new(LythonKnownCallableSignatures.OpenPyxlAlignment, "LA3151", "openpyxl.styles.Alignment(...) received unsupported arguments.", StaticReturnShape.OpenPyxlAlignment),
        new(LythonKnownCallableSignatures.OpenPyxlProtection, "LA3151", "openpyxl.styles.Protection(...) received unsupported arguments.", StaticReturnShape.OpenPyxlProtection),
        new(LythonKnownCallableSignatures.OpenPyxlNamedStyle, "LA3151", "openpyxl.styles.NamedStyle(...) received unsupported arguments.", StaticReturnShape.OpenPyxlNamedStyle),
        new(LythonKnownCallableSignatures.OpenPyxlColor, "LA3151", "openpyxl.styles.colors.Color(...) received unsupported arguments.", StaticReturnShape.OpenPyxlColor),
        new(LythonKnownCallableSignatures.OpenPyxlTable, "LA3151", "openpyxl.worksheet.table.Table([displayName][, ref]) expects zero to two arguments.", StaticReturnShape.OpenPyxlTable),
        new(LythonKnownCallableSignatures.OpenPyxlTableStyleInfo, "LA3151", "openpyxl.worksheet.table.TableStyleInfo(...) received unsupported arguments.", StaticReturnShape.OpenPyxlTableStyleInfo),
        new(LythonKnownCallableSignatures.OpenPyxlDataValidation, "LA3151", "openpyxl.worksheet.datavalidation.DataValidation(...) received unsupported arguments.", StaticReturnShape.OpenPyxlDataValidation),
        new(LythonKnownCallableSignatures.OpenPyxlBarChart, "LA3151", "openpyxl.chart.BarChart() expects no arguments.", StaticReturnShape.OpenPyxlChart),
        new(LythonKnownCallableSignatures.OpenPyxlLineChart, "LA3151", "openpyxl.chart.LineChart() expects no arguments.", StaticReturnShape.OpenPyxlChart),
        new(LythonKnownCallableSignatures.OpenPyxlPieChart, "LA3151", "openpyxl.chart.PieChart() expects no arguments.", StaticReturnShape.OpenPyxlChart),
        new(LythonKnownCallableSignatures.OpenPyxlScatterChart, "LA3151", "openpyxl.chart.ScatterChart() expects no arguments.", StaticReturnShape.OpenPyxlChart),
        new(LythonKnownCallableSignatures.OpenPyxlChartReference, "LA3151", "openpyxl.chart.Reference(worksheet[, min_col][, min_row][, max_col][, max_row][, range_string]) expects one to six arguments."),
        new(LythonKnownCallableSignatures.OpenPyxlChartSeries, "LA3151", "openpyxl.chart.Series([values][, xvalues][, title]) expects zero to three arguments."),
        new(LythonKnownCallableSignatures.OpenPyxlDrawingImage, "LA3151", "openpyxl.drawing.image.Image(img) expects one argument.", StaticReturnShape.OpenPyxlImage),
        new(LythonKnownCallableSignatures.ReCompile, "LA3151", "re.compile(pattern[, flags]) expects one or two arguments.", StaticReturnShape.RegexPattern),
        new(LythonKnownCallableSignatures.ReSearch, "LA3151", "re.search(pattern, string[, flags]) expects two or three arguments.", StaticReturnShape.MaybeRegexMatch),
        new(LythonKnownCallableSignatures.ReMatch, "LA3151", "re.match(pattern, string[, flags]) expects two or three arguments.", StaticReturnShape.MaybeRegexMatch),
        new(LythonKnownCallableSignatures.ReFullMatch, "LA3151", "re.fullmatch(pattern, string[, flags]) expects two or three arguments.", StaticReturnShape.MaybeRegexMatch),
        new(LythonKnownCallableSignatures.ReFindAll, "LA3151", "re.findall(pattern, string[, flags]) expects two or three arguments.", StaticReturnShape.ListOfUnknown),
        new(LythonKnownCallableSignatures.ReFindIter, "LA3151", "re.finditer(pattern, string[, flags]) expects two or three arguments."),
        new(LythonKnownCallableSignatures.ReSub, "LA3151", "re.sub(pattern, repl, string[, count][, flags]) expects three to five arguments.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.ReSubn, "LA3151", "re.subn(pattern, repl, string[, count][, flags]) expects three to five arguments."),
        new(LythonKnownCallableSignatures.ReSplit, "LA3151", "re.split(pattern, string[, maxsplit][, flags]) expects two to four arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.ReEscape, "LA3151", "re.escape(string) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.ArgparseArgumentParser, "LA3151", "argparse.ArgumentParser([prog][, usage][, description][, epilog][, formatter_class][, add_help][, allow_abbrev][, exit_on_error]) expects supported parser options.", StaticReturnShape.ArgparseParser),
        new(LythonKnownCallableSignatures.ArgparseNamespace, "LA3151", "argparse.Namespace(**kwargs) expects keyword arguments only.", StaticReturnShape.ArgparseNamespace),
        new(LythonKnownCallableSignatures.ArgparseFileType, "LA3151", "argparse.FileType([mode][, bufsize][, encoding][, errors]) expects supported text-mode options."),
        new(LythonKnownCallableSignatures.DataclassesDataclass, "LA3151", "dataclasses.dataclass([cls], ...) expects at most one positional class plus supported boolean options."),
        new(LythonKnownCallableSignatures.DataclassesField, "LA3151", "dataclasses.field(...) expects keyword-only field options."),
        new(LythonKnownCallableSignatures.DataclassesMakeDataclass, "LA3151", "dataclasses.make_dataclass(cls_name, fields, ...) expects a class name and field list."),
        new(LythonKnownCallableSignatures.DataclassesIsDataclass, "LA3151", "dataclasses.is_dataclass(value) expects one argument."),
        new(LythonKnownCallableSignatures.DataclassesFields, "LA3151", "dataclasses.fields(class_or_instance) expects one argument."),
        new(LythonKnownCallableSignatures.DataclassesAsDict, "LA3151", "dataclasses.asdict(obj[, dict_factory]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.DataclassesAsTuple, "LA3151", "dataclasses.astuple(obj[, tuple_factory]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.DataclassesReplace, "LA3151", "dataclasses.replace(obj, **changes) expects one positional object plus keyword field changes."),
        new(LythonKnownCallableSignatures.TypingTypeVar, "LA3151", "typing.TypeVar(name, ...) expects at least one argument."),
        new(LythonKnownCallableSignatures.TypingNewType, "LA3151", "typing.NewType(name, tp) expects two arguments."),
        new(LythonKnownCallableSignatures.TypingCast, "LA3151", "typing.cast(typ, val) expects two arguments."),
        new(LythonKnownCallableSignatures.TypingGetOrigin, "LA3151", "typing.get_origin(tp) expects one argument."),
        new(LythonKnownCallableSignatures.TypingGetArgs, "LA3151", "typing.get_args(tp) expects one argument."),
        new(LythonKnownCallableSignatures.TypingNamedTuple, "LA3151", "typing.NamedTuple(typename[, fields]) expects at least one argument."),
        new(LythonKnownCallableSignatures.TypingTypedDict, "LA3151", "typing.TypedDict(typename[, fields]) expects at least one argument."),
        new(LythonKnownCallableSignatures.SubprocessRun, "LA3151", "subprocess.run(args, ...) expects one command and supported subprocess options.", StaticReturnShape.SubprocessCompletedProcess),
        new(LythonKnownCallableSignatures.SubprocessCall, "LA3151", "subprocess.call(args, ...) expects one command and supported subprocess options.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.SubprocessCheckCall, "LA3151", "subprocess.check_call(args, ...) expects one command and supported subprocess options.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.SubprocessCheckOutput, "LA3151", "subprocess.check_output(args, ...) expects one command and supported subprocess options.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsListDir, "LA3151", "os.listdir([path]) expects zero or one argument.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.OsWalk, "LA3151", "os.walk([top][, topdown][, onerror][, followlinks]) expects zero to four arguments."),
        new(LythonKnownCallableSignatures.OsGetCwd, "LA3151", "os.getcwd() expects no arguments.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsFspath, "LA3151", "os.fspath(path) expects one path-like argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsStat, "LA3151", "os.stat(path) expects one path-like argument."),
        new(LythonKnownCallableSignatures.OsLstat, "LA3151", "os.lstat(path) expects one path-like argument."),
        new(LythonKnownCallableSignatures.OsScandir, "LA3151", "os.scandir([path]) expects zero or one path-like argument.", StaticReturnShape.ListOfUnknown),
        new(LythonKnownCallableSignatures.OsMkdir, "LA3151", "os.mkdir(path) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsMakedirs, "LA3151", "os.makedirs(path[, exist_ok]) expects one or two arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsRemove, "LA3151", "os.remove(path) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsUnlink, "LA3151", "os.unlink(path) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsRename, "LA3151", "os.rename(src, dst) expects two arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsReplace, "LA3151", "os.replace(src, dst) expects two arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsRmdir, "LA3151", "os.rmdir(path) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsRemovedirs, "LA3151", "os.removedirs(path) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsPathJoin, "LA3151", "os.path.join(path, *paths) expects one or more arguments.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathSplit, "LA3151", "os.path.split(path) expects one argument."),
        new(LythonKnownCallableSignatures.OsPathSplitExt, "LA3151", "os.path.splitext(path) expects one argument."),
        new(LythonKnownCallableSignatures.OsPathBasename, "LA3151", "os.path.basename(path) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathDirname, "LA3151", "os.path.dirname(path) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathIsAbs, "LA3151", "os.path.isabs(path) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OsPathNormPath, "LA3151", "os.path.normpath(path) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathAbsPath, "LA3151", "os.path.abspath(path) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathRelPath, "LA3151", "os.path.relpath(path[, start]) expects one or two arguments.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathCommonPath, "LA3151", "os.path.commonpath(paths) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathExists, "LA3151", "os.path.exists(path) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OsPathLexists, "LA3151", "os.path.lexists(path) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OsPathIsFile, "LA3151", "os.path.isfile(path) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OsPathIsDir, "LA3151", "os.path.isdir(path) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OsPathGetSize, "LA3151", "os.path.getsize(path) expects one argument.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.OsPathGetMTime, "LA3151", "os.path.getmtime(path) expects one argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.OsPathSameFile, "LA3151", "os.path.samefile(path1, path2) expects two arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OsPathRealPath, "LA3151", "os.path.realpath(path) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.Glob, "LA3151", "glob.glob(pathname[, recursive]) expects one or two arguments.", StaticReturnShape.ListOfPath),
        new(LythonKnownCallableSignatures.IGlob, "LA3151", "glob.iglob(pathname[, recursive]) expects one or two arguments.", StaticReturnShape.ListOfPath),
        new(LythonKnownCallableSignatures.GlobEscape, "LA3151", "glob.escape(pathname) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.FnMatch, "LA3151", "fnmatch.fnmatch(name, pattern) expects two arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.FnMatchFilter, "LA3151", "fnmatch.filter(names, pattern) expects two arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.DifflibIsLineJunk, "LA3151", "difflib.IS_LINE_JUNK(line) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.DifflibIsCharacterJunk, "LA3151", "difflib.IS_CHARACTER_JUNK(ch) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.DifflibUnifiedDiff, "LA3151", "difflib.unified_diff(a, b[, fromfile][, tofile][, fromfiledate][, tofiledate][, n][, lineterm]) expects two to eight arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.DifflibContextDiff, "LA3151", "difflib.context_diff(a, b[, fromfile][, tofile][, fromfiledate][, tofiledate][, n][, lineterm]) expects two to eight arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.DifflibNdiff, "LA3151", "difflib.ndiff(a, b[, linejunk][, charjunk]) expects two to four arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.DifflibRestore, "LA3151", "difflib.restore(delta, which) expects two arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.DifflibGetCloseMatches, "LA3151", "difflib.get_close_matches(word, possibilities[, n][, cutoff]) expects two to four arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.DifflibDiffBytes, "LA3151", "difflib.diff_bytes(dfunc, a, b[, fromfile][, tofile][, fromfiledate][, tofiledate][, n][, lineterm]) expects three to nine arguments.", StaticReturnShape.ListOfBytes),
        new(LythonKnownCallableSignatures.DifflibDiffer, "LA3151", "difflib.Differ([linejunk][, charjunk]) expects zero to two arguments.", StaticReturnShape.DifflibDiffer),
        new(LythonKnownCallableSignatures.DifflibHtmlDiff, "LA3151", "difflib.HtmlDiff([tabsize][, wrapcolumn][, linejunk][, charjunk]) expects zero to four arguments.", StaticReturnShape.DifflibHtmlDiff),
        new(LythonKnownCallableSignatures.DifflibSequenceMatcher, "LA3151", "difflib.SequenceMatcher([isjunk][, a][, b][, autojunk]) expects zero to four arguments.", StaticReturnShape.DifflibSequenceMatcher),
        new(LythonKnownCallableSignatures.PkgutilModuleInfo, "LA3151", "pkgutil.ModuleInfo(module_finder, name, ispkg) expects three arguments.", StaticReturnShape.PkgutilModuleInfo),
        new(LythonKnownCallableSignatures.PkgutilIterModules, "LA3151", "pkgutil.iter_modules([path][, prefix]) expects zero to two arguments.", StaticReturnShape.ListOfPkgutilModuleInfo),
        new(LythonKnownCallableSignatures.PkgutilWalkPackages, "LA3151", "pkgutil.walk_packages([path][, prefix][, onerror]) expects zero to three arguments.", StaticReturnShape.ListOfPkgutilModuleInfo),
        new(LythonKnownCallableSignatures.PkgutilFindLoader, "LA3151", "pkgutil.find_loader(fullname) expects one argument.", StaticReturnShape.PkgutilLoader),
        new(LythonKnownCallableSignatures.PkgutilGetLoader, "LA3151", "pkgutil.get_loader(module_or_name) expects one argument.", StaticReturnShape.PkgutilLoader),
        new(LythonKnownCallableSignatures.PkgutilExtendPath, "LA3151", "pkgutil.extend_path(path, name) expects two arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.PkgutilResolveName, "LA3151", "pkgutil.resolve_name(name) expects one argument."),
        new(LythonKnownCallableSignatures.PkgutilGetImporter, "LA3151", "pkgutil.get_importer(path_item) expects one argument."),
        new(LythonKnownCallableSignatures.PkgutilIterImporters, "LA3151", "pkgutil.iter_importers([fullname]) expects zero or one argument.", StaticReturnShape.ListOfUnknown),
        new(LythonKnownCallableSignatures.PkgutilIterImporterModules, "LA3151", "pkgutil.iter_importer_modules(importer[, prefix]) expects one or two arguments.", StaticReturnShape.ListOfPkgutilModuleInfo),
        new(LythonKnownCallableSignatures.PkgutilIterZipimportModules, "LA3151", "pkgutil.iter_zipimport_modules(importer[, prefix]) expects one or two arguments.", StaticReturnShape.ListOfPkgutilModuleInfo),
        new(LythonKnownCallableSignatures.PkgutilGetData, "LA3151", "pkgutil.get_data(package, resource) expects two arguments."),
        new(LythonKnownCallableSignatures.PkgutilReadCode, "LA3151", "pkgutil.read_code(stream) expects one argument."),
        new(LythonKnownCallableSignatures.ItertoolsChain, "LA3151", "itertools.chain(*iterables) expects positional iterable arguments."),
        new(LythonKnownCallableSignatures.ItertoolsCount, "LA3151", "itertools.count([start][, step]) expects zero to two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsRepeat, "LA3151", "itertools.repeat(object[, times]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsCycle, "LA3151", "itertools.cycle(iterable) expects one argument."),
        new(LythonKnownCallableSignatures.ItertoolsIslice, "LA3151", "itertools.islice(iterable, stop) or islice(iterable, start, stop[, step]) expects two to four arguments."),
        new(LythonKnownCallableSignatures.ItertoolsCombinations, "LA3151", "itertools.combinations(iterable, r) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsCombinationsWithReplacement, "LA3151", "itertools.combinations_with_replacement(iterable, r) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsPermutations, "LA3151", "itertools.permutations(iterable[, r]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsAccumulate, "LA3151", "itertools.accumulate(iterable[, func], *, initial=None) expects supported arguments."),
        new(LythonKnownCallableSignatures.ItertoolsCompress, "LA3151", "itertools.compress(data, selectors) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsFilterFalse, "LA3151", "itertools.filterfalse(function, iterable) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsDropWhile, "LA3151", "itertools.dropwhile(predicate, iterable) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsTakeWhile, "LA3151", "itertools.takewhile(predicate, iterable) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsStarmap, "LA3151", "itertools.starmap(function, iterable) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsPairwise, "LA3151", "itertools.pairwise(iterable) expects one argument."),
        new(LythonKnownCallableSignatures.ItertoolsGroupBy, "LA3151", "itertools.groupby(iterable[, key]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsTee, "LA3151", "itertools.tee(iterable[, n]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsBatched, "LA3151", "itertools.batched(iterable, n, *, strict=False) expects supported arguments."),
    ];

    public static bool TryGetKnownCallContract(string targetName, out StaticKnownCallContract contract)
    {
        foreach (var candidate in KnownCallContracts)
        {
            if (string.Equals(candidate.TargetName, targetName, StringComparison.Ordinal))
            {
                contract = candidate;
                return true;
            }
        }

        contract = default;
        return false;
    }

    public static bool TryGetKnownCallReturn(string targetName, LythonSourceSpan span, out AbstractValue value)
    {
        if (TryGetKnownCallContract(targetName, out var contract) &&
            contract.ReturnShape != StaticReturnShape.Unknown)
        {
            value = CreateReturnValue(contract.ReturnShape, span);
            return true;
        }

        value = default;
        return false;
    }
}
