using Lokad.Lython.Runtime;

namespace Lokad.Lython.Frontend;

internal static partial class StaticContracts
{
    private static readonly StaticKnownCallContract[] KnownCallContracts =
    [
        new(LythonKnownCallableSignatures.SysExit, "LA3151", "sys.exit([code]) expects zero or one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.SysGetDefaultEncoding, "LA3151", "sys.getdefaultencoding() expects no arguments.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.SysExcInfo, "LA3151", "sys.exc_info() expects no arguments."),
        new(LythonKnownCallableSignatures.SysGetSizeOf, "LA3151", "sys.getsizeof(object[, default]) expects one or two arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.SysSetTrace, "LA3151", "sys.settrace(function) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.SysSetProfile, "LA3151", "sys.setprofile(function) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.SysSetRecursionLimit, "LA3151", "sys.setrecursionlimit(limit) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.SysAddAuditHook, "LA3151", "sys.addaudithook(hook) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.SysAudit, "LA3151", "sys.audit(event[, args]) expects one or two arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.PathlibPath, "LA3151", "pathlib.Path([path][, ...]) expects string or Path path arguments.", StaticReturnShape.Path),
        new(LythonKnownCallableSignatures.PathlibPurePath, "LA3151", "pathlib.PurePath([path][, ...]) expects string or Path path arguments.", StaticReturnShape.Path),
        new(LythonKnownCallableSignatures.PathlibPurePosixPath, "LA3151", "pathlib.PurePosixPath([path][, ...]) expects string or Path path arguments.", StaticReturnShape.Path),
        new(LythonKnownCallableSignatures.PathlibPosixPath, "LA3151", "pathlib.PosixPath([path][, ...]) expects string or Path path arguments.", StaticReturnShape.Path),
        new(LythonKnownCallableSignatures.PathlibPureWindowsPath, "LA3151", "pathlib.PureWindowsPath(...) is not supported by Lython's normalized POSIX-like path model."),
        new(LythonKnownCallableSignatures.PathlibWindowsPath, "LA3151", "pathlib.WindowsPath(...) is not supported by Lython's normalized POSIX-like path model."),
        new(LythonKnownCallableSignatures.JsonLoad, "LA3151", "json.load(fp, *, ...) expects one readable text file handle.", StaticReturnShape.Unknown),
        new(LythonKnownCallableSignatures.JsonLoads, "LA3151", "json.loads(s, *, ...) expects one string argument plus supported keyword options."),
        new(LythonKnownCallableSignatures.JsonDump, "LA3151", "json.dump(obj, fp, *, ...) expects an object and writable text file handle.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.JsonDumps, "LA3151", "json.dumps(obj, *, ...) expects one object plus supported keyword options.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.CsvReader, "LA3151", "csv.reader(csvfile[, dialect][, ...]) expects one argument and supported CSV options.", StaticReturnShape.CsvReader),
        new(LythonKnownCallableSignatures.CsvWriter, "LA3151", "csv.writer([fileobj][, dialect][, ...]) expects a text file handle or no file object.", StaticReturnShape.CsvWriter),
        new(LythonKnownCallableSignatures.CsvDictReader, "LA3151", "csv.DictReader(f[, fieldnames][, restkey][, restval][, ...]) expects supported CSV options.", StaticReturnShape.CsvDictReader),
        new(LythonKnownCallableSignatures.CsvDictWriter, "LA3151", "csv.DictWriter(f, fieldnames, ...) expects a text file handle and field names.", StaticReturnShape.CsvDictWriter),
        new(LythonKnownCallableSignatures.CollectionsDefaultDict, "LA3151", "collections.defaultdict([default_factory][, iterable], **kwargs) expects supported arguments.", StaticReturnShape.CollectionsDefaultDict),
        new(LythonKnownCallableSignatures.CollectionsCounter, "LA3151", "collections.Counter([iterable], **kwargs) expects supported arguments.", StaticReturnShape.CollectionsCounter),
        new(LythonKnownCallableSignatures.CollectionsDeque, "LA3151", "collections.deque([iterable][, maxlen]) expects supported arguments.", StaticReturnShape.CollectionsDeque),
        new(LythonKnownCallableSignatures.CollectionsNamedTuple, "LA3151", "collections.namedtuple(typename, field_names[, rename][, defaults][, module]) expects supported arguments."),
        new(LythonKnownCallableSignatures.CollectionsOrderedDict, "LA3151", "collections.OrderedDict([mapping], **kwargs) expects supported arguments.", StaticReturnShape.Dict),
        new(LythonKnownCallableSignatures.CollectionsChainMap, "LA3151", "collections.ChainMap(*maps) expects positional mapping arguments.", StaticReturnShape.CollectionsChainMap),
        new(LythonKnownCallableSignatures.CollectionsUserDict, "LA3151", "collections.UserDict is explicitly unsupported by Lython."),
        new(LythonKnownCallableSignatures.CollectionsUserList, "LA3151", "collections.UserList is explicitly unsupported by Lython."),
        new(LythonKnownCallableSignatures.CollectionsUserString, "LA3151", "collections.UserString is explicitly unsupported by Lython."),
        new(LythonKnownCallableSignatures.CopyCopy, "LA3151", "copy.copy(x) expects one argument."),
        new(LythonKnownCallableSignatures.CopyDeepCopy, "LA3151", "copy.deepcopy(x, memo=None) expects one argument plus an optional memo dict."),
        new(LythonKnownCallableSignatures.CopyReplace, "LA3151", "copy.replace(obj, /, **changes) expects one positional object plus keyword changes."),
        new(LythonKnownCallableSignatures.FunctoolsUpdateWrapper, "LA3151", "functools.update_wrapper(wrapper, wrapped[, assigned][, updated]) expects two to four arguments."),
        new(LythonKnownCallableSignatures.FunctoolsWraps, "LA3151", "functools.wraps(wrapped[, assigned][, updated]) expects one to three arguments."),
        new(LythonKnownCallableSignatures.FunctoolsTotalOrdering, "LA3151", "functools.total_ordering(cls) expects one class argument."),
        new(LythonKnownCallableSignatures.FunctoolsReduce, "LA3151", "functools.reduce(function, iterable[, initializer]) expects two or three arguments."),
        new(LythonKnownCallableSignatures.FunctoolsPartial, "LA3151", "functools.partial(func, ...) expects the first argument to be callable."),
        new(LythonKnownCallableSignatures.FunctoolsPartialMethod, "LA3151", "functools.partialmethod(func, ...) expects the first argument to be callable."),
        new(LythonKnownCallableSignatures.FunctoolsCmpToKey, "LA3151", "functools.cmp_to_key(mycmp) expects one callable argument."),
        new(LythonKnownCallableSignatures.FunctoolsLruCache, "LA3151", "functools.lru_cache(maxsize=128, typed=False) expects supported cache options."),
        new(LythonKnownCallableSignatures.FunctoolsCache, "LA3151", "functools.cache(user_function) expects one callable argument."),
        new(LythonKnownCallableSignatures.FunctoolsCachedProperty, "LA3151", "functools.cached_property(func) expects one callable argument."),
        new(LythonKnownCallableSignatures.FunctoolsSingleDispatch, "LA3151", "functools.singledispatch(func) expects one callable argument."),
        new(LythonKnownCallableSignatures.FunctoolsSingleDispatchMethod, "LA3151", "functools.singledispatchmethod(func) expects one callable argument."),
        new(LythonKnownCallableSignatures.FunctoolsRecursiveRepr, "LA3151", "functools.recursive_repr(fillvalue='...') expects zero or one argument."),
        new(LythonKnownCallableSignatures.OperatorTruth, "LA3151", "operator.truth(obj) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OperatorNot, "LA3151", "operator.not_(obj) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OperatorIs, "LA3151", "operator.is_(a, b) expects two arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OperatorIsNot, "LA3151", "operator.is_not(a, b) expects two arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OperatorAbs, "LA3151", "operator.abs(obj) expects one numeric argument."),
        new(LythonKnownCallableSignatures.OperatorNeg, "LA3151", "operator.neg(obj) expects one numeric argument."),
        new(LythonKnownCallableSignatures.OperatorPos, "LA3151", "operator.pos(obj) expects one numeric argument."),
        new(LythonKnownCallableSignatures.OperatorInvert, "LA3151", "operator.invert(obj) expects one integer argument.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.OperatorIndex, "LA3151", "operator.index(obj) expects one integer-compatible argument.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.OperatorAdd, "LA3151", "operator.add(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorSub, "LA3151", "operator.sub(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorMul, "LA3151", "operator.mul(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorTrueDiv, "LA3151", "operator.truediv(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorFloorDiv, "LA3151", "operator.floordiv(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorMod, "LA3151", "operator.mod(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorPow, "LA3151", "operator.pow(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorMatMul, "LA3151", "operator.matmul(a, b) is explicitly unsupported because Lython has no matrix multiplication operator."),
        new(LythonKnownCallableSignatures.OperatorLShift, "LA3151", "operator.lshift(a, b) expects two integer arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.OperatorRShift, "LA3151", "operator.rshift(a, b) expects two integer arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.OperatorAnd, "LA3151", "operator.and_(a, b) expects two compatible integer or set-like arguments."),
        new(LythonKnownCallableSignatures.OperatorOr, "LA3151", "operator.or_(a, b) expects two compatible integer or set-like arguments."),
        new(LythonKnownCallableSignatures.OperatorXor, "LA3151", "operator.xor(a, b) expects two compatible integer or set-like arguments."),
        new(LythonKnownCallableSignatures.OperatorConcat, "LA3151", "operator.concat(a, b) expects two compatible sequence arguments."),
        new(LythonKnownCallableSignatures.OperatorEq, "LA3151", "operator.eq(a, b) expects two arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OperatorNe, "LA3151", "operator.ne(a, b) expects two arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OperatorLt, "LA3151", "operator.lt(a, b) expects two comparable arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OperatorLe, "LA3151", "operator.le(a, b) expects two comparable arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OperatorGt, "LA3151", "operator.gt(a, b) expects two comparable arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OperatorGe, "LA3151", "operator.ge(a, b) expects two comparable arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OperatorGetItem, "LA3151", "operator.getitem(obj, key) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorSetItem, "LA3151", "operator.setitem(obj, key, value) expects three arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OperatorDelItem, "LA3151", "operator.delitem(obj, key) expects two arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OperatorContains, "LA3151", "operator.contains(obj, value) expects two arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OperatorLengthHint, "LA3151", "operator.length_hint(obj, default=0) expects one or two arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.OperatorCountOf, "LA3151", "operator.countOf(a, b) expects two arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.OperatorIndexOf, "LA3151", "operator.indexOf(a, b) expects two arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.OperatorIAdd, "LA3151", "operator.iadd(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorISub, "LA3151", "operator.isub(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorIMul, "LA3151", "operator.imul(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorITrueDiv, "LA3151", "operator.itruediv(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorIFloorDiv, "LA3151", "operator.ifloordiv(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorIMod, "LA3151", "operator.imod(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorIPow, "LA3151", "operator.ipow(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorILShift, "LA3151", "operator.ilshift(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorIRShift, "LA3151", "operator.irshift(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorIAnd, "LA3151", "operator.iand(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorIOr, "LA3151", "operator.ior(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorIXor, "LA3151", "operator.ixor(a, b) expects two arguments."),
        new(LythonKnownCallableSignatures.OperatorIConcat, "LA3151", "operator.iconcat(a, b) expects two sequence-compatible arguments."),
        new(LythonKnownCallableSignatures.OperatorCall, "LA3151", "operator.call(obj, /, *args, **kwargs) expects at least one callable argument."),
        new(LythonKnownCallableSignatures.OperatorItemGetter, "LA3151", "operator.itemgetter(item, ...) expects one or more positional item keys."),
        new(LythonKnownCallableSignatures.OperatorAttrGetter, "LA3151", "operator.attrgetter(attr, ...) expects one or more positional string attributes."),
        new(LythonKnownCallableSignatures.OperatorMethodCaller, "LA3151", "operator.methodcaller(name, ...) expects a method-name string and optional call arguments."),
        new(LythonKnownCallableSignatures.Decimal, "LA3151", "decimal.Decimal([value][, context]) expects a supported fixed-precision decimal value.", StaticReturnShape.Decimal),
        new(LythonKnownCallableSignatures.DecimalTuple, "LA3151", "decimal.DecimalTuple(sign, digits, exponent) expects three arguments.", StaticReturnShape.DecimalTuple),
        new(LythonKnownCallableSignatures.DecimalContext, "LA3151", "decimal.Context(...) expects supported context options.", StaticReturnShape.DecimalContext),
        new(LythonKnownCallableSignatures.DecimalGetContext, "LA3151", "decimal.getcontext() expects no arguments.", StaticReturnShape.DecimalContext),
        new(LythonKnownCallableSignatures.DecimalSetContext, "LA3151", "decimal.setcontext(context) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.DecimalLocalContext, "LA3151", "decimal.localcontext([context]) expects zero or one argument."),
        new(LythonKnownCallableSignatures.DateTimeTimedelta, "LA3151", "datetime.timedelta(...) expects supported duration fields.", StaticReturnShape.DateTimeTimedelta),
        new(LythonKnownCallableSignatures.DateTimeDate, "LA3151", "datetime.date(year, month, day) expects three arguments.", StaticReturnShape.DateTimeDate),
        new(LythonKnownCallableSignatures.DateTimeDateToday, "LA3151", "datetime.date.today() expects no arguments.", StaticReturnShape.DateTimeDate),
        new(LythonKnownCallableSignatures.DateTimeDateFromTimestamp, "LA3151", "datetime.date.fromtimestamp(timestamp) expects one argument.", StaticReturnShape.DateTimeDate),
        new(LythonKnownCallableSignatures.DateTimeDateFromOrdinal, "LA3151", "datetime.date.fromordinal(ordinal) expects one argument.", StaticReturnShape.DateTimeDate),
        new(LythonKnownCallableSignatures.DateTimeDateFromIsoFormat, "LA3151", "datetime.date.fromisoformat(date_string) expects one argument.", StaticReturnShape.DateTimeDate),
        new(LythonKnownCallableSignatures.DateTimeDateFromIsoCalendar, "LA3151", "datetime.date.fromisocalendar(year, week, day) expects three arguments.", StaticReturnShape.DateTimeDate),
        new(LythonKnownCallableSignatures.DateTimeTime, "LA3151", "datetime.time([hour][, minute][, second][, microsecond][, tzinfo][, fold]) expects supported arguments.", StaticReturnShape.DateTimeTime),
        new(LythonKnownCallableSignatures.DateTimeTimeFromIsoFormat, "LA3151", "datetime.time.fromisoformat(time_string) expects one argument.", StaticReturnShape.DateTimeTime),
        new(LythonKnownCallableSignatures.DateTimeDateTime, "LA3151", "datetime.datetime(year, month, day[, ...]) expects at least year, month, and day.", StaticReturnShape.DateTimeDateTime),
        new(LythonKnownCallableSignatures.DateTimeDateTimeToday, "LA3151", "datetime.datetime.today() expects no arguments.", StaticReturnShape.DateTimeDateTime),
        new(LythonKnownCallableSignatures.DateTimeDateTimeNow, "LA3151", "datetime.datetime.now([tz]) expects zero or one argument.", StaticReturnShape.DateTimeDateTime),
        new(LythonKnownCallableSignatures.DateTimeDateTimeUtcNow, "LA3151", "datetime.datetime.utcnow() expects no arguments.", StaticReturnShape.DateTimeDateTime),
        new(LythonKnownCallableSignatures.DateTimeDateTimeFromTimestamp, "LA3151", "datetime.datetime.fromtimestamp(timestamp[, tz]) expects one or two arguments.", StaticReturnShape.DateTimeDateTime),
        new(LythonKnownCallableSignatures.DateTimeDateTimeUtcFromTimestamp, "LA3151", "datetime.datetime.utcfromtimestamp(timestamp) expects one argument.", StaticReturnShape.DateTimeDateTime),
        new(LythonKnownCallableSignatures.DateTimeDateTimeFromOrdinal, "LA3151", "datetime.datetime.fromordinal(ordinal) expects one argument.", StaticReturnShape.DateTimeDateTime),
        new(LythonKnownCallableSignatures.DateTimeDateTimeCombine, "LA3151", "datetime.datetime.combine(date, time[, tzinfo]) expects two or three arguments.", StaticReturnShape.DateTimeDateTime),
        new(LythonKnownCallableSignatures.DateTimeDateTimeFromIsoFormat, "LA3151", "datetime.datetime.fromisoformat(date_string) expects one argument.", StaticReturnShape.DateTimeDateTime),
        new(LythonKnownCallableSignatures.DateTimeDateTimeFromIsoCalendar, "LA3151", "datetime.datetime.fromisocalendar(year, week, day) expects three arguments.", StaticReturnShape.DateTimeDateTime),
        new(LythonKnownCallableSignatures.DateTimeDateTimeStrptime, "LA3151", "datetime.datetime.strptime(date_string, format) expects two arguments.", StaticReturnShape.DateTimeDateTime),
        new(LythonKnownCallableSignatures.DateTimeTimezone, "LA3151", "datetime.timezone(offset[, name]) expects a timedelta offset and optional name.", StaticReturnShape.DateTimeTimezone),
        new(LythonKnownCallableSignatures.DateTimeTzInfo, "LA3151", "datetime.tzinfo() is abstract; use datetime.timezone(...)."),
        new(LythonKnownCallableSignatures.StatisticsMean, "LA3151", "statistics.mean(data) expects one iterable.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.StatisticsFMean, "LA3151", "statistics.fmean(data[, weights]) expects iterable data and optional weights.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.StatisticsGeometricMean, "LA3151", "statistics.geometric_mean(data) expects one iterable.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.StatisticsHarmonicMean, "LA3151", "statistics.harmonic_mean(data, *, weights=None) expects one iterable plus optional weights.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.StatisticsMedian, "LA3151", "statistics.median(data) expects one iterable.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.StatisticsMedianLow, "LA3151", "statistics.median_low(data) expects one iterable."),
        new(LythonKnownCallableSignatures.StatisticsMedianHigh, "LA3151", "statistics.median_high(data) expects one iterable."),
        new(LythonKnownCallableSignatures.StatisticsMedianGrouped, "LA3151", "statistics.median_grouped(data[, interval]) expects one iterable and optional interval.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.StatisticsMode, "LA3151", "statistics.mode(data) expects one iterable."),
        new(LythonKnownCallableSignatures.StatisticsMultiMode, "LA3151", "statistics.multimode(data) expects one iterable.", StaticReturnShape.ListOfUnknown),
        new(LythonKnownCallableSignatures.StatisticsPStdev, "LA3151", "statistics.pstdev(data[, mu]) expects iterable data and an optional center.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.StatisticsStdev, "LA3151", "statistics.stdev(data[, xbar]) expects iterable data and an optional center.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.StatisticsPVariance, "LA3151", "statistics.pvariance(data[, mu]) expects iterable data and an optional center.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.StatisticsVariance, "LA3151", "statistics.variance(data[, xbar]) expects iterable data and an optional center.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.StatisticsQuantiles, "LA3151", "statistics.quantiles(data, *, n=4, method='exclusive') expects one iterable plus optional keyword parameters.", StaticReturnShape.ListOfFloat),
        new(LythonKnownCallableSignatures.StatisticsCovariance, "LA3151", "statistics.covariance(x, y) expects two iterables.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.StatisticsCorrelation, "LA3151", "statistics.correlation(x, y) expects two iterables.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.StatisticsLinearRegression, "LA3151", "statistics.linear_regression(x, y, *, proportional=False) expects two iterables.", StaticReturnShape.StatisticsLinearRegression),
        new(LythonKnownCallableSignatures.StatisticsLinearRegressionResult, "LA3151", "statistics.LinearRegression(slope, intercept) expects two numeric fields.", StaticReturnShape.StatisticsLinearRegression),
        new(LythonKnownCallableSignatures.StatisticsNormalDist, "LA3151", "statistics.NormalDist([mu][, sigma]) expects zero to two real numbers.", StaticReturnShape.StatisticsNormalDist),
        new(LythonKnownCallableSignatures.StatisticsNormalDistFromSamples, "LA3151", "statistics.NormalDist.from_samples(data) expects one iterable.", StaticReturnShape.StatisticsNormalDist),
        new(LythonKnownCallableSignatures.StatisticsKde, "LA3151", "statistics.kde(...) is explicitly unsupported by Lython."),
        new(LythonKnownCallableSignatures.StatisticsKdeRandom, "LA3151", "statistics.kde_random(...) is explicitly unsupported by Lython."),
        new(LythonKnownCallableSignatures.RandomClass, "LA3151", "random.Random([a]) expects an optional seed.", StaticReturnShape.Random),
        new(LythonKnownCallableSignatures.RandomSystemRandom, "LA3151", "random.SystemRandom(...) is explicitly unsupported by Lython."),
        new(LythonKnownCallableSignatures.RandomSeed, "LA3151", "random.seed(a=None, version=2) expects supported seed arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.RandomRandom, "LA3151", "random.random() expects no arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.RandomGetState, "LA3151", "random.getstate() expects no arguments."),
        new(LythonKnownCallableSignatures.RandomSetState, "LA3151", "random.setstate(state) expects one state object.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.RandomRandRange, "LA3151", "random.randrange(start, stop=None, step=1) expects one to three integer arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.RandomRandInt, "LA3151", "random.randint(a, b) expects two integer arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.RandomChoice, "LA3151", "random.choice(seq) expects one sequence.", StaticReturnShape.Unknown),
        new(LythonKnownCallableSignatures.RandomChoices, "LA3151", "random.choices(population, weights=None, *, cum_weights=None, k=1) expects supported arguments.", StaticReturnShape.ListOfUnknown),
        new(LythonKnownCallableSignatures.RandomShuffle, "LA3151", "random.shuffle(x) expects one mutable sequence.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.RandomSample, "LA3151", "random.sample(population, k, *, counts=None) expects two arguments plus optional counts.", StaticReturnShape.ListOfUnknown),
        new(LythonKnownCallableSignatures.RandomGetRandBits, "LA3151", "random.getrandbits(k) expects one integer argument.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.RandomRandBytes, "LA3151", "random.randbytes(n) expects one integer argument.", StaticReturnShape.Bytes),
        new(LythonKnownCallableSignatures.RandomUniform, "LA3151", "random.uniform(a, b) expects two real arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.RandomTriangular, "LA3151", "random.triangular(low=0.0, high=1.0, mode=None) expects zero to three real arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.RandomBetaVariate, "LA3151", "random.betavariate(alpha, beta) expects two positive real arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.RandomExpVariate, "LA3151", "random.expovariate(lambd=1.0) expects zero or one real argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.RandomGammaVariate, "LA3151", "random.gammavariate(alpha, beta) expects two positive real arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.RandomGauss, "LA3151", "random.gauss(mu=0.0, sigma=1.0) expects zero to two real arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.RandomNormalVariate, "LA3151", "random.normalvariate(mu=0.0, sigma=1.0) expects zero to two real arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.RandomLogNormVariate, "LA3151", "random.lognormvariate(mu, sigma) expects two real arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.RandomParetoVariate, "LA3151", "random.paretovariate(alpha) expects one positive real argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.RandomVonMisesVariate, "LA3151", "random.vonmisesvariate(mu, kappa) expects two real arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.RandomWeibullVariate, "LA3151", "random.weibullvariate(alpha, beta) expects two positive real arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathSqrt, "LA3151", "math.sqrt(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathExp, "LA3151", "math.exp(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathLog, "LA3151", "math.log(x[, base]) expects one or two numeric arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathLog10, "LA3151", "math.log10(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathLog2, "LA3151", "math.log2(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathSin, "LA3151", "math.sin(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathCos, "LA3151", "math.cos(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathTan, "LA3151", "math.tan(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathAsin, "LA3151", "math.asin(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathAcos, "LA3151", "math.acos(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathAtan, "LA3151", "math.atan(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathAtan2, "LA3151", "math.atan2(y, x) expects two numeric arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathSinh, "LA3151", "math.sinh(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathCosh, "LA3151", "math.cosh(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathTanh, "LA3151", "math.tanh(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathFloor, "LA3151", "math.floor(x) expects one numeric argument.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.MathCeil, "LA3151", "math.ceil(x) expects one numeric argument.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.MathFabs, "LA3151", "math.fabs(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathTrunc, "LA3151", "math.trunc(x) expects one numeric argument.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.MathDegrees, "LA3151", "math.degrees(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathRadians, "LA3151", "math.radians(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathIsFinite, "LA3151", "math.isfinite(x) expects one numeric argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.MathIsInf, "LA3151", "math.isinf(x) expects one numeric argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.MathIsNaN, "LA3151", "math.isnan(x) expects one numeric argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.MathPow, "LA3151", "math.pow(x, y) expects two numeric arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathHypot, "LA3151", "math.hypot(*coordinates) expects numeric positional arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathFmod, "LA3151", "math.fmod(x, y) expects two numeric arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathCopySign, "LA3151", "math.copysign(x, y) expects two numeric arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathIsClose, "LA3151", "math.isclose(a, b[, rel_tol][, abs_tol]) expects two to four numeric arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.MathProd, "LA3151", "math.prod(iterable, *, start=1) expects one iterable plus optional keyword start."),
        new(LythonKnownCallableSignatures.MathFsum, "LA3151", "math.fsum(iterable) expects one iterable.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathFactorial, "LA3151", "math.factorial(n) expects one integer argument.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.MathGcd, "LA3151", "math.gcd(*integers) expects integer positional arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.MathLcm, "LA3151", "math.lcm(*integers) expects integer positional arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.MathComb, "LA3151", "math.comb(n, k) expects two integer arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.MathPerm, "LA3151", "math.perm(n[, k]) expects one or two integer arguments.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.MathIsqrt, "LA3151", "math.isqrt(n) expects one integer argument.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.MathDist, "LA3151", "math.dist(p, q) expects two iterable points.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathFrexp, "LA3151", "math.frexp(x) expects one numeric argument.", StaticReturnShape.TupleFloatInteger),
        new(LythonKnownCallableSignatures.MathLdexp, "LA3151", "math.ldexp(x, i) expects a numeric value and integer exponent.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathModf, "LA3151", "math.modf(x) expects one numeric argument.", StaticReturnShape.TupleFloatFloat),
        new(LythonKnownCallableSignatures.MathRemainder, "LA3151", "math.remainder(x, y) expects two numeric arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathNextAfter, "LA3151", "math.nextafter(x, y, *, steps=None) expects two numeric arguments and optional integer steps.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathUlp, "LA3151", "math.ulp(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathExp2, "LA3151", "math.exp2(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathExpm1, "LA3151", "math.expm1(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathLog1p, "LA3151", "math.log1p(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathCbrt, "LA3151", "math.cbrt(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathErf, "LA3151", "math.erf(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathErfc, "LA3151", "math.erfc(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathGamma, "LA3151", "math.gamma(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathLgamma, "LA3151", "math.lgamma(x) expects one numeric argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathFma, "LA3151", "math.fma(x, y, z) expects three numeric arguments.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.MathSumProd, "LA3151", "math.sumprod(p, q) expects two iterables."),
        new(LythonKnownCallableSignatures.OpenPyxlWorkbook, "LA3151", "openpyxl.Workbook([write_only][, iso_dates]) expects zero to two arguments.", StaticReturnShape.OpenPyxlWorkbook),
        new(LythonKnownCallableSignatures.OpenPyxlLoadWorkbook, "LA3151", "openpyxl.load_workbook(filename[, read_only][, keep_vba][, data_only][, keep_links][, rich_text]) expects one to six arguments.", StaticReturnShape.OpenPyxlWorkbook),
        new(LythonKnownCallableSignatures.OpenPyxlGetColumnLetter, "LA3151", "openpyxl.utils.get_column_letter(col_idx) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OpenPyxlColumnIndexFromString, "LA3151", "openpyxl.utils.column_index_from_string(col) expects one argument.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.OpenPyxlCoordinateFromString, "LA3151", "openpyxl.utils.coordinate_from_string(coord_string) expects one argument."),
        new(LythonKnownCallableSignatures.OpenPyxlCoordinateToTuple, "LA3151", "openpyxl.utils.coordinate_to_tuple(coordinate) expects one argument."),
        new(LythonKnownCallableSignatures.OpenPyxlRangeBoundaries, "LA3151", "openpyxl.utils.range_boundaries(range_string) expects one argument."),
        new(LythonKnownCallableSignatures.OpenPyxlGetColumnInterval, "LA3151", "openpyxl.utils.get_column_interval(start, end) expects two arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.OpenPyxlAbsoluteCoordinate, "LA3151", "openpyxl.utils.absolute_coordinate(coord_string) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OpenPyxlQuoteSheetName, "LA3151", "openpyxl.utils.quote_sheetname(sheetname) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OpenPyxlRowsFromRange, "LA3151", "openpyxl.utils.rows_from_range(range_string) expects one argument.", StaticReturnShape.ListOfUnknown),
        new(LythonKnownCallableSignatures.OpenPyxlColsFromRange, "LA3151", "openpyxl.utils.cols_from_range(range_string) expects one argument.", StaticReturnShape.ListOfUnknown),
        new(LythonKnownCallableSignatures.OpenPyxlComment, "LA3151", "openpyxl.comments.Comment(text, author) expects two arguments.", StaticReturnShape.OpenPyxlComment),
        new(LythonKnownCallableSignatures.OpenPyxlFont, "LA3151", "openpyxl.styles.Font(...) received unsupported arguments.", StaticReturnShape.OpenPyxlFont),
        new(LythonKnownCallableSignatures.OpenPyxlPatternFill, "LA3151", "openpyxl.styles.PatternFill(...) received unsupported arguments.", StaticReturnShape.OpenPyxlPatternFill),
        new(LythonKnownCallableSignatures.OpenPyxlBorder, "LA3151", "openpyxl.styles.Border(...) received unsupported arguments.", StaticReturnShape.OpenPyxlBorder),
        new(LythonKnownCallableSignatures.OpenPyxlSide, "LA3151", "openpyxl.styles.Side(...) received unsupported arguments.", StaticReturnShape.OpenPyxlSide),
        new(LythonKnownCallableSignatures.OpenPyxlAlignment, "LA3151", "openpyxl.styles.Alignment(...) received unsupported arguments.", StaticReturnShape.OpenPyxlAlignment),
        new(LythonKnownCallableSignatures.OpenPyxlProtection, "LA3151", "openpyxl.styles.Protection(...) received unsupported arguments.", StaticReturnShape.OpenPyxlProtection),
        new(LythonKnownCallableSignatures.OpenPyxlNamedStyle, "LA3151", "openpyxl.styles.NamedStyle(...) received unsupported arguments.", StaticReturnShape.OpenPyxlNamedStyle),
        new(LythonKnownCallableSignatures.OpenPyxlColor, "LA3151", "openpyxl.styles.colors.Color(...) received unsupported arguments.", StaticReturnShape.OpenPyxlColor),
        new(LythonKnownCallableSignatures.OpenPyxlTable, "LA3151", "openpyxl.worksheet.table.Table([displayName][, ref]) expects zero to two arguments.", StaticReturnShape.OpenPyxlTable),
        new(LythonKnownCallableSignatures.OpenPyxlTableStyleInfo, "LA3151", "openpyxl.worksheet.table.TableStyleInfo(...) received unsupported arguments.", StaticReturnShape.OpenPyxlTableStyleInfo),
        new(LythonKnownCallableSignatures.OpenPyxlDataValidation, "LA3151", "openpyxl.worksheet.datavalidation.DataValidation(...) received unsupported arguments.", StaticReturnShape.OpenPyxlDataValidation),
        new(LythonKnownCallableSignatures.OpenPyxlBarChart, "LA3151", "openpyxl.chart.BarChart() expects no arguments.", StaticReturnShape.OpenPyxlChart),
        new(LythonKnownCallableSignatures.OpenPyxlLineChart, "LA3151", "openpyxl.chart.LineChart() expects no arguments.", StaticReturnShape.OpenPyxlChart),
        new(LythonKnownCallableSignatures.OpenPyxlPieChart, "LA3151", "openpyxl.chart.PieChart() expects no arguments.", StaticReturnShape.OpenPyxlChart),
        new(LythonKnownCallableSignatures.OpenPyxlScatterChart, "LA3151", "openpyxl.chart.ScatterChart() expects no arguments.", StaticReturnShape.OpenPyxlChart),
        new(LythonKnownCallableSignatures.OpenPyxlChartReference, "LA3151", "openpyxl.chart.Reference(worksheet[, min_col][, min_row][, max_col][, max_row][, range_string]) expects one to six arguments."),
        new(LythonKnownCallableSignatures.OpenPyxlChartSeries, "LA3151", "openpyxl.chart.Series([values][, xvalues][, title]) expects zero to three arguments."),
        new(LythonKnownCallableSignatures.OpenPyxlDrawingImage, "LA3151", "openpyxl.drawing.image.Image(img) expects one argument.", StaticReturnShape.OpenPyxlImage),
        new(LythonKnownCallableSignatures.ReCompile, "LA3151", "re.compile(pattern[, flags]) expects one or two arguments.", StaticReturnShape.RegexPattern),
        new(LythonKnownCallableSignatures.ReSearch, "LA3151", "re.search(pattern, string[, flags][, pos][, endpos]) expects two to five arguments.", StaticReturnShape.MaybeRegexMatch),
        new(LythonKnownCallableSignatures.ReMatch, "LA3151", "re.match(pattern, string[, flags][, pos][, endpos]) expects two to five arguments.", StaticReturnShape.MaybeRegexMatch),
        new(LythonKnownCallableSignatures.ReFullMatch, "LA3151", "re.fullmatch(pattern, string[, flags][, pos][, endpos]) expects two to five arguments.", StaticReturnShape.MaybeRegexMatch),
        new(LythonKnownCallableSignatures.ReFindAll, "LA3151", "re.findall(pattern, string[, flags][, pos][, endpos]) expects two to five arguments.", StaticReturnShape.ListOfUnknown),
        new(LythonKnownCallableSignatures.ReFindIter, "LA3151", "re.finditer(pattern, string[, flags][, pos][, endpos]) expects two to five arguments."),
        new(LythonKnownCallableSignatures.ReSub, "LA3151", "re.sub(pattern, repl, string[, count][, flags][, pos][, endpos]) expects three to seven arguments.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.ReSubn, "LA3151", "re.subn(pattern, repl, string[, count][, flags][, pos][, endpos]) expects three to seven arguments."),
        new(LythonKnownCallableSignatures.ReSplit, "LA3151", "re.split(pattern, string[, maxsplit][, flags][, pos][, endpos]) expects two to six arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.ReEscape, "LA3151", "re.escape(string) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.RePurge, "LA3151", "re.purge() expects no arguments."),
        new(LythonKnownCallableSignatures.ArgparseArgumentParser, "LA3151", "argparse.ArgumentParser([prog][, usage][, description][, epilog][, formatter_class][, add_help][, allow_abbrev][, exit_on_error]) expects supported parser options.", StaticReturnShape.ArgparseParser),
        new(LythonKnownCallableSignatures.ArgparseNamespace, "LA3151", "argparse.Namespace(**kwargs) expects keyword arguments only.", StaticReturnShape.ArgparseNamespace),
        new(LythonKnownCallableSignatures.ArgparseFileType, "LA3151", "argparse.FileType([mode][, bufsize][, encoding][, errors]) expects supported text-mode options."),
        new(LythonKnownCallableSignatures.DataclassesDataclass, "LA3151", "dataclasses.dataclass([cls], ...) expects at most one positional class plus supported boolean options."),
        new(LythonKnownCallableSignatures.DataclassesField, "LA3151", "dataclasses.field(...) expects keyword-only field options."),
        new(LythonKnownCallableSignatures.DataclassesMakeDataclass, "LA3151", "dataclasses.make_dataclass(cls_name, fields, ...) expects a class name and field list."),
        new(LythonKnownCallableSignatures.DataclassesIsDataclass, "LA3151", "dataclasses.is_dataclass(value) expects one argument."),
        new(LythonKnownCallableSignatures.DataclassesFields, "LA3151", "dataclasses.fields(class_or_instance) expects one argument."),
        new(LythonKnownCallableSignatures.DataclassesAsDict, "LA3151", "dataclasses.asdict(obj[, dict_factory]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.DataclassesAsTuple, "LA3151", "dataclasses.astuple(obj[, tuple_factory]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.DataclassesReplace, "LA3151", "dataclasses.replace(obj, **changes) expects one positional object plus keyword field changes."),
        new(LythonKnownCallableSignatures.TypingTypeVar, "LA3151", "typing.TypeVar(name, ...) expects at least one argument."),
        new(LythonKnownCallableSignatures.TypingNewType, "LA3151", "typing.NewType(name, tp) expects two arguments."),
        new(LythonKnownCallableSignatures.TypingCast, "LA3151", "typing.cast(typ, val) expects two arguments."),
        new(LythonKnownCallableSignatures.TypingGetOrigin, "LA3151", "typing.get_origin(tp) expects one argument."),
        new(LythonKnownCallableSignatures.TypingGetArgs, "LA3151", "typing.get_args(tp) expects one argument."),
        new(LythonKnownCallableSignatures.TypingNamedTuple, "LA3151", "typing.NamedTuple(typename[, fields]) expects at least one argument."),
        new(LythonKnownCallableSignatures.TypingTypedDict, "LA3151", "typing.TypedDict(typename[, fields]) expects at least one argument."),
        new(LythonKnownCallableSignatures.SubprocessRun, "LA3151", "subprocess.run(args, ...) expects one command and supported subprocess options.", StaticReturnShape.SubprocessCompletedProcess),
        new(LythonKnownCallableSignatures.SubprocessCall, "LA3151", "subprocess.call(args, ...) expects one command and supported subprocess options.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.SubprocessCheckCall, "LA3151", "subprocess.check_call(args, ...) expects one command and supported subprocess options.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.SubprocessCheckOutput, "LA3151", "subprocess.check_output(args, ...) expects one command and supported subprocess options.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.SubprocessCompletedProcess, "LA3151", "subprocess.CompletedProcess(args, returncode, stdout=None, stderr=None) expects args and returncode.", StaticReturnShape.SubprocessCompletedProcess),
        new(LythonKnownCallableSignatures.SubprocessList2Cmdline, "LA3151", "subprocess.list2cmdline(seq) expects one iterable of strings.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.SubprocessUnsupported, "LA3151", "This subprocess helper is not supported by Lython."),
        new(LythonKnownCallableSignatures.OsListDir, "LA3151", "os.listdir([path]) expects zero or one argument.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.OsWalk, "LA3151", "os.walk([top][, topdown][, onerror][, followlinks]) expects zero to four arguments."),
        new(LythonKnownCallableSignatures.OsGetCwd, "LA3151", "os.getcwd() expects no arguments.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsFspath, "LA3151", "os.fspath(path) expects one path-like argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsFsEncode, "LA3151", "os.fsencode(filename) expects one path-like argument."),
        new(LythonKnownCallableSignatures.OsFsDecode, "LA3151", "os.fsdecode(filename) expects one path-like argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsGetEnv, "LA3151", "os.getenv(key[, default]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.OsPutEnv, "LA3151", "os.putenv(key, value) expects two arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsUnsetEnv, "LA3151", "os.unsetenv(key) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsGetExecPath, "LA3151", "os.get_exec_path([env]) expects zero or one argument.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.OsStat, "LA3151", "os.stat(path) expects one path-like argument."),
        new(LythonKnownCallableSignatures.OsLstat, "LA3151", "os.lstat(path) expects one path-like argument."),
        new(LythonKnownCallableSignatures.OsScandir, "LA3151", "os.scandir([path]) expects zero or one path-like argument."),
        new(LythonKnownCallableSignatures.OsMkdir, "LA3151", "os.mkdir(path) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsMakedirs, "LA3151", "os.makedirs(path[, exist_ok]) expects one or two arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsRemove, "LA3151", "os.remove(path) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsUnlink, "LA3151", "os.unlink(path) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsRename, "LA3151", "os.rename(src, dst) expects two arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsReplace, "LA3151", "os.replace(src, dst) expects two arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsRmdir, "LA3151", "os.rmdir(path) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsRemovedirs, "LA3151", "os.removedirs(path) expects one argument.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.OsPathJoin, "LA3151", "os.path.join(path, *paths) expects one or more arguments.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathSplit, "LA3151", "os.path.split(path) expects one argument."),
        new(LythonKnownCallableSignatures.OsPathSplitExt, "LA3151", "os.path.splitext(path) expects one argument."),
        new(LythonKnownCallableSignatures.OsPathBasename, "LA3151", "os.path.basename(path) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathDirname, "LA3151", "os.path.dirname(path) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathIsAbs, "LA3151", "os.path.isabs(path) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OsPathNormPath, "LA3151", "os.path.normpath(path) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathNormCase, "LA3151", "os.path.normcase(path) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathAbsPath, "LA3151", "os.path.abspath(path) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathRelPath, "LA3151", "os.path.relpath(path[, start]) expects one or two arguments.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathCommonPath, "LA3151", "os.path.commonpath(paths) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathCommonPrefix, "LA3151", "os.path.commonprefix(list) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathExists, "LA3151", "os.path.exists(path) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OsPathLexists, "LA3151", "os.path.lexists(path) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OsPathIsFile, "LA3151", "os.path.isfile(path) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OsPathIsDir, "LA3151", "os.path.isdir(path) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OsPathGetSize, "LA3151", "os.path.getsize(path) expects one argument.", StaticReturnShape.Integer),
        new(LythonKnownCallableSignatures.OsPathGetMTime, "LA3151", "os.path.getmtime(path) expects one argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.OsPathGetATime, "LA3151", "os.path.getatime(path) expects one argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.OsPathGetCTime, "LA3151", "os.path.getctime(path) expects one argument.", StaticReturnShape.Float),
        new(LythonKnownCallableSignatures.OsPathSameFile, "LA3151", "os.path.samefile(path1, path2) expects two arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.OsPathRealPath, "LA3151", "os.path.realpath(path) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathExpandVars, "LA3151", "os.path.expandvars(path) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.OsPathSplitDrive, "LA3151", "os.path.splitdrive(path) expects one argument."),
        new(LythonKnownCallableSignatures.OsPathSplitRoot, "LA3151", "os.path.splitroot(path) expects one argument."),
        new(LythonKnownCallableSignatures.OsPathIsMount, "LA3151", "os.path.ismount(path) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.ShutilCopyFile, "LA3151", "shutil.copyfile(src, dst, *, follow_symlinks=True) expects two path-like arguments plus supported keyword options.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.ShutilCopy, "LA3151", "shutil.copy(src, dst, *, follow_symlinks=True) expects two path-like arguments plus supported keyword options.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.ShutilCopy2, "LA3151", "shutil.copy2(src, dst, *, follow_symlinks=True) is not supported by Lython because metadata preservation is outside the host contract."),
        new(LythonKnownCallableSignatures.ShutilMove, "LA3151", "shutil.move(src, dst, copy_function=copy) expects two path-like arguments; custom copy_function is not supported.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.ShutilCopyFileObj, "LA3151", "shutil.copyfileobj(fsrc, fdst, length=0) expects source and destination text file-like objects.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.Glob, "LA3151", "glob.glob(pathname, *, root_dir=None, dir_fd=None, recursive=False, include_hidden=False) expects one path-like argument plus supported keyword options.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.IGlob, "LA3151", "glob.iglob(pathname, *, root_dir=None, dir_fd=None, recursive=False, include_hidden=False) expects one path-like argument plus supported keyword options."),
        new(LythonKnownCallableSignatures.GlobEscape, "LA3151", "glob.escape(pathname) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.GlobHasMagic, "LA3151", "glob.has_magic(s) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.GlobTranslate, "LA3151", "glob.translate(pathname, *, recursive=False, include_hidden=False, seps=None) expects one path-like argument plus supported keyword options.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.Glob0, "LA3151", "glob.glob0(...) is not supported by Lython; use glob.glob()."),
        new(LythonKnownCallableSignatures.Glob1, "LA3151", "glob.glob1(...) is not supported by Lython; use glob.glob()."),
        new(LythonKnownCallableSignatures.FnMatch, "LA3151", "fnmatch.fnmatch(name, pattern) expects two arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.FnMatchCase, "LA3151", "fnmatch.fnmatchcase(name, pattern) expects two arguments.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.FnMatchFilter, "LA3151", "fnmatch.filter(names, pattern) expects two arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.FnMatchTranslate, "LA3151", "fnmatch.translate(pattern) expects one argument.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.DifflibIsLineJunk, "LA3151", "difflib.IS_LINE_JUNK(line) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.DifflibIsCharacterJunk, "LA3151", "difflib.IS_CHARACTER_JUNK(ch) expects one argument.", StaticReturnShape.Boolean),
        new(LythonKnownCallableSignatures.DifflibUnifiedDiff, "LA3151", "difflib.unified_diff(a, b[, fromfile][, tofile][, fromfiledate][, tofiledate][, n][, lineterm]) expects two to eight arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.DifflibContextDiff, "LA3151", "difflib.context_diff(a, b[, fromfile][, tofile][, fromfiledate][, tofiledate][, n][, lineterm]) expects two to eight arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.DifflibNdiff, "LA3151", "difflib.ndiff(a, b[, linejunk][, charjunk]) expects two to four arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.DifflibRestore, "LA3151", "difflib.restore(delta, which) expects two arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.DifflibGetCloseMatches, "LA3151", "difflib.get_close_matches(word, possibilities[, n][, cutoff]) expects two to four arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.DifflibDiffBytes, "LA3151", "difflib.diff_bytes(dfunc, a, b[, fromfile][, tofile][, fromfiledate][, tofiledate][, n][, lineterm]) expects three to nine arguments.", StaticReturnShape.ListOfBytes),
        new(LythonKnownCallableSignatures.DifflibDiffer, "LA3151", "difflib.Differ([linejunk][, charjunk]) expects zero to two arguments.", StaticReturnShape.DifflibDiffer),
        new(LythonKnownCallableSignatures.DifflibHtmlDiff, "LA3151", "difflib.HtmlDiff([tabsize][, wrapcolumn][, linejunk][, charjunk]) expects zero to four arguments.", StaticReturnShape.DifflibHtmlDiff),
        new(LythonKnownCallableSignatures.DifflibSequenceMatcher, "LA3151", "difflib.SequenceMatcher([isjunk][, a][, b][, autojunk]) expects zero to four arguments.", StaticReturnShape.DifflibSequenceMatcher),
        new(LythonKnownCallableSignatures.PkgutilModuleInfo, "LA3151", "pkgutil.ModuleInfo(module_finder, name, ispkg) expects three arguments.", StaticReturnShape.PkgutilModuleInfo),
        new(LythonKnownCallableSignatures.PkgutilIterModules, "LA3151", "pkgutil.iter_modules([path][, prefix]) expects zero to two arguments.", StaticReturnShape.ListOfPkgutilModuleInfo),
        new(LythonKnownCallableSignatures.PkgutilWalkPackages, "LA3151", "pkgutil.walk_packages([path][, prefix][, onerror]) expects zero to three arguments.", StaticReturnShape.ListOfPkgutilModuleInfo),
        new(LythonKnownCallableSignatures.PkgutilFindLoader, "LA3151", "pkgutil.find_loader(fullname) expects one argument.", StaticReturnShape.PkgutilLoader),
        new(LythonKnownCallableSignatures.PkgutilGetLoader, "LA3151", "pkgutil.get_loader(module_or_name) expects one argument.", StaticReturnShape.PkgutilLoader),
        new(LythonKnownCallableSignatures.PkgutilExtendPath, "LA3151", "pkgutil.extend_path(path, name) expects two arguments.", StaticReturnShape.ListOfString),
        new(LythonKnownCallableSignatures.PkgutilResolveName, "LA3151", "pkgutil.resolve_name(name) expects one argument."),
        new(LythonKnownCallableSignatures.PkgutilGetImporter, "LA3151", "pkgutil.get_importer(path_item) expects one argument."),
        new(LythonKnownCallableSignatures.PkgutilIterImporters, "LA3151", "pkgutil.iter_importers([fullname]) expects zero or one argument.", StaticReturnShape.ListOfUnknown),
        new(LythonKnownCallableSignatures.PkgutilIterImporterModules, "LA3151", "pkgutil.iter_importer_modules(importer[, prefix]) expects one or two arguments.", StaticReturnShape.ListOfPkgutilModuleInfo),
        new(LythonKnownCallableSignatures.PkgutilIterZipimportModules, "LA3151", "pkgutil.iter_zipimport_modules(importer[, prefix]) expects one or two arguments.", StaticReturnShape.ListOfPkgutilModuleInfo),
        new(LythonKnownCallableSignatures.PkgutilGetData, "LA3151", "pkgutil.get_data(package, resource) expects two arguments."),
        new(LythonKnownCallableSignatures.PkgutilReadCode, "LA3151", "pkgutil.read_code(stream) expects one argument."),
        new(LythonKnownCallableSignatures.ImportlibImportModule, "LA3151", "importlib.import_module(name[, package]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.ImportlibInvalidateCaches, "LA3151", "importlib.invalidate_caches() expects no arguments.", StaticReturnShape.None),
        new(LythonKnownCallableSignatures.ImportlibUtilFindSpec, "LA3151", "importlib.util.find_spec(name[, package]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.ImportlibUtilResolveName, "LA3151", "importlib.util.resolve_name(name, package) expects two arguments.", StaticReturnShape.String),
        new(LythonKnownCallableSignatures.ImportlibUtilModuleFromSpec, "LA3151", "importlib.util.module_from_spec(spec) expects one argument."),
        new(LythonKnownCallableSignatures.ImportlibUtilSpecFromFileLocation, "LA3151", "importlib.util.spec_from_file_location(name, location, *, loader=None, submodule_search_locations=None) expects two positional arguments."),
        new(LythonKnownCallableSignatures.ImportlibUtilSpecFromLoader, "LA3151", "importlib.util.spec_from_loader(name, loader, *, origin=None, is_package=None) expects two positional arguments."),
        new(LythonKnownCallableSignatures.ItertoolsChain, "LA3151", "itertools.chain(*iterables) expects positional iterable arguments."),
        new(LythonKnownCallableSignatures.ItertoolsCount, "LA3151", "itertools.count([start][, step]) expects zero to two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsRepeat, "LA3151", "itertools.repeat(object[, times]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsCycle, "LA3151", "itertools.cycle(iterable) expects one argument."),
        new(LythonKnownCallableSignatures.ItertoolsIslice, "LA3151", "itertools.islice(iterable, stop) or islice(iterable, start, stop[, step]) expects two to four arguments."),
        new(LythonKnownCallableSignatures.ItertoolsCombinations, "LA3151", "itertools.combinations(iterable, r) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsCombinationsWithReplacement, "LA3151", "itertools.combinations_with_replacement(iterable, r) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsPermutations, "LA3151", "itertools.permutations(iterable[, r]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsAccumulate, "LA3151", "itertools.accumulate(iterable[, func], *, initial=None) expects supported arguments."),
        new(LythonKnownCallableSignatures.ItertoolsCompress, "LA3151", "itertools.compress(data, selectors) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsFilterFalse, "LA3151", "itertools.filterfalse(function, iterable) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsDropWhile, "LA3151", "itertools.dropwhile(predicate, iterable) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsTakeWhile, "LA3151", "itertools.takewhile(predicate, iterable) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsStarmap, "LA3151", "itertools.starmap(function, iterable) expects two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsPairwise, "LA3151", "itertools.pairwise(iterable) expects one argument."),
        new(LythonKnownCallableSignatures.ItertoolsGroupBy, "LA3151", "itertools.groupby(iterable[, key]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsTee, "LA3151", "itertools.tee(iterable[, n]) expects one or two arguments."),
        new(LythonKnownCallableSignatures.ItertoolsBatched, "LA3151", "itertools.batched(iterable, n, *, strict=False) expects supported arguments."),
    ];

    public static bool TryGetKnownCallContract(string targetName, out StaticKnownCallContract contract)
    {
        foreach (var candidate in KnownCallContracts)
        {
            if (string.Equals(candidate.TargetName, targetName, StringComparison.Ordinal))
            {
                contract = candidate;
                return true;
            }
        }

        contract = default;
        return false;
    }

    public static bool TryGetKnownCallReturn(string targetName, LythonSourceSpan span, out AbstractValue value)
    {
        if (TryGetKnownCallContract(targetName, out var contract) &&
            contract.ReturnShape != StaticReturnShape.Unknown)
        {
            value = CreateReturnValue(contract.ReturnShape, span);
            return true;
        }

        value = default;
        return false;
    }
}
