using Lokad.Lython.Runtime;

namespace Lokad.Lython.Frontend;

internal static partial class StaticContracts
{
    private static class LibraryCallableContractCatalog
    {
        public static readonly StaticCallableContract[] Contracts =
        [
        new(AbstractValueKind.DateTimeTimedelta, "total_seconds", 0, 0, "LA3162", "timedelta.total_seconds() expects no arguments."),
        new(AbstractValueKind.DateTimeDate, "weekday", 0, 0, "LA3162", "date.weekday() expects no arguments."),
        new(AbstractValueKind.DateTimeDate, "isoweekday", 0, 0, "LA3162", "date.isoweekday() expects no arguments."),
        new(AbstractValueKind.DateTimeDate, "isocalendar", 0, 0, "LA3162", "date.isocalendar() expects no arguments."),
        new(AbstractValueKind.DateTimeDate, "toordinal", 0, 0, "LA3162", "date.toordinal() expects no arguments."),
        new(AbstractValueKind.DateTimeDate, "timetuple", 0, 0, "LA3162", "date.timetuple() expects no arguments."),
        new(AbstractValueKind.DateTimeDate, "ctime", 0, 0, "LA3162", "date.ctime() expects no arguments."),
        new(AbstractValueKind.DateTimeDate, "isoformat", 0, 0, "LA3162", "date.isoformat() expects no arguments."),
        new(AbstractValueKind.DateTimeDate, "__format__", 1, 1, "LA3162", "date.__format__(format_spec) expects one argument.", parameterNames: ["format_spec"]),
        new(AbstractValueKind.DateTimeDate, "strftime", 1, 1, "LA3162", "date.strftime(format) expects one argument.", parameterNames: ["format"]),
        new(AbstractValueKind.DateTimeDate, "replace", 0, 3, "LA3162", "date.replace([year][, month][, day]) expects supported date fields.", parameterNames: ["year", "month", "day"]),
        new(AbstractValueKind.DateTimeTime, "utcoffset", 0, 0, "LA3162", "time.utcoffset() expects no arguments."),
        new(AbstractValueKind.DateTimeTime, "tzname", 0, 0, "LA3162", "time.tzname() expects no arguments."),
        new(AbstractValueKind.DateTimeTime, "dst", 0, 0, "LA3162", "time.dst() expects no arguments."),
        new(AbstractValueKind.DateTimeTime, "isoformat", 0, 1, "LA3162", "time.isoformat([timespec]) expects zero or one argument.", parameterNames: ["timespec"]),
        new(AbstractValueKind.DateTimeTime, "__format__", 1, 1, "LA3162", "time.__format__(format_spec) expects one argument.", parameterNames: ["format_spec"]),
        new(AbstractValueKind.DateTimeTime, "strftime", 1, 1, "LA3162", "time.strftime(format) expects one argument.", parameterNames: ["format"]),
        new(AbstractValueKind.DateTimeTime, "replace", 0, 6, "LA3162", "time.replace([hour][, minute][, second][, microsecond][, tzinfo][, fold]) expects supported fields.", parameterNames: ["hour", "minute", "second", "microsecond", "tzinfo", "fold"]),
        new(AbstractValueKind.DateTimeDateTime, "date", 0, 0, "LA3162", "datetime.date() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "time", 0, 0, "LA3162", "datetime.time() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "timetz", 0, 0, "LA3162", "datetime.timetz() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "weekday", 0, 0, "LA3162", "datetime.weekday() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "isoweekday", 0, 0, "LA3162", "datetime.isoweekday() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "isocalendar", 0, 0, "LA3162", "datetime.isocalendar() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "toordinal", 0, 0, "LA3162", "datetime.toordinal() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "timetuple", 0, 0, "LA3162", "datetime.timetuple() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "utctimetuple", 0, 0, "LA3162", "datetime.utctimetuple() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "ctime", 0, 0, "LA3162", "datetime.ctime() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "timestamp", 0, 0, "LA3162", "datetime.timestamp() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "utcoffset", 0, 0, "LA3162", "datetime.utcoffset() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "tzname", 0, 0, "LA3162", "datetime.tzname() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "dst", 0, 0, "LA3162", "datetime.dst() expects no arguments."),
        new(AbstractValueKind.DateTimeDateTime, "astimezone", 0, 1, "LA3162", "datetime.astimezone([tz]) expects zero or one argument.", parameterNames: ["tz"]),
        new(AbstractValueKind.DateTimeDateTime, "isoformat", 0, 2, "LA3162", "datetime.isoformat([sep][, timespec]) expects zero to two arguments.", parameterNames: ["sep", "timespec"]),
        new(AbstractValueKind.DateTimeDateTime, "__format__", 1, 1, "LA3162", "datetime.__format__(format_spec) expects one argument.", parameterNames: ["format_spec"]),
        new(AbstractValueKind.DateTimeDateTime, "strftime", 1, 1, "LA3162", "datetime.strftime(format) expects one argument.", parameterNames: ["format"]),
        new(AbstractValueKind.DateTimeDateTime, "replace", 0, 9, "LA3162", "datetime.replace([year][, month][, day][, hour][, minute][, second][, microsecond][, tzinfo][, fold]) expects supported fields.", parameterNames: ["year", "month", "day", "hour", "minute", "second", "microsecond", "tzinfo", "fold"]),
        new(AbstractValueKind.DateTimeTimezone, "utcoffset", 1, 1, "LA3162", "timezone.utcoffset(dt) expects one argument.", parameterNames: ["dt"]),
        new(AbstractValueKind.DateTimeTimezone, "tzname", 1, 1, "LA3162", "timezone.tzname(dt) expects one argument.", parameterNames: ["dt"]),
        new(AbstractValueKind.DateTimeTimezone, "dst", 1, 1, "LA3162", "timezone.dst(dt) expects one argument.", parameterNames: ["dt"]),
        new(AbstractValueKind.StatisticsLinearRegression, "_asdict", 0, 0, "LA3163", "LinearRegression._asdict() expects no arguments."),
        new(AbstractValueKind.StatisticsLinearRegression, "_replace", 0, 2, "LA3163", "LinearRegression._replace([slope][, intercept]) expects zero to two field values.", parameterNames: ["slope", "intercept"]),
        new(AbstractValueKind.StatisticsLinearRegression, "count", 1, 1, "LA3163", "LinearRegression.count(value) expects one argument.", parameterNames: ["value"]),
        new(AbstractValueKind.StatisticsLinearRegression, "index", 1, 3, "LA3163", "LinearRegression.index(value[, start[, stop]]) expects one to three arguments.", parameterNames: ["value", "start", "stop"]),
        new(AbstractValueKind.StatisticsNormalDist, "zscore", 1, 1, "LA3163", "NormalDist.zscore(x) expects one argument.", parameterNames: ["x"]),
        new(AbstractValueKind.StatisticsNormalDist, "pdf", 1, 1, "LA3163", "NormalDist.pdf(x) expects one argument.", parameterNames: ["x"]),
        new(AbstractValueKind.StatisticsNormalDist, "cdf", 1, 1, "LA3163", "NormalDist.cdf(x) expects one argument.", parameterNames: ["x"]),
        new(AbstractValueKind.StatisticsNormalDist, "inv_cdf", 1, 1, "LA3163", "NormalDist.inv_cdf(p) expects one argument.", parameterNames: ["p"]),
        new(AbstractValueKind.StatisticsNormalDist, "overlap", 1, 1, "LA3163", "NormalDist.overlap(other) expects one NormalDist argument.", parameterNames: ["other"]),
        new(AbstractValueKind.StatisticsNormalDist, "quantiles", 0, 1, "LA3163", "NormalDist.quantiles([n]) expects zero or one argument.", parameterNames: ["n"]),
        new(AbstractValueKind.StatisticsNormalDist, "samples", 1, 2, "LA3163", "NormalDist.samples(n[, seed]) expects one or two arguments.", parameterNames: ["n", "seed"]),
        new(AbstractValueKind.Random, "seed", 0, 2, "LA3164", "Random.seed(a=None, version=2) expects zero to two arguments.", parameterNames: ["a", "version"]),
        new(AbstractValueKind.Random, "random", 0, 0, "LA3164", "Random.random() expects no arguments."),
        new(AbstractValueKind.Random, "getstate", 0, 0, "LA3164", "Random.getstate() expects no arguments."),
        new(AbstractValueKind.Random, "setstate", 1, 1, "LA3164", "Random.setstate(state) expects one argument.", parameterNames: ["state"]),
        new(AbstractValueKind.Random, "randrange", 1, 3, "LA3164", "Random.randrange(start, stop=None, step=1) expects one to three arguments.", parameterNames: ["start", "stop", "step"]),
        new(AbstractValueKind.Random, "randint", 2, 2, "LA3164", "Random.randint(a, b) expects two arguments.", parameterNames: ["a", "b"]),
        new(AbstractValueKind.Random, "choice", 1, 1, "LA3164", "Random.choice(seq) expects one argument.", parameterNames: ["seq"]),
        new(AbstractValueKind.Random, "choices", 1, 4, "LA3164", "Random.choices(population, weights=None, cum_weights=None, k=1) expects supported arguments.", parameterNames: ["population", "weights", "cum_weights", "k"]),
        new(AbstractValueKind.Random, "shuffle", 1, 1, "LA3164", "Random.shuffle(x) expects one argument.", StaticMutationKind.MutatesReceiver, ["x"]),
        new(AbstractValueKind.Random, "sample", 2, 3, "LA3164", "Random.sample(population, k, *, counts=None) expects two arguments plus optional counts.", parameterNames: ["population", "k", "counts"]),
        new(AbstractValueKind.Random, "getrandbits", 1, 1, "LA3164", "Random.getrandbits(k) expects one argument.", parameterNames: ["k"]),
        new(AbstractValueKind.Random, "randbytes", 1, 1, "LA3164", "Random.randbytes(n) expects one argument.", parameterNames: ["n"]),
        new(AbstractValueKind.Random, "uniform", 2, 2, "LA3164", "Random.uniform(a, b) expects two arguments.", parameterNames: ["a", "b"]),
        new(AbstractValueKind.Random, "triangular", 0, 3, "LA3164", "Random.triangular(low=0.0, high=1.0, mode=None) expects zero to three arguments.", parameterNames: ["low", "high", "mode"]),
        new(AbstractValueKind.Random, "betavariate", 2, 2, "LA3164", "Random.betavariate(alpha, beta) expects two arguments.", parameterNames: ["alpha", "beta"]),
        new(AbstractValueKind.Random, "expovariate", 0, 1, "LA3164", "Random.expovariate(lambd=1.0) expects zero or one argument.", parameterNames: ["lambd"]),
        new(AbstractValueKind.Random, "gammavariate", 2, 2, "LA3164", "Random.gammavariate(alpha, beta) expects two arguments.", parameterNames: ["alpha", "beta"]),
        new(AbstractValueKind.Random, "gauss", 0, 2, "LA3164", "Random.gauss(mu=0.0, sigma=1.0) expects zero to two arguments.", parameterNames: ["mu", "sigma"]),
        new(AbstractValueKind.Random, "normalvariate", 0, 2, "LA3164", "Random.normalvariate(mu=0.0, sigma=1.0) expects zero to two arguments.", parameterNames: ["mu", "sigma"]),
        new(AbstractValueKind.Random, "lognormvariate", 2, 2, "LA3164", "Random.lognormvariate(mu, sigma) expects two arguments.", parameterNames: ["mu", "sigma"]),
        new(AbstractValueKind.Random, "paretovariate", 1, 1, "LA3164", "Random.paretovariate(alpha) expects one argument.", parameterNames: ["alpha"]),
        new(AbstractValueKind.Random, "vonmisesvariate", 2, 2, "LA3164", "Random.vonmisesvariate(mu, kappa) expects two arguments.", parameterNames: ["mu", "kappa"]),
        new(AbstractValueKind.Random, "weibullvariate", 2, 2, "LA3164", "Random.weibullvariate(alpha, beta) expects two arguments.", parameterNames: ["alpha", "beta"]),
        new(AbstractValueKind.DifflibDiffer, "compare", 2, 2, "LA3156", "Differ.compare(a, b) expects two arguments.", parameterNames: ["a", "b"]),
        new(AbstractValueKind.DifflibHtmlDiff, "make_table", 2, 6, "LA3156", "HtmlDiff.make_table(fromlines, tolines[, fromdesc][, todesc][, context][, numlines]) expects two to six arguments.", parameterNames: ["fromlines", "tolines", "fromdesc", "todesc", "context", "numlines"]),
        new(AbstractValueKind.DifflibHtmlDiff, "make_file", 2, 7, "LA3156", "HtmlDiff.make_file(fromlines, tolines[, fromdesc][, todesc][, context][, numlines][, charset]) expects two to seven arguments.", parameterNames: ["fromlines", "tolines", "fromdesc", "todesc", "context", "numlines", "charset"]),
        new(AbstractValueKind.DifflibSequenceMatcher, "set_seqs", 2, 2, "LA3156", "SequenceMatcher.set_seqs(a, b) expects two arguments.", StaticMutationKind.MutatesReceiver, ["a", "b"]),
        new(AbstractValueKind.DifflibSequenceMatcher, "set_seq1", 1, 1, "LA3156", "SequenceMatcher.set_seq1(a) expects one argument.", StaticMutationKind.MutatesReceiver, ["a"]),
        new(AbstractValueKind.DifflibSequenceMatcher, "set_seq2", 1, 1, "LA3156", "SequenceMatcher.set_seq2(b) expects one argument.", StaticMutationKind.MutatesReceiver, ["b"]),
        new(AbstractValueKind.DifflibSequenceMatcher, "find_longest_match", 0, 4, "LA3156", "SequenceMatcher.find_longest_match([alo][, ahi][, blo][, bhi]) expects zero to four arguments.", parameterNames: ["alo", "ahi", "blo", "bhi"]),
        new(AbstractValueKind.DifflibSequenceMatcher, "get_matching_blocks", 0, 0, "LA3156", "SequenceMatcher.get_matching_blocks() expects no arguments."),
        new(AbstractValueKind.DifflibSequenceMatcher, "get_opcodes", 0, 0, "LA3156", "SequenceMatcher.get_opcodes() expects no arguments."),
        new(AbstractValueKind.DifflibSequenceMatcher, "get_grouped_opcodes", 0, 1, "LA3156", "SequenceMatcher.get_grouped_opcodes([n]) expects zero or one argument.", parameterNames: ["n"]),
        new(AbstractValueKind.DifflibSequenceMatcher, "ratio", 0, 0, "LA3156", "SequenceMatcher.ratio() expects no arguments."),
        new(AbstractValueKind.DifflibSequenceMatcher, "quick_ratio", 0, 0, "LA3156", "SequenceMatcher.quick_ratio() expects no arguments."),
        new(AbstractValueKind.DifflibSequenceMatcher, "real_quick_ratio", 0, 0, "LA3156", "SequenceMatcher.real_quick_ratio() expects no arguments."),
        new(AbstractValueKind.PkgutilModuleInfo, "_asdict", 0, 0, "LA3156", "ModuleInfo._asdict() expects no arguments."),
        new(AbstractValueKind.PkgutilModuleInfo, "_replace", 0, 3, "LA3156", "ModuleInfo._replace([module_finder][, name][, ispkg]) expects zero to three field values.", parameterNames: ["module_finder", "name", "ispkg"]),
        new(AbstractValueKind.PkgutilModuleInfo, "count", 1, 1, "LA3156", "ModuleInfo.count(value) expects one argument.", parameterNames: ["value"]),
        new(AbstractValueKind.PkgutilModuleInfo, "index", 1, 3, "LA3156", "ModuleInfo.index(value[, start[, stop]]) expects one to three arguments.", parameterNames: ["value", "start", "stop"]),
        new(AbstractValueKind.PkgutilLoader, "is_package", 0, 1, "LA3156", "loader.is_package([fullname]) expects zero or one argument.", parameterNames: ["fullname"]),
        new(AbstractValueKind.PkgutilLoader, "get_source", 0, 1, "LA3156", "loader.get_source([fullname]) expects zero or one argument.", parameterNames: ["fullname"]),
        new(AbstractValueKind.SubprocessCompletedProcess, "check_returncode", 0, 0, "LA3160", "CompletedProcess.check_returncode() expects no arguments."),
        new(AbstractValueKind.SubprocessPopen, "communicate", 0, 2, "LA3160", "Popen.communicate([input][, timeout]) expects zero to two arguments.", parameterNames: ["input", "timeout"]),
        new(AbstractValueKind.SubprocessPopen, "wait", 0, 1, "LA3160", "Popen.wait([timeout]) expects zero or one argument.", parameterNames: ["timeout"]),
        new(AbstractValueKind.SubprocessPopen, "poll", 0, 0, "LA3160", "Popen.poll() expects no arguments."),
        new(AbstractValueKind.SubprocessPopen, "send_signal", 1, 1, "LA3160", "Popen.send_signal(signal) expects one argument.", parameterNames: ["signal"]),
        new(AbstractValueKind.SubprocessPopen, "terminate", 0, 0, "LA3160", "Popen.terminate() expects no arguments."),
        new(AbstractValueKind.SubprocessPopen, "kill", 0, 0, "LA3160", "Popen.kill() expects no arguments."),
        ];
    }
}
