<Project>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.6" />
    <PackageVersion Include="Lokad.Parsing" Version="1.1.0" />
    <PackageVersion Include="Lokad.Utf8Regex.PythonRe" Version="0.2.0" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
