<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../benchmarks/Lokad.Lython.Benchmarks/Comparison/OwnedWorkerProcess.cs" Link="OwnedWorkerProcess.cs" />
  </ItemGroup>
</Project>
