using Lokad.Lython.Tests.Harness;

namespace Lokad.Lython.PublicApi.Tests;

public sealed class AsciiCodecCompatibilityTests
{
    public static IEnumerable<object[]> PythonControls()
    {
        yield return new object[] { "ascii-aliases-and-native-roundtrip", "for name in ['ascii', '646', 'ansi_x3.4_1968', 'ansi_x3.4_1986', 'ansi_x3_4_1968', 'cp367', 'csascii', 'ibm367', 'iso646_us', 'iso_646.irv_1991', 'iso_ir_6', 'us', 'us_ascii']:\n    value=bytes(range(128))\n    text=value.decode(name)\n    print(text.encode(name)==value,str(value,name)==text,bytes(text,name)==value,len(text))\n", "True True True 128\nTrue True True 128\nTrue True True 128\nTrue True True 128\nTrue True True 128\nTrue True True 128\nTrue True True 128\nTrue True True 128\nTrue True True 128\nTrue True True 128\nTrue True True 128\nTrue True True 128\nTrue True True 128\n" };
        yield return new object[] { "ascii-encode-handlers-and-scalar-width", "for source in ['', 'plain\\r\\n\u00e9\\t\u20ac\ud83d\ude00\\x00', '\u00e9\u00ff', '\u20ac\ud83d\ude00']:\n    for errors in ['strict','ignore','replace','backslashreplace']:\n        try:\n            print(repr(source.encode('ascii',errors)))\n            print(repr(bytes(source,'US-ASCII',errors)))\n        except Exception as e:\n            print(type(e).__name__)\n", "b''\nb''\nb''\nb''\nb''\nb''\nb''\nb''\nUnicodeEncodeError\nb'plain\\r\\n\\t\\x00'\nb'plain\\r\\n\\t\\x00'\nb'plain\\r\\n?\\t??\\x00'\nb'plain\\r\\n?\\t??\\x00'\nb'plain\\r\\n\\\\xe9\\t\\\\u20ac\\\\U0001f600\\x00'\nb'plain\\r\\n\\\\xe9\\t\\\\u20ac\\\\U0001f600\\x00'\nUnicodeEncodeError\nb''\nb''\nb'??'\nb'??'\nb'\\\\xe9\\\\xff'\nb'\\\\xe9\\\\xff'\nUnicodeEncodeError\nb''\nb''\nb'??'\nb'??'\nb'\\\\u20ac\\\\U0001f600'\nb'\\\\u20ac\\\\U0001f600'\n" };
        yield return new object[] { "ascii-decode-all-bytes-and-handlers", "value=bytes(range(256))\nfor errors in ['strict','ignore','replace','backslashreplace']:\n    try:\n        print(repr(value.decode('ascii',errors)))\n        print(str(value,'ascii',errors)==value.decode('ascii',errors))\n    except Exception as e:\n        print(type(e).__name__)\n", "UnicodeDecodeError\n'\\x00\\x01\\x02\\x03\\x04\\x05\\x06\\x07\\x08\\t\\n\\x0b\\x0c\\r\\x0e\\x0f\\x10\\x11\\x12\\x13\\x14\\x15\\x16\\x17\\x18\\x19\\x1a\\x1b\\x1c\\x1d\\x1e\\x1f !\"#$%&\\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\\x7f'\nTrue\n'\\x00\\x01\\x02\\x03\\x04\\x05\\x06\\x07\\x08\\t\\n\\x0b\\x0c\\r\\x0e\\x0f\\x10\\x11\\x12\\x13\\x14\\x15\\x16\\x17\\x18\\x19\\x1a\\x1b\\x1c\\x1d\\x1e\\x1f !\"#$%&\\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\\x7f\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd'\nTrue\n'\\x00\\x01\\x02\\x03\\x04\\x05\\x06\\x07\\x08\\t\\n\\x0b\\x0c\\r\\x0e\\x0f\\x10\\x11\\x12\\x13\\x14\\x15\\x16\\x17\\x18\\x19\\x1a\\x1b\\x1c\\x1d\\x1e\\x1f !\"#$%&\\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\\\]^_`abcdefghijklmnopqrstuvwxyz{|}~\\x7f\\\\x80\\\\x81\\\\x82\\\\x83\\\\x84\\\\x85\\\\x86\\\\x87\\\\x88\\\\x89\\\\x8a\\\\x8b\\\\x8c\\\\x8d\\\\x8e\\\\x8f\\\\x90\\\\x91\\\\x92\\\\x93\\\\x94\\\\x95\\\\x96\\\\x97\\\\x98\\\\x99\\\\x9a\\\\x9b\\\\x9c\\\\x9d\\\\x9e\\\\x9f\\\\xa0\\\\xa1\\\\xa2\\\\xa3\\\\xa4\\\\xa5\\\\xa6\\\\xa7\\\\xa8\\\\xa9\\\\xaa\\\\xab\\\\xac\\\\xad\\\\xae\\\\xaf\\\\xb0\\\\xb1\\\\xb2\\\\xb3\\\\xb4\\\\xb5\\\\xb6\\\\xb7\\\\xb8\\\\xb9\\\\xba\\\\xbb\\\\xbc\\\\xbd\\\\xbe\\\\xbf\\\\xc0\\\\xc1\\\\xc2\\\\xc3\\\\xc4\\\\xc5\\\\xc6\\\\xc7\\\\xc8\\\\xc9\\\\xca\\\\xcb\\\\xcc\\\\xcd\\\\xce\\\\xcf\\\\xd0\\\\xd1\\\\xd2\\\\xd3\\\\xd4\\\\xd5\\\\xd6\\\\xd7\\\\xd8\\\\xd9\\\\xda\\\\xdb\\\\xdc\\\\xdd\\\\xde\\\\xdf\\\\xe0\\\\xe1\\\\xe2\\\\xe3\\\\xe4\\\\xe5\\\\xe6\\\\xe7\\\\xe8\\\\xe9\\\\xea\\\\xeb\\\\xec\\\\xed\\\\xee\\\\xef\\\\xf0\\\\xf1\\\\xf2\\\\xf3\\\\xf4\\\\xf5\\\\xf6\\\\xf7\\\\xf8\\\\xf9\\\\xfa\\\\xfb\\\\xfc\\\\xfd\\\\xfe\\\\xff'\nTrue\n" };
        yield return new object[] { "ascii-bom-is-invalid-and-newlines-preserved", "for value in [b'\\xef\\xbb\\xbfabc',b'a\\r\\nb\\rc\\n',b'\\xc3\\xa9\\xff',b'\\x80']:\n    for errors in ['strict','ignore','replace','backslashreplace']:\n        try:\n            print(repr(value.decode('ascii',errors)))\n        except Exception as e:\n            print(type(e).__name__)\n", "UnicodeDecodeError\n'abc'\n'\ufffd\ufffd\ufffdabc'\n'\\\\xef\\\\xbb\\\\xbfabc'\n'a\\r\\nb\\rc\\n'\n'a\\r\\nb\\rc\\n'\n'a\\r\\nb\\rc\\n'\n'a\\r\\nb\\rc\\n'\nUnicodeDecodeError\n''\n'\ufffd\ufffd\ufffd'\n'\\\\xc3\\\\xa9\\\\xff'\nUnicodeDecodeError\n''\n'\ufffd'\n'\\\\x80'\n" };
    }

    [Theory]
    [MemberData(nameof(PythonControls))]
    public async Task MatchesPython(string name, string source, string expected)
    {
        _ = name;
        var script = new LythonEngine().Compile(source);
        Assert.True(script.IsValid, string.Join("; ", script.Diagnostics.Select(d => d.Code + ": " + d.Message)));
        foreach (var result in new[] { script.Run(new MockLythonHost()), await script.RunAsync(new MockLythonHost()) })
        {
            Assert.True(result.Success, result.Failure?.Message);
            Assert.Equal(expected, result.StandardOutput);
        }
    }
}
