using Lokad.Lython.Tests.Harness;

namespace Lokad.Lython.PublicApi.Tests;

public sealed class BytesIOTests
{
    public static IEnumerable<object[]> PythonControls()
    {
        yield return new object[] { "bytes-basic", "import io\ns=io.BytesIO(b'a\\nb\\xff')\nprint(s.tell(), s.read(1), s.readline(), list(s), s.getvalue())\ns.seek(1)\nprint(s.write(b'XY'), s.tell(), s.getvalue())", "0 b'a' b'\\n' [b'b\\xff'] b'a\\nb\\xff'\n2 3 b'aXY\\xff'\n" };
        yield return new object[] { "bytes-gap-seek-truncate", "import io\ns=io.BytesIO(b'abc')\nprint(s.seek(-10,2), s.seek(2,1), s.seek(5))\nprint(s.write(b''), s.getvalue(), s.tell())\nprint(s.write(b'x'), s.getvalue(), s.tell())\nprint(s.truncate(20), s.getvalue(), s.tell())\nprint(s.truncate(2), s.getvalue(), s.tell())", "0 2 5\n0 b'abc' 5\n1 b'abc\\x00\\x00x' 6\n20 b'abc\\x00\\x00x' 6\n2 b'ab' 6\n" };
        yield return new object[] { "bytes-iterator-identity", "import io\ns=io.BytesIO(b'a\\nb\\nc')\nprint(iter(s) is s, next(s), s.readline(), list(s), next(s,'empty'))", "True b'a\\n' b'b\\n' [b'c'] empty\n" };
        yield return new object[] { "bytes-context-close", "import io\nwith io.BytesIO(b'x') as s:\n    print(s.closed,s.readable(),s.writable(),s.seekable(),s.flush())\nprint(s.closed,s.close())\nfor call in [lambda:s.read(),lambda:s.write(b'x'),lambda:s.getvalue(),lambda:s.tell(),lambda:s.seek(0),lambda:s.truncate(),lambda:s.flush()]:\n    try:\n        call()\n    except Exception as e:\n        print(type(e).__name__)", "False True True True None\nTrue None\nValueError\nValueError\nValueError\nValueError\nValueError\nValueError\nValueError\n" };
        yield return new object[] { "bytes-readlines-hint", "import io\nfor hint in [0,1,2,3,-1]:\n    s=io.BytesIO(b'a\\nb\\nc')\n    print(hint,s.readlines(hint),s.read())", "0 [b'a\\n', b'b\\n', b'c'] b''\n1 [b'a\\n'] b'b\\nc'\n2 [b'a\\n'] b'b\\nc'\n3 [b'a\\n', b'b\\n'] b'c'\n-1 [b'a\\n', b'b\\n', b'c'] b''\n" };
        yield return new object[] { "bytes-alias-snapshot", "import io\ns=io.BytesIO(b'abc')\nv=s.getvalue()\ns.write(b'X')\nprint(v,s.getvalue())\ns.close()\nprint(v)", "b'abc' b'Xbc'\nb'abc'\n" };
        yield return new object[] { "bytes-writelines", "import io\ns=io.BytesIO()\nprint(s.writelines([b'a',b'\\n']),s.getvalue())\ntry:\n    s.writelines([b'b','wrong',b'c'])\nexcept TypeError:\n    print(s.getvalue())", "None b'a\\n'\nb'a\\nb'\n" };
        yield return new object[] { "bytes-error-io.BytesIO('x')", "import io\ntry:\n    io.BytesIO('x')\nexcept Exception as e:\n    print(type(e).__name__)", "TypeError\n" };
        yield return new object[] { "bytes-error-io.BytesIO().write('x')", "import io\ntry:\n    io.BytesIO().write('x')\nexcept Exception as e:\n    print(type(e).__name__)", "TypeError\n" };
        yield return new object[] { "bytes-error-io.BytesIO().seek(-1)", "import io\ntry:\n    io.BytesIO().seek(-1)\nexcept Exception as e:\n    print(type(e).__name__)", "ValueError\n" };
        yield return new object[] { "bytes-error-io.BytesIO().read(1.5)", "import io\ntry:\n    io.BytesIO().read(1.5)\nexcept Exception as e:\n    print(type(e).__name__)", "TypeError\n" };
        yield return new object[] { "bytes-metadata", "from io import BytesIO as B\ns=B(None)\nprint(type(s) is B,isinstance(s,B),type(B) is type,B.__name__,B.__module__,s.getvalue())\ns=B(initial_bytes=b'\\xff\\x00abc')\nprint(s.read(None),s.readline(None),s.readlines(None),s.truncate(None))", "True True True BytesIO _io b''\nb'\\xff\\x00abc' b'' [] 5\n" };
        yield return new object[] { "bytes-relative-seek", "import io\ns=io.BytesIO(b'abc')\nfor offset,whence in [(-10,1),(-10,2),(5,2),(-3,1),(0,0)]:\n    print(s.seek(offset,whence),s.tell(),s.getvalue())\nfor offset,whence in [(-1,0),(0,3),(0,2**40),(10**100,0)]:\n    try:\n        s.seek(offset,whence)\n    except Exception as e:\n        print(type(e).__name__)", "0 0 b'abc'\n0 0 b'abc'\n8 8 b'abc'\n5 5 b'abc'\n0 0 b'abc'\nValueError\nValueError\nOverflowError\nOverflowError\n" };
        yield return new object[] { "bytes-sizes", "import io\nfor size in [None,-3,-1,0,1,2,20]:\n    s=io.BytesIO(b'a\\xff\\nbc\\n')\n    print(size,s.read(size),s.tell(),s.read1(size),s.tell())", "None b'a\\xff\\nbc\\n' 6 b'' 6\n-3 b'a\\xff\\nbc\\n' 6 b'' 6\n-1 b'a\\xff\\nbc\\n' 6 b'' 6\n0 b'' 0 b'' 0\n1 b'a' 1 b'\\xff' 2\n2 b'a\\xff' 2 b'\\nb' 4\n20 b'a\\xff\\nbc\\n' 6 b'' 6\n" };
        yield return new object[] { "bytes-hint", "import io\nfor hint in [None,-1,0,1,2,3,20]:\n    s=io.BytesIO(b'a\\nb\\nc')\n    print(hint,s.readlines(hint),s.read())", "None [b'a\\n', b'b\\n', b'c'] b''\n-1 [b'a\\n', b'b\\n', b'c'] b''\n0 [b'a\\n', b'b\\n', b'c'] b''\n1 [b'a\\n'] b'b\\nc'\n2 [b'a\\n'] b'b\\nc'\n3 [b'a\\n', b'b\\n'] b'c'\n20 [b'a\\n', b'b\\n', b'c'] b''\n" };
        yield return new object[] { "bytes-closed", "import io\ns=io.BytesIO();s.close()\nprint(iter(s) is s,s.closed,s.close())\nfor call in [lambda:s.write('x'),lambda:s.read(2.3),lambda:s.read(),lambda:s.read1(),lambda:s.readline(),lambda:s.seek(2.3),lambda:s.truncate(-1),lambda:s.flush(),lambda:s.readlines(None),lambda:s.readable(),lambda:s.writable(),lambda:s.seekable(),lambda:next(s),lambda:s.getvalue(),lambda:s.tell()]:\n    try:\n        call()\n    except Exception as e:\n        print(type(e).__name__)", "True True None\nTypeError\nTypeError\nValueError\nValueError\nValueError\nTypeError\nValueError\nValueError\nValueError\nValueError\nValueError\nValueError\nValueError\nValueError\nValueError\n" };
        yield return new object[] { "bytes-keyword-errors", "import io\ndef calls(s):\n    return [lambda:s.read(size=1),lambda:s.read1(size=1),lambda:s.write(b=b'x'),lambda:s.seek(pos=0),lambda:s.truncate(size=1)]\nfor call in calls(io.BytesIO()):\n    try:\n        call()\n    except Exception as e:\n        print(type(e).__name__)", "TypeError\nTypeError\nTypeError\nTypeError\nTypeError\n" };
        yield return new object[] { "bytes-index", "import io\nclass Index:\n    def __index__(self):\n        return 2\nx=Index();x.__index__=lambda:0\ns=io.BytesIO(b'a\\xffbc\\ndef')\nprint(s.read(x),s.tell())\nprint(s.seek(x),s.readline(x))\nprint(s.truncate(x),s.getvalue())", "b'a\\xff' 2\n2 b'bc'\n2 b'a\\xff'\n" };
        yield return new object[] { "bytes-snapshots", "import io\ns=io.BytesIO(b'\\xff\\x00abc')\na=s.getvalue();s.write(b'XY');b=s.getvalue();s.truncate(1);c=s.getvalue();s.close()\nprint(a,b,c)", "b'\\xff\\x00abc' b'XYabc' b'X'\n" };
        yield return new object[] { "bytes-empty-overwrite", "import io\ns=io.BytesIO(b'abc');s.seek(7)\nprint(s.write(b''),s.getvalue(),s.tell())\nprint(s.write(b'\\xff\\x00'),s.getvalue(),s.tell())\ns.seek(2);print(s.write(b'XY'),s.getvalue(),s.tell())\nprint(s.truncate(30),s.getvalue(),s.tell())", "0 b'abc' 7\n2 b'abc\\x00\\x00\\x00\\x00\\xff\\x00' 9\n2 b'abXY\\x00\\x00\\x00\\xff\\x00' 4\n30 b'abXY\\x00\\x00\\x00\\xff\\x00' 4\n" };
        yield return new object[] { "bytes-line-size-0", "import io\ns=io.BytesIO(b'\\xff\\r\\r\\nx\\ry\\nz')\nfor _ in range(8):\n    print(s.readline(0),s.tell())", "b'' 0\nb'' 0\nb'' 0\nb'' 0\nb'' 0\nb'' 0\nb'' 0\nb'' 0\n" };
        yield return new object[] { "bytes-line-size-1", "import io\ns=io.BytesIO(b'\\xff\\r\\r\\nx\\ry\\nz')\nfor _ in range(8):\n    print(s.readline(1),s.tell())", "b'\\xff' 1\nb'\\r' 2\nb'\\r' 3\nb'\\n' 4\nb'x' 5\nb'\\r' 6\nb'y' 7\nb'\\n' 8\n" };
        yield return new object[] { "bytes-line-size-2", "import io\ns=io.BytesIO(b'\\xff\\r\\r\\nx\\ry\\nz')\nfor _ in range(8):\n    print(s.readline(2),s.tell())", "b'\\xff\\r' 2\nb'\\r\\n' 4\nb'x\\r' 6\nb'y\\n' 8\nb'z' 9\nb'' 9\nb'' 9\nb'' 9\n" };
        yield return new object[] { "bytes-line-size-3", "import io\ns=io.BytesIO(b'\\xff\\r\\r\\nx\\ry\\nz')\nfor _ in range(8):\n    print(s.readline(3),s.tell())", "b'\\xff\\r\\r' 3\nb'\\n' 4\nb'x\\ry' 7\nb'\\n' 8\nb'z' 9\nb'' 9\nb'' 9\nb'' 9\n" };
        yield return new object[] { "bytes-line-size--1", "import io\ns=io.BytesIO(b'\\xff\\r\\r\\nx\\ry\\nz')\nfor _ in range(8):\n    print(s.readline(-1),s.tell())", "b'\\xff\\r\\r\\n' 4\nb'x\\ry\\n' 8\nb'z' 9\nb'' 9\nb'' 9\nb'' 9\nb'' 9\nb'' 9\n" };
        yield return new object[] { "bytes-line-size-None", "import io\ns=io.BytesIO(b'\\xff\\r\\r\\nx\\ry\\nz')\nfor _ in range(8):\n    print(s.readline(None),s.tell())", "b'\\xff\\r\\r\\n' 4\nb'x\\ry\\n' 8\nb'z' 9\nb'' 9\nb'' 9\nb'' 9\nb'' 9\nb'' 9\n" };
        yield return new object[] { "bytes-relative-overflow", "import io\ns=io.BytesIO(b'abc')\nprint(s.seek(2**63-1),s.tell())\nfor offset in [1,2**63-1]:\n    try:\n        s.seek(offset,1)\n    except Exception as e:\n        print(type(e).__name__,s.tell(),s.getvalue())\nprint(s.seek(-2**63,1),s.tell())\nprint(s.seek(-2**63,2),s.tell())\n", "9223372036854775807 9223372036854775807\nOverflowError 9223372036854775807 b'abc'\nOverflowError 9223372036854775807 b'abc'\n0 0\n0 0\n" };
        yield return new object[] { "bytes-index-errors", "import io\nclass Missing:\n    pass\nclass Wrong:\n    def __index__(self):\n        return '2'\nclass Huge:\n    def __index__(self):\n        return 10**100\nx=Missing();x.__index__=lambda:2\ns=io.BytesIO(b'abc')\nfor value in [x,Wrong(),Huge()]:\n    for call in [lambda:s.read(value),lambda:s.seek(value),lambda:s.truncate(value),lambda:s.readlines(value)]:\n        try:\n            call()\n        except Exception as e:\n            print(type(e).__name__,s.tell())\n", "TypeError 0\nTypeError 0\nTypeError 0\nTypeError 0\nTypeError 0\nTypeError 0\nTypeError 0\nTypeError 0\nOverflowError 0\nOverflowError 0\nOverflowError 0\nTypeError 0\n" };
        yield return new object[] { "bytes-index-descriptor", "import io\nclass Base:\n    def __index__(self):\n        return 2\nclass Index(Base):\n    pass\nclass Descriptor:\n    @property\n    def __index__(self):\n        return lambda:1\ns=io.BytesIO(b'abc')\nprint(s.read(Index()),s.tell())\nprint(s.seek(Descriptor()),s.read())\n", "b'ab' 2\n1 b'bc'\n" };
        yield return new object[] { "bytes-readlines-no-index", "import io\nclass Index:\n    def __index__(self):\n        print('index-called')\n        return 2\nfor closed in [False,True]:\n    s=io.BytesIO(b'a\\nb')\n    if closed:\n        s.close()\n    for value in [Index(),10**100,-10**100]:\n        try:\n            s.readlines(value)\n        except Exception as e:\n            print(type(e).__name__)\n", "TypeError\nOverflowError\nOverflowError\nValueError\nValueError\nValueError\n" };
    }

    [Theory]
    [MemberData(nameof(PythonControls))]
    public async Task MatchesPython(string name, string source, string expected)
    {
        _ = name;
        var script = new LythonEngine().Compile(source);
        Assert.True(script.IsValid, string.Join("; ", script.Diagnostics.Select(d => d.Code + ": " + d.Message)));
        foreach (var result in new[] { script.Run(new MockLythonHost()), await script.RunAsync(new MockLythonHost()) })
        {
            Assert.True(result.Success, result.Failure?.Message);
            Assert.Equal(expected, result.StandardOutput);
        }
    }
}
