using Lokad.Lython.Tests.Harness;

namespace Lokad.Lython.PublicApi.Tests;

public sealed class GzipFileCompatibilityTests
{
    // Frozen against isolated CPython 3.13.16; native-packet diagnostics
    // retain separate provenance because compressed bytes are not canonical.
    public static IEnumerable<object[]> PythonControls()
    {
        yield return new object[] { "gzipfile-bytesio-writer-ownership", "import gzip,io\nsink=io.BytesIO()\nwriter=gzip.GzipFile(fileobj=sink,mode='wb',mtime=0)\nprint(writer.name,writer.mode,writer.closed,writer.writable(),writer.readable())\nprint(writer.write(b'alpha\\nbeta\\n'),writer.tell())\nwriter.close()\nprint(writer.closed,sink.closed,gzip.decompress(sink.getvalue()))\nwriter.close()\nprint(sink.closed)\n", " wb False True False\n11 11\nTrue False b'alpha\\nbeta\\n'\nFalse\n" };
        yield return new object[] { "gzipfile-header-levels-time-and-name", "import gzip,io\nfor level in [-1,0,1,2,3,4,5,6,7,8,9]:\n    sink=io.BytesIO()\n    with gzip.GzipFile(filename='dir/report.gz',fileobj=sink,mode='wb',compresslevel=level,mtime=123) as writer:\n        writer.write(b'hello hello hello')\n    data=sink.getvalue()\n    print(level,data[:10].hex(),data[10:17],gzip.decompress(data))\n", "-1 1f8b08087b00000000ff b'report\\x00' b'hello hello hello'\n0 1f8b08087b00000000ff b'report\\x00' b'hello hello hello'\n1 1f8b08087b00000004ff b'report\\x00' b'hello hello hello'\n2 1f8b08087b00000000ff b'report\\x00' b'hello hello hello'\n3 1f8b08087b00000000ff b'report\\x00' b'hello hello hello'\n4 1f8b08087b00000000ff b'report\\x00' b'hello hello hello'\n5 1f8b08087b00000000ff b'report\\x00' b'hello hello hello'\n6 1f8b08087b00000000ff b'report\\x00' b'hello hello hello'\n7 1f8b08087b00000000ff b'report\\x00' b'hello hello hello'\n8 1f8b08087b00000000ff b'report\\x00' b'hello hello hello'\n9 1f8b08087b00000002ff b'report\\x00' b'hello hello hello'\n" };
        yield return new object[] { "gzipfile-reader-metadata-and-lines", "import gzip,io\nsource=io.BytesIO(bytes.fromhex('1f8b08007b00000002ff4bcc29c848e44a4a2d49e402006e50306e0b000000'))\nreader=gzip.GzipFile(fileobj=source,mode='rb')\nprint(reader.name,reader.mode,reader.mtime,reader.tell(),reader.closed)\nprint(reader.read(0),reader.mtime)\nprint(reader.readline(),reader.mtime,reader.tell())\nprint(iter(reader) is reader,next(reader),next(reader,b'end'))\nreader.close()\nprint(reader.closed,source.closed)\n", " rb None 0 False\nb'' None\nb'alpha\\n' 123 6\nTrue b'beta\\n' b'end'\nTrue False\n" };
        yield return new object[] { "gzipfile-reader-none-size-and-concatenation", "import gzip,io\nsource=io.BytesIO(bytes.fromhex('1f8b08007b00000002ff4bcc29c848e44a4a2d49e402006e50306e0b0000001f8b0800c801000002ff2b49cccc01005db4377c04000000')+b'\\x00'*3)\nreader=gzip.GzipFile(fileobj=source)\nprint(reader.mode,reader.mtime,reader.read(None),reader.mtime,reader.tell())\nprint(reader.read(),reader.readline(),reader.readlines())\nreader.close()\nprint(source.closed)\n", "rb None b'alpha\\nbeta\\ntail' 456 15\nb'' b'' []\nFalse\n" };
        yield return new object[] { "gzipfile-empty-member-and-default-mode", "import gzip,io\nreader=gzip.GzipFile(fileobj=io.BytesIO(bytes.fromhex('1f8b08001503000002ff03000000000000000000')))\nprint(reader.mode,reader.mtime,reader.read(),reader.mtime,reader.tell())\nsink=io.BytesIO()\nwith gzip.GzipFile(fileobj=sink,mode='w',mtime=0) as writer:\n    print(writer.mode,writer.write(b''),writer.tell())\nprint(gzip.decompress(sink.getvalue()),sink.closed,len(sink.getvalue()))\n", "rb None b'' 789 0\nwb 0 0\nb'' False 20\n" };
        yield return new object[] { "gzipfile-supplied-fileobj-name-precedence", "import gzip,io\nclass Named:\n    def __init__(self):\n        self.buffer=io.BytesIO()\n        self.name='original.gz'\n        self.closed=False\n    def write(self,value): return self.buffer.write(value)\n    def flush(self): return self.buffer.flush()\n    def getvalue(self): return self.buffer.getvalue()\nsource=Named()\nwith gzip.GzipFile(filename='chosen.gz',fileobj=source,mode='wb',mtime=0) as writer:\n    print(writer.name,writer.mode)\n    writer.write(b'x')\nprint(source.closed,source.getvalue()[10:17])\n", "chosen.gz wb\nFalse b'chosen\\x00'\n" };
        yield return new object[] { "gzipfile-writer-closed-and-type-errors", "import gzip,io\nwriter=gzip.GzipFile(fileobj=io.BytesIO(),mode='wb',mtime=0)\nfor value in ['text',1,None,[]]:\n    try: writer.write(value)\n    except Exception as error: print(type(error).__name__)\nwriter.close()\nfor method,args in [(writer.read,[]),(writer.write,[b'x']),(writer.tell,[]),(writer.flush,[]),(writer.readable,[])]:\n    try: method(*args)\n    except Exception as error: print(type(error).__name__)\n", "TypeError\nTypeError\nTypeError\nTypeError\nValueError\nValueError\nValueError\nValueError\n" };
        yield return new object[] { "gzipfile-constructor-binding-and-modes", "import gzip,io\nfor args,kwargs in [([],{ 'fileobj':io.BytesIO(),'mode':'rt'}),([],{ 'fileobj':io.BytesIO(),'mode':7}),([],{'fileobj':io.BytesIO(),'unknown':1}),([None,'wb',9,io.BytesIO(),0,1],{}),([None,'wb'],{'mode':'wb','fileobj':io.BytesIO()})]:\n    try: gzip.GzipFile(*args,**kwargs)\n    except Exception as error: print(type(error).__name__)\n", "ValueError\nTypeError\nTypeError\nTypeError\nTypeError\n" };
        yield return new object[] { "gzipfile-invalid-read-streams", "import gzip,io\ngood=bytes.fromhex('1f8b08007b00000002ff4bcc29c848e44a4a2d49e402006e50306e0b000000')\nfor data in [b'invalid',good[:-1],good[:-8]+b'\\x00'*8]:\n    reader=gzip.GzipFile(fileobj=io.BytesIO(data),mode='rb')\n    try: reader.read()\n    except Exception as error: print(type(error).__name__)\n    reader.close()\n", "BadGzipFile\nEOFError\nBadGzipFile\n" };
        yield return new object[] { "gzipfile-json-and-struct-composition", "import gzip,io,json,struct\nraw=json.dumps({'name':'\u00e9\u03a9\ud83d\ude00','count':3},ensure_ascii=False).encode('utf-8')\nsink=io.BytesIO()\nwith gzip.GzipFile(fileobj=sink,mode='wb',mtime=0) as writer:\n    writer.write(struct.pack('>I',len(raw)))\n    writer.writelines([raw[:5],raw[5:]])\nwith gzip.GzipFile(fileobj=io.BytesIO(sink.getvalue()),mode='rb') as reader:\n    print(struct.unpack('>I',reader.read(4)))\n    print(json.loads(reader.read().decode('utf-8')))\nprint(sink.closed)\n", "(32,)\n{'name': '\u00e9\u03a9\ud83d\ude00', 'count': 3}\nFalse\n" };
        yield return new object[] { "gzipfile-empty-sync-flush-and-close", "import gzip,io\nfor level in [-1,0,1,9]:\n    sink=io.BytesIO()\n    writer=gzip.GzipFile(fileobj=sink,mode='wb',compresslevel=level,mtime=0)\n    print(level,sink.getvalue().hex())\n    writer.flush()\n    first=sink.getvalue()\n    writer.flush()\n    print(first.hex(),sink.getvalue()==first)\n    writer.close()\n    print(sink.getvalue().hex(),gzip.decompress(sink.getvalue()))\n", "-1 1f8b08000000000000ff\n1f8b08000000000000ff000000ffff True\n1f8b08000000000000ff000000ffff03000000000000000000 b''\n0 1f8b08000000000000ff\n1f8b08000000000000ff000000ffff True\n1f8b08000000000000ff000000ffff010000ffff0000000000000000 b''\n1 1f8b08000000000004ff\n1f8b08000000000004ff000000ffff True\n1f8b08000000000004ff000000ffff03000000000000000000 b''\n9 1f8b08000000000002ff\n1f8b08000000000002ff000000ffff True\n1f8b08000000000002ff000000ffff03000000000000000000 b''\n" };
        yield return new object[] { "gzipfile-empty-flush-before-first-write", "import gzip,io\nfor level in [0,1,9]:\n    sink=io.BytesIO()\n    writer=gzip.GzipFile(fileobj=sink,mode='wb',compresslevel=level,mtime=0)\n    writer.flush()\n    writer.write(b'tail')\n    writer.close()\n    print(level,sink.getvalue().hex(),gzip.decompress(sink.getvalue()))\n", "0 1f8b08000000000000ff000000ffff010400fbff7461696c5db4377c04000000 b'tail'\n1 1f8b08000000000004ff000000ffff2b49cccc01005db4377c04000000 b'tail'\n9 1f8b08000000000002ff000000ffff2b49cccc01005db4377c04000000 b'tail'\n" };
        yield return new object[] { "gzipfile-empty-reader-is-not-invalid", "import gzip,io\nreader=gzip.GzipFile(fileobj=io.BytesIO())\nprint(reader.mtime,reader.read(0),reader.mtime,reader.read(),reader.mtime)\nreader.close()\n", "None b'' None b'' None\n" };
        yield return new object[] { "gzipfile-trailer-errors-after-positive-read", "import gzip,io\ngood=bytes.fromhex('1f8b08007b00000002ff4bcc29c848e44a4a2d49e402006e50306e0b000000')\nfor data in [good[:-1],good[:-8]+b'\\x00'*8]:\n    reader=gzip.GzipFile(fileobj=io.BytesIO(data))\n    print(reader.read(1),reader.mtime,reader.tell())\n    try: reader.read()\n    except Exception as error: print(type(error).__name__)\n    reader.close()\n", "b'a' 123 1\nEOFError\nb'a' 123 1\nBadGzipFile\n" };
        yield return new object[] { "gzipfile-partial-concatenation-mtime", "import gzip,io\ndata=bytes.fromhex('1f8b08007b00000002ff4bcc29c848e44a4a2d49e402006e50306e0b0000001f8b0800c801000002ff2b49cccc01005db4377c04000000')\nreader=gzip.GzipFile(fileobj=io.BytesIO(data))\nprint(reader.read(1),reader.mtime)\nprint(reader.read(10),reader.mtime)\nprint(reader.read(1),reader.mtime)\nprint(reader.read(),reader.mtime)\n", "b'a' 123\nb'lpha\\nbeta\\n' 123\nb't' 456\nb'ail' 456\n" };
        yield return new object[] { "gzipfile-name-fallback-and-mode-precedence", "import gzip,io\nclass Sink:\n    def __init__(self): self.inner=io.BytesIO(); self.name=7; self.mode='wb'; self.closed=False\n    def write(self,data): return self.inner.write(data)\n    def flush(self): return None\nsink=Sink()\nwriter=gzip.GzipFile(fileobj=sink,mode='wb',mtime=0)\nprint(repr(writer.name),writer.mode,writer.write(b'x'))\nwriter.close()\nprint(sink.closed,gzip.decompress(sink.inner.getvalue()))\n", "'' wb 1\nFalse b'x'\n" };
        yield return new object[] { "gzipfile-header-writer-callback-order", "import gzip,io\nclass Sink:\n    def __init__(self): self.inner=io.BytesIO()\n    def write(self,data):\n        print('write',data.hex())\n        return self.inner.write(data)\n    def flush(self): print('flush')\nsink=Sink()\nwriter=gzip.GzipFile(filename='dir/report.gz',fileobj=sink,mode='wb',mtime=0)\nprint('created')\nwriter.write(b'x')\nprint('written')\nwriter.flush()\nprint('flushed')\nwriter.close()\nprint('closed',gzip.decompress(sink.inner.getvalue()))\n", "write 1f8b\nwrite 08\nwrite 08\nwrite 00000000\nwrite 02\nwrite ff\nwrite 7265706f727400\ncreated\nwritten\nwrite \nwrite aa00000000ffff\nflush\nflushed\nwrite 0300\nwrite 8316dc8c\nwrite 01000000\nclosed b'x'\n" };
        yield return new object[] { "gzipfile-short-source-read-protocol", "import gzip,io\nclass Source:\n    def __init__(self): self.inner=io.BytesIO(bytes.fromhex('1f8b08007b00000002ff4bcc29c848e44a4a2d49e402006e50306e0b000000')); self.closed=False\n    def read(self,size=-1): return self.inner.read(min(size,1) if size>=0 else 1)\nreader=gzip.GzipFile(fileobj=Source())\ntry: print(reader.read())\nexcept Exception as error: print(type(error).__name__)\n", "BadGzipFile\n" };
        yield return new object[] { "gzipfile-original-level-equality-controls-xfl", "import gzip,io\nclass Level:\n    def __index__(self): print('index'); return 1\n    def __eq__(self,other): print('eq',other); return other==9\nsink=io.BytesIO()\nwriter=gzip.GzipFile(fileobj=sink,mode='wb',compresslevel=Level(),mtime=0)\nwriter.close()\nprint(sink.getvalue()[:10].hex())\n", "index\neq 9\n1f8b08000000000002ff\n" };
        yield return new object[] { "gzipfile-mtime-int-conversion-callback", "import gzip,io\nclass Time:\n    def __int__(self): print('time-int'); return 123\nsink=io.BytesIO()\nwriter=gzip.GzipFile(fileobj=sink,mode='wb',mtime=Time())\nwriter.close()\nprint(sink.getvalue()[:10].hex())\n", "time-int\n1f8b08007b00000002ff\n" };
        yield return new object[] { "gzipfile-write-buffer-semantic-phases", "import gzip,io\nclass Sink:\n    def __init__(self): self.inner=io.BytesIO()\n    def write(self,data): print('write'); return self.inner.write(data)\n    def flush(self): print('flush')\nfor size in [32767,32768,32769]:\n    print('size',size)\n    sink=Sink()\n    writer=gzip.GzipFile(fileobj=sink,mode='wb',compresslevel=0,mtime=0)\n    print('created')\n    writer.write(b'x'*size)\n    print('written')\n    print('position',writer.tell())\n    writer.close()\n    print('closed',len(gzip.decompress(sink.inner.getvalue())))\n", "size 32767\nwrite\nwrite\nwrite\nwrite\nwrite\nwrite\ncreated\nwritten\nwrite\nposition 32767\nwrite\nwrite\nwrite\nclosed 32767\nsize 32768\nwrite\nwrite\nwrite\nwrite\nwrite\nwrite\ncreated\nwrite\nwritten\nposition 32768\nwrite\nwrite\nwrite\nclosed 32768\nsize 32769\nwrite\nwrite\nwrite\nwrite\nwrite\nwrite\ncreated\nwrite\nwritten\nposition 32769\nwrite\nwrite\nwrite\nclosed 32769\n" };
        yield return new object[] { "gzipfile-sync-flush-is-readable-and-incomplete", "import gzip,io\nsink=io.BytesIO()\nwriter=gzip.GzipFile(fileobj=sink,mode='wb',mtime=0)\nwriter.write(b'alpha\\nbeta\\n')\nwriter.flush()\nwith gzip.GzipFile(fileobj=io.BytesIO(sink.getvalue())) as reader:\n    print(reader.read(11))\n    try: reader.read()\n    except EOFError: print('incomplete')\nwriter.write(b'tail')\nwriter.close()\nprint(gzip.decompress(sink.getvalue()))\n", "b'alpha\\nbeta\\n'\nincomplete\nb'alpha\\nbeta\\ntail'\n" };
        yield return new object[] { "gzipfile-closed-readable-writable-queries", "import gzip,io\nfor mode in ['rb','wb']:\n    wrapper=gzip.GzipFile(fileobj=io.BytesIO(),mode=mode,mtime=0)\n    wrapper.close()\n    print(mode,wrapper.closed,wrapper.readable(),wrapper.writable())\n", "rb True True False\nwb True False True\n" };
        yield return new object[] { "gzipfile-class-and-instance-identity", "import gzip,io\nprint(type(gzip.GzipFile) is type,gzip.GzipFile.__module__,gzip.GzipFile.__name__,isinstance(gzip.GzipFile,type))\nreader=gzip.GzipFile(fileobj=io.BytesIO())\nprint(type(reader) is gzip.GzipFile,isinstance(reader,gzip.GzipFile),isinstance(reader,object))\nreader.close()\n", "False gzip GzipFile True\nTrue True True\n" };
        yield return new object[] { "gzipfile-reader-size-types-and-keywords", "import gzip,io\nraw=gzip.compress(b'alpha\\nbeta\\n',mtime=0)\nreader=gzip.GzipFile(fileobj=io.BytesIO(raw))\nfor method,value in [(reader.read,-2),(reader.readline,None),(reader.readlines,None),(reader.read,2**100)]:\n    try: method(value)\n    except Exception as error: print(type(error).__name__)\nprint(reader.read(size=2),reader.readline(size=2),reader.tell())\nreader.close()\n", "ValueError\nOverflowError\nb'' b'' 11\n" };
        yield return new object[] { "gzipfile-level-and-time-invalid-types", "import gzip,io\nfor level in [None,10,-2,2**100,2**32]:\n    try: gzip.GzipFile(fileobj=io.BytesIO(),mode='wb',compresslevel=level,mtime=0)\n    except Exception as error: print(type(error).__name__)\nfor time in [-1,2**32,float('nan'),float('inf'),None]:\n    try:\n        writer=gzip.GzipFile(fileobj=io.BytesIO(),mode='wb',mtime=time)\n        writer.close()\n        print('ok')\n    except Exception as error: print(type(error).__name__)\n", "TypeError\nValueError\nValueError\nOverflowError\nOverflowError\nerror\nerror\nValueError\nOverflowError\nok\n" };
        yield return new object[] { "gzipfile-latin1-header-names", "import gzip,io\nfor name in ['dir/caf\u00e9.gz','dir/\u03a9.gz','dir/.gz']:\n    sink=io.BytesIO()\n    with gzip.GzipFile(filename=name,fileobj=sink,mode='wb',mtime=0) as writer: writer.write(b'x')\n    data=sink.getvalue()\n    print(writer.name,data[3],gzip.decompress(data))\n", "dir/caf\u00e9.gz 8 b'x'\ndir/\u03a9.gz 0 b'x'\ndir/.gz 0 b'x'\n" };
    }

    [Theory]
    [MemberData(nameof(PythonControls))]
    public async Task BinaryWrapperFollowsFrozenPythonControls(string name, string source, string expected)
    {
        var script = new LythonEngine().Compile(source);
        Assert.True(script.IsValid, name + ": " + string.Join("; ", script.Diagnostics.Select(d => d.Message)));
        foreach (var result in new[] { script.Run(new MockLythonHost()), await script.RunAsync(new MockLythonHost()) })
        {
            Assert.True(result.Success, name + ": " + result.Failure?.Message);
            Assert.Equal(expected, result.StandardOutput);
        }
    }
}
