using Lokad.Lython.Tests.Harness;

namespace Lokad.Lython.PublicApi.Tests;

public sealed class StringIOTests
{
    public static IEnumerable<object[]> PythonControls()
    {
        yield return new object[] { "string-unicode-positions", "import io\ns=io.StringIO('a😀bc')\nprint(s.tell(), s.read(2), s.tell())\nprint(s.write('XY'), s.tell(), repr(s.getvalue()))\ns.seek(1)\nprint(s.read())", "0 a😀 2\n2 4 'a😀XY'\n😀XY\n" };
        yield return new object[] { "string-newline-None", "import io\ns=io.StringIO('a\\r\\nb\\rc\\nd', newline=None)\nprint(repr(s.getvalue()), repr(s.newlines), s.tell())\nprint([repr(line) for line in s], s.tell())\ns.seek(0)\nprint(s.write('x\\n'), repr(s.getvalue()), s.tell(), repr(s.newlines))", "'a\\nb\\nc\\nd' ('\\r', '\\n', '\\r\\n') 0\n[\"'a\\\\n'\", \"'b\\\\n'\", \"'c\\\\n'\", \"'d'\"] 7\n2 'x\\nb\\nc\\nd' 2 ('\\r', '\\n', '\\r\\n')\n" };
        yield return new object[] { "string-newline-''", "import io\ns=io.StringIO('a\\r\\nb\\rc\\nd', newline='')\nprint(repr(s.getvalue()), repr(s.newlines), s.tell())\nprint([repr(line) for line in s], s.tell())\ns.seek(0)\nprint(s.write('x\\n'), repr(s.getvalue()), s.tell(), repr(s.newlines))", "'a\\r\\nb\\rc\\nd' ('\\r', '\\n', '\\r\\n') 0\n[\"'a\\\\r\\\\n'\", \"'b\\\\r'\", \"'c\\\\n'\", \"'d'\"] 8\n2 'x\\n\\nb\\rc\\nd' 2 ('\\r', '\\n', '\\r\\n')\n" };
        yield return new object[] { "string-newline-'\\n'", "import io\ns=io.StringIO('a\\r\\nb\\rc\\nd', newline='\\n')\nprint(repr(s.getvalue()), repr(s.newlines), s.tell())\nprint([repr(line) for line in s], s.tell())\ns.seek(0)\nprint(s.write('x\\n'), repr(s.getvalue()), s.tell(), repr(s.newlines))", "'a\\r\\nb\\rc\\nd' None 0\n[\"'a\\\\r\\\\n'\", \"'b\\\\rc\\\\n'\", \"'d'\"] 8\n2 'x\\n\\nb\\rc\\nd' 2 None\n" };
        yield return new object[] { "string-newline-'\\r'", "import io\ns=io.StringIO('a\\r\\nb\\rc\\nd', newline='\\r')\nprint(repr(s.getvalue()), repr(s.newlines), s.tell())\nprint([repr(line) for line in s], s.tell())\ns.seek(0)\nprint(s.write('x\\n'), repr(s.getvalue()), s.tell(), repr(s.newlines))", "'a\\r\\rb\\rc\\rd' None 0\n[\"'a\\\\r'\", \"'\\\\r'\", \"'b\\\\r'\", \"'c\\\\r'\", \"'d'\"] 8\n2 'x\\r\\rb\\rc\\rd' 2 None\n" };
        yield return new object[] { "string-newline-'\\r\\n'", "import io\ns=io.StringIO('a\\r\\nb\\rc\\nd', newline='\\r\\n')\nprint(repr(s.getvalue()), repr(s.newlines), s.tell())\nprint([repr(line) for line in s], s.tell())\ns.seek(0)\nprint(s.write('x\\n'), repr(s.getvalue()), s.tell(), repr(s.newlines))", "'a\\r\\r\\nb\\rc\\r\\nd' None 0\n[\"'a\\\\r\\\\r\\\\n'\", \"'b\\\\rc\\\\r\\\\n'\", \"'d'\"] 10\n2 'x\\r\\n\\nb\\rc\\r\\nd' 3 None\n" };
        yield return new object[] { "string-split-newline-None", "import io\ns=io.StringIO(newline=None)\nprint(s.write('a\\r'), s.write('\\nb'), repr(s.getvalue()), repr(s.newlines))", "2 2 'a\\n\\nb' ('\\r', '\\n')\n" };
        yield return new object[] { "string-split-newline-''", "import io\ns=io.StringIO(newline='')\nprint(s.write('a\\r'), s.write('\\nb'), repr(s.getvalue()), repr(s.newlines))", "2 2 'a\\r\\nb' ('\\r', '\\n')\n" };
        yield return new object[] { "string-read-sizes", "import io\ns=io.StringIO('a😀\\nbc\\n')\nprint(repr(s.read(0)), repr(s.read(2)), repr(s.readline(1)), repr(s.readline(-1)), repr(s.read()), repr(s.read()))", "'' 'a😀' '\\n' 'bc\\n' '' ''\n" };
        yield return new object[] { "string-gap-overwrite-truncate", "import io\ns=io.StringIO('abc')\ns.seek(5)\nprint(s.write(''), repr(s.getvalue()), s.tell())\nprint(s.write('é'), repr(s.getvalue()), s.tell())\nprint(s.truncate(20), repr(s.getvalue()), s.tell())\nprint(s.truncate(2), repr(s.getvalue()), s.tell())", "0 'abc' 5\n1 'abc\\x00\\x00é' 6\n20 'abc\\x00\\x00é' 6\n2 'ab' 6\n" };
        yield return new object[] { "string-relative-seek", "import io\ns=io.StringIO('a😀')\ns.read(1)\nprint(s.seek(0,1), s.seek(0,2))\nfor offset, whence in [(1,1),(-1,2),(-1,0),(0,3)]:\n    try:\n        s.seek(offset,whence)\n    except Exception as e:\n        print(type(e).__name__)", "1 2\nOSError\nOSError\nValueError\nValueError\n" };
        yield return new object[] { "string-iterator-identity", "import io\ns=io.StringIO('a\\nb\\nc')\nprint(iter(s) is s, repr(next(s)), repr(s.readline()), list(s), next(s,'empty'))", "True 'a\\n' 'b\\n' ['c'] empty\n" };
        yield return new object[] { "string-readlines-hint", "import io\nfor hint in [0,1,2,3,-1]:\n    s=io.StringIO('a\\nb\\nc')\n    print(hint, s.readlines(hint), repr(s.read()))", "0 ['a\\n', 'b\\n', 'c'] ''\n1 ['a\\n'] 'b\\nc'\n2 ['a\\n', 'b\\n'] 'c'\n3 ['a\\n', 'b\\n'] 'c'\n-1 ['a\\n', 'b\\n', 'c'] ''\n" };
        yield return new object[] { "string-context-close", "import io\nwith io.StringIO('abc') as s:\n    print(s.closed, s.readable(), s.writable(), s.seekable(), s.flush())\nprint(s.closed, s.close())\nfor call in [lambda:s.read(),lambda:s.write('x'),lambda:s.getvalue(),lambda:s.tell(),lambda:s.seek(0),lambda:s.truncate(),lambda:s.flush()]:\n    try:\n        call()\n    except Exception as e:\n        print(type(e).__name__)", "False True True True None\nTrue None\nValueError\nValueError\nValueError\nValueError\nValueError\nValueError\n" };
        yield return new object[] { "string-json-csv-composition", "import io\nimport json,csv\ns=io.StringIO()\ncsv.writer(s,lineterminator='\\n').writerows([['a','b'],['😀',3]])\nprint(repr(s.getvalue()))\ns.seek(0)\nprint(list(csv.reader(s)))\ns=io.StringIO()\njson.dump({'x':'😀'},s,ensure_ascii=False)\ns.seek(0)\nprint(json.load(s))", "'a,b\\n😀,3\\n'\n[['a', 'b'], ['😀', '3']]\n{'x': '😀'}\n" };
        yield return new object[] { "string-writelines", "import io\ns=io.StringIO()\nprint(s.writelines(x for x in ['a','\\n','b']), repr(s.getvalue()))\ntry:\n    s.writelines(['c',7,'d'])\nexcept TypeError:\n    print(repr(s.getvalue()))", "None 'a\\nb'\n'a\\nbc'\n" };
        yield return new object[] { "string-error-io.StringIO(b'x')", "import io\ntry:\n    io.StringIO(b'x')\nexcept Exception as e:\n    print(type(e).__name__)", "TypeError\n" };
        yield return new object[] { "string-error-io.StringIO('x', newline=7)", "import io\ntry:\n    io.StringIO('x', newline=7)\nexcept Exception as e:\n    print(type(e).__name__)", "TypeError\n" };
        yield return new object[] { "string-error-io.StringIO('x', newline='bad')", "import io\ntry:\n    io.StringIO('x', newline='bad')\nexcept Exception as e:\n    print(type(e).__name__)", "ValueError\n" };
        yield return new object[] { "string-error-io.StringIO().write(b'x')", "import io\ntry:\n    io.StringIO().write(b'x')\nexcept Exception as e:\n    print(type(e).__name__)", "TypeError\n" };
        yield return new object[] { "string-error-io.StringIO().read(1.5)", "import io\ntry:\n    io.StringIO().read(1.5)\nexcept Exception as e:\n    print(type(e).__name__)", "TypeError\n" };
        yield return new object[] { "string-metadata", "from io import StringIO as S, SEEK_SET, SEEK_CUR, SEEK_END\ns=S(None)\nprint(type(s) is S, isinstance(s,S), type(S) is type, S.__name__, S.__module__)\nprint(SEEK_SET,SEEK_CUR,SEEK_END,s.encoding,s.errors,s.line_buffering)\nprint(s.read(None),s.readline(None),s.readlines(None),s.truncate(None))\nprint(s.seek(True,False))", "True True True StringIO _io\n0 1 2 None None False\n  [] 0\n1\n" };
        yield return new object[] { "string-print", "import io\ns=io.StringIO(newline='\\r\\n')\nprint('é', '😀', sep=':', file=s, flush=True)\nprint(repr(s.getvalue()), s.tell())", "'é:😀\\r\\n' 5\n" };
        yield return new object[] { "string-index", "import io\nclass Index:\n    def __index__(self):\n        return 2\nx=Index()\nx.__index__=lambda: 0\ns=io.StringIO('a😀bc\\ndef')\nprint(repr(s.read(x)),s.tell())\nprint(s.seek(x), repr(s.readline(x)))\nprint(s.truncate(x),repr(s.getvalue()))\nclass Bad:\n    def __index__(self):\n        return 'bad'\nfor call in [lambda:s.read(Bad()),lambda:s.seek(Bad()),lambda:s.truncate(Bad())]:\n    try:\n        call()\n    except TypeError:\n        print('bad')", "'a😀' 2\n2 'bc'\n2 'a😀'\nbad\nbad\nbad\n" };
        yield return new object[] { "string-errors", "import io\ndef calls(s):\n    return [lambda:s.read(size=1),lambda:s.write(s='x'),lambda:s.seek(pos=1),lambda:s.read(10**100),lambda:s.seek(10**100),lambda:s.truncate(10**100),lambda:s.seek(0,2**40)]\nfor call in calls(io.StringIO()):\n    try:\n        call()\n    except Exception as e:\n        print(type(e).__name__)", "TypeError\nTypeError\nTypeError\nOverflowError\nOverflowError\nOverflowError\nOverflowError\n" };
        yield return new object[] { "string-closed-priority", "import io\ns=io.StringIO();s.close()\nfor call in [lambda:s.write(7),lambda:s.read(7.2),lambda:s.seek(7.2),lambda:s.truncate(-1),lambda:s.newlines,lambda:s.line_buffering,lambda:iter(s),lambda:s.writelines(7),lambda:s.readlines(None),lambda:s.readable(),lambda:s.writable(),lambda:s.seekable()]:\n    try:\n        call()\n    except Exception as e:\n        print(type(e).__name__)\nprint(s.encoding,s.errors,s.closed,s.close())", "TypeError\nTypeError\nTypeError\nValueError\nValueError\nValueError\nValueError\nValueError\nValueError\nValueError\nValueError\nValueError\nNone None True None\n" };
        yield return new object[] { "string-snapshot", "import io\ns=io.StringIO('é😀abc')\na=s.getvalue()\ns.write('XY');b=s.getvalue();s.truncate(1);c=s.getvalue();s.close()\nprint(repr(a),repr(b),repr(c))", "'é😀abc' 'XYabc' 'X'\n" };
        yield return new object[] { "string-newline-history", "import io\nfor newline in [None,'']:\n    s=io.StringIO(newline=newline)\n    for text in ['a\\r','\\nb','\\r\\n','\\r\\r\\n','x\\n']:\n        print(s.write(text),repr(s.newlines),repr(s.getvalue()))\n    s.truncate(0)\n    print(repr(s.newlines))", "2 '\\r' 'a\\n'\n2 ('\\r', '\\n') 'a\\n\\nb'\n2 ('\\r', '\\n', '\\r\\n') 'a\\n\\nb\\n'\n3 ('\\r', '\\n', '\\r\\n') 'a\\n\\nb\\n\\n\\n'\n2 ('\\r', '\\n', '\\r\\n') 'a\\n\\nb\\n\\n\\nx\\n'\n('\\r', '\\n', '\\r\\n')\n2 '\\r' 'a\\r'\n2 ('\\r', '\\n') 'a\\r\\nb'\n2 ('\\r', '\\n', '\\r\\n') 'a\\r\\nb\\r\\n'\n3 ('\\r', '\\n', '\\r\\n') 'a\\r\\nb\\r\\n\\r\\r\\n'\n2 ('\\r', '\\n', '\\r\\n') 'a\\r\\nb\\r\\n\\r\\r\\nx\\n'\n('\\r', '\\n', '\\r\\n')\n" };
        yield return new object[] { "string-lines-None-0", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline=None)\nfor _ in range(8):\n    print(repr(s.readline(0)),s.tell())", "'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n" };
        yield return new object[] { "string-lines-None-1", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline=None)\nfor _ in range(8):\n    print(repr(s.readline(1)),s.tell())", "'😀' 1\n'\\n' 2\n'\\n' 3\n'x' 4\n'\\n' 5\n'y' 6\n'\\n' 7\n'z' 8\n" };
        yield return new object[] { "string-lines-None-2", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline=None)\nfor _ in range(8):\n    print(repr(s.readline(2)),s.tell())", "'😀\\n' 2\n'\\n' 3\n'x\\n' 5\n'y\\n' 7\n'z' 8\n'' 8\n'' 8\n'' 8\n" };
        yield return new object[] { "string-lines-None-3", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline=None)\nfor _ in range(8):\n    print(repr(s.readline(3)),s.tell())", "'😀\\n' 2\n'\\n' 3\n'x\\n' 5\n'y\\n' 7\n'z' 8\n'' 8\n'' 8\n'' 8\n" };
        yield return new object[] { "string-lines-None--1", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline=None)\nfor _ in range(8):\n    print(repr(s.readline(-1)),s.tell())", "'😀\\n' 2\n'\\n' 3\n'x\\n' 5\n'y\\n' 7\n'z' 8\n'' 8\n'' 8\n'' 8\n" };
        yield return new object[] { "string-lines-''-0", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='')\nfor _ in range(8):\n    print(repr(s.readline(0)),s.tell())", "'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n" };
        yield return new object[] { "string-lines-''-1", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='')\nfor _ in range(8):\n    print(repr(s.readline(1)),s.tell())", "'😀' 1\n'\\r' 2\n'\\r' 3\n'\\n' 4\n'x' 5\n'\\r' 6\n'y' 7\n'\\n' 8\n" };
        yield return new object[] { "string-lines-''-2", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='')\nfor _ in range(8):\n    print(repr(s.readline(2)),s.tell())", "'😀\\r' 2\n'\\r\\n' 4\n'x\\r' 6\n'y\\n' 8\n'z' 9\n'' 9\n'' 9\n'' 9\n" };
        yield return new object[] { "string-lines-''-3", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='')\nfor _ in range(8):\n    print(repr(s.readline(3)),s.tell())", "'😀\\r' 2\n'\\r\\n' 4\n'x\\r' 6\n'y\\n' 8\n'z' 9\n'' 9\n'' 9\n'' 9\n" };
        yield return new object[] { "string-lines-''--1", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='')\nfor _ in range(8):\n    print(repr(s.readline(-1)),s.tell())", "'😀\\r' 2\n'\\r\\n' 4\n'x\\r' 6\n'y\\n' 8\n'z' 9\n'' 9\n'' 9\n'' 9\n" };
        yield return new object[] { "string-lines-'\\n'-0", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\n')\nfor _ in range(8):\n    print(repr(s.readline(0)),s.tell())", "'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n" };
        yield return new object[] { "string-lines-'\\n'-1", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\n')\nfor _ in range(8):\n    print(repr(s.readline(1)),s.tell())", "'😀' 1\n'\\r' 2\n'\\r' 3\n'\\n' 4\n'x' 5\n'\\r' 6\n'y' 7\n'\\n' 8\n" };
        yield return new object[] { "string-lines-'\\n'-2", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\n')\nfor _ in range(8):\n    print(repr(s.readline(2)),s.tell())", "'😀\\r' 2\n'\\r\\n' 4\n'x\\r' 6\n'y\\n' 8\n'z' 9\n'' 9\n'' 9\n'' 9\n" };
        yield return new object[] { "string-lines-'\\n'-3", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\n')\nfor _ in range(8):\n    print(repr(s.readline(3)),s.tell())", "'😀\\r\\r' 3\n'\\n' 4\n'x\\ry' 7\n'\\n' 8\n'z' 9\n'' 9\n'' 9\n'' 9\n" };
        yield return new object[] { "string-lines-'\\n'--1", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\n')\nfor _ in range(8):\n    print(repr(s.readline(-1)),s.tell())", "'😀\\r\\r\\n' 4\n'x\\ry\\n' 8\n'z' 9\n'' 9\n'' 9\n'' 9\n'' 9\n'' 9\n" };
        yield return new object[] { "string-lines-'\\r'-0", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\r')\nfor _ in range(8):\n    print(repr(s.readline(0)),s.tell())", "'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n" };
        yield return new object[] { "string-lines-'\\r'-1", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\r')\nfor _ in range(8):\n    print(repr(s.readline(1)),s.tell())", "'😀' 1\n'\\r' 2\n'\\r' 3\n'\\r' 4\n'x' 5\n'\\r' 6\n'y' 7\n'\\r' 8\n" };
        yield return new object[] { "string-lines-'\\r'-2", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\r')\nfor _ in range(8):\n    print(repr(s.readline(2)),s.tell())", "'😀\\r' 2\n'\\r' 3\n'\\r' 4\n'x\\r' 6\n'y\\r' 8\n'z' 9\n'' 9\n'' 9\n" };
        yield return new object[] { "string-lines-'\\r'-3", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\r')\nfor _ in range(8):\n    print(repr(s.readline(3)),s.tell())", "'😀\\r' 2\n'\\r' 3\n'\\r' 4\n'x\\r' 6\n'y\\r' 8\n'z' 9\n'' 9\n'' 9\n" };
        yield return new object[] { "string-lines-'\\r'--1", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\r')\nfor _ in range(8):\n    print(repr(s.readline(-1)),s.tell())", "'😀\\r' 2\n'\\r' 3\n'\\r' 4\n'x\\r' 6\n'y\\r' 8\n'z' 9\n'' 9\n'' 9\n" };
        yield return new object[] { "string-lines-'\\r\\n'-0", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\r\\n')\nfor _ in range(8):\n    print(repr(s.readline(0)),s.tell())", "'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n'' 0\n" };
        yield return new object[] { "string-lines-'\\r\\n'-1", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\r\\n')\nfor _ in range(8):\n    print(repr(s.readline(1)),s.tell())", "'😀' 1\n'\\r' 2\n'\\r' 3\n'\\r' 4\n'\\n' 5\n'x' 6\n'\\r' 7\n'y' 8\n" };
        yield return new object[] { "string-lines-'\\r\\n'-2", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\r\\n')\nfor _ in range(8):\n    print(repr(s.readline(2)),s.tell())", "'😀\\r' 2\n'\\r\\r' 4\n'\\nx' 6\n'\\ry' 8\n'\\r\\n' 10\n'z' 11\n'' 11\n'' 11\n" };
        yield return new object[] { "string-lines-'\\r\\n'-3", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\r\\n')\nfor _ in range(8):\n    print(repr(s.readline(3)),s.tell())", "'😀\\r\\r' 3\n'\\r\\n' 5\n'x\\ry' 8\n'\\r\\n' 10\n'z' 11\n'' 11\n'' 11\n'' 11\n" };
        yield return new object[] { "string-lines-'\\r\\n'--1", "import io\ns=io.StringIO('😀\\r\\r\\nx\\ry\\nz',newline='\\r\\n')\nfor _ in range(8):\n    print(repr(s.readline(-1)),s.tell())", "'😀\\r\\r\\r\\n' 5\n'x\\ry\\r\\n' 10\n'z' 11\n'' 11\n'' 11\n'' 11\n'' 11\n'' 11\n" };
    }

    [Theory]
    [MemberData(nameof(PythonControls))]
    public async Task MatchesPython(string name, string source, string expected)
    {
        _ = name;
        var script = new LythonEngine().Compile(source);
        Assert.True(script.IsValid, string.Join("; ", script.Diagnostics.Select(d => d.Code + ": " + d.Message)));
        foreach (var result in new[] { script.Run(new MockLythonHost()), await script.RunAsync(new MockLythonHost()) })
        {
            Assert.True(result.Success, result.Failure?.Message);
            Assert.Equal(expected, result.StandardOutput);
        }
    }
}
